git add README.MD
git add wcserver/WcSDK-DotNet.sln
git add wcserver/c#/WinServerAPI/Properties/AssemblyInfo.cs
git add wcserver/c#/WinServerAPI/WinServerAPI.csproj
git add wcserver/c#/WinServerAPI/bin/Debug/WinServerAPI.dll
git add wcserver/c#/WinServerAPI/bin/Debug/WinServerAPI.pdb
git add wcserver/c#/examples/BSMiniRPTC#.NET/BSMiniRPT-CS.csproj
git add wcserver/c#/examples/BSMiniRPTC#.NET/BSMiniRPT-CS.csproj.user
git add wcserver/c#/examples/BSMiniRPTC#.NET/bin/BSMiniRPT.exe
git add wcserver/c#/examples/BSMiniRPTC#.NET/bin/BSMiniRPT.pdb
git add wcserver/c#/examples/BSMiniRPTC#.NET/bin/WinServerAPI.dll
git add wcserver/c#/examples/BSMiniRPTC#.NET/bin/WinServerAPI.pdb
git add wcserver/c#/includes/wcMakeWildAPI.cs
git add wcserver/c#/includes/wcMimeLib.cs
git add wcserver/c#/includes/wcServerAPI.cs
git add wcserver/vb.net/examples/BSMiniRPT.NET/BSMiniRPT-VBNET.vbproj
git add wcserver/vb.net/examples/BSMiniRPT.NET/BSMiniRPT-VBNET.vbproj.user
git add wcserver/vb.net/examples/BSMiniRPT.NET/bin/BSMiniRPT.exe
git add wcserver/vb.net/examples/BSMiniRPT.NET/bin/BSMiniRPT.pdb
git add wcserver/vb.net/examples/BSMiniRPT.NET/bin/WinServerAPI.dll
git add wcserver/vb.net/examples/BSMiniRPT.NET/bin/WinServerAPI.pdb
git add wcserver/vb.net/examples/wcChat.net/wcChat.NET.vbproj
git add wcserver/vb.net/examples/wcChat.net/wcChat.NET.vbproj.user
