    git rm   .gitattributes --cached
    git rm   .gitignore --cached
    git rm   CVS/Entries --cached
    git rm   CVS/Entries.Extra --cached
    git rm   CVS/Entries.Extra.Old --cached
    git rm   CVS/Entries.Old --cached
    git rm   CVS/Repository --cached
    git rm   CVS/Root --cached
    git rm   CVS/readme.md,t --cached
    git rm   Stage.cmd --cached
    git rm   UnmanagedCode.pdf --cached
    git rm   WcSDK-master-20200510.zip --cached
    git rm   WcSDK-master-20200522-1.zip --cached
    git rm   WcSDK-master-20200522.zip --cached
    git rm   WcSDK-master.zip --cached
    git rm   cvs-status-20200416.txt --cached
    git rm   describe --cached
    git rm   foo --cached
    git rm   foo.bak --cached
    git rm   git-push.cmd --cached
    git rm   git-questions.txt --cached
    git rm   git-readme.txt --cached
    git rm   git-update1.cmd --cached
    git rm   goo --cached
    git rm   help/CVS/Entries --cached
    git rm   help/CVS/Entries.Extra --cached
    git rm   help/CVS/Entries.Extra.Old --cached
    git rm   help/CVS/Entries.Old --cached
    git rm   help/CVS/Repository --cached
    git rm   help/CVS/Root --cached
    git rm   notes.txt --cached
    git rm   readme-now.txt --cached
    git rm   sample-stack.cs --cached
    git rm   sample.txt --cached
    git rm   update-20200510.cmd --cached
    git rm   update-20200516.cmd --cached
    git rm   update-20200522.bak --cached
    git rm   update-20200522.cmd --cached
    git rm   wcnav16/CVS/Entries --cached
    git rm   wcnav16/CVS/Entries.Extra --cached
    git rm   wcnav16/CVS/Entries.Extra.Old --cached
    git rm   wcnav16/CVS/Entries.Old --cached
    git rm   wcnav16/CVS/Repository --cached
    git rm   wcnav16/CVS/Root --cached
    git rm   wcnav16/include/CVS/Entries --cached

    git rm   wcnav16/include/CVS/Entries.Extra --cached
    git rm   wcnav16/include/CVS/Entries.Extra.Old --cached
    git rm   wcnav16/include/CVS/Entries.Old --cached
    git rm   wcnav16/include/CVS/Repository --cached
    git rm   wcnav16/include/CVS/Root --cached
    git rm   wcnav16/include/cpp/CVS/Entries --cached
    git rm   wcnav16/include/cpp/CVS/Entries.Extra --cached
    git rm   wcnav16/include/cpp/CVS/Entries.Extra.Old --cached
    git rm   wcnav16/include/cpp/CVS/Entries.Old --cached
    git rm   wcnav16/include/cpp/CVS/Repository --cached
    git rm   wcnav16/include/cpp/CVS/Root --cached
    git rm   wcnav16/include/cpp/cloadpxy.cpp --cached
    git rm   wcnav16/include/cpp/cloadpxy.h --cached
    git rm   wcnav16/include/cpp/cloadsys.cpp --cached
    git rm   wcnav16/include/cpp/cloadsys.h --cached
    git rm   wcnav16/include/cpp/wccache.h --cached
    git rm   wcnav16/include/cpp/wcgui.h --cached
    git rm   wcnav16/include/cpp/wcstype.h --cached
    git rm   wcnav16/include/cpp/wctype.h --cached
    git rm   wcnav16/include/cpp/wildsock.h --cached
    git rm   wcnav16/include/delphi16/CVS/Entries --cached
    git rm   wcnav16/include/delphi16/CVS/Entries.Extra --cached
    git rm   wcnav16/include/delphi16/CVS/Entries.Extra.Old --cached
    git rm   wcnav16/include/delphi16/CVS/Entries.Old --cached
    git rm   wcnav16/include/delphi16/CVS/Repository --cached
    git rm   wcnav16/include/delphi16/CVS/Root --cached
    git rm   wcnav16/include/delphi16/cloadpxy.pas --cached
    git rm   wcnav16/include/delphi16/cloadsys.pas --cached
    git rm   wcnav16/include/delphi16/wccache.pas --cached
    git rm   wcnav16/include/delphi16/wcgui.pas --cached
    git rm   wcnav16/include/delphi16/wchkeys.pas --cached
    git rm   wcnav16/include/delphi16/wcserror.pas --cached
    git rm   wcnav16/include/delphi16/wcstype.pas --cached
    git rm   wcnav16/include/delphi16/wctype.pas --cached
    git rm   wcnav16/lib/CVS/Entries --cached
    git rm   wcnav16/lib/CVS/Entries.Extra --cached
    git rm   wcnav16/lib/CVS/Entries.Extra.Old --cached
    git rm   wcnav16/lib/CVS/Entries.Old --cached
    git rm   wcnav16/lib/CVS/Repository --cached
    git rm   wcnav16/lib/CVS/Root --cached
    git rm   wcsdk-file-list.txt --cached
    git rm   wcsdk61-layout.png --cached
    git rm   wcserver/CVS/Entries --cached
    git rm   wcserver/CVS/Entries.Extra --cached
    git rm   wcserver/CVS/Entries.Extra.Old --cached
    git rm   wcserver/CVS/Entries.Old --cached
    git rm   wcserver/CVS/Repository --cached
    git rm   wcserver/CVS/Root --cached
    git rm   wcserver/c#/CVS/Entries --cached
    git rm   wcserver/c#/CVS/Entries.Extra --cached
    git rm   wcserver/c#/CVS/Entries.Extra.Old --cached
    git rm   wcserver/c#/CVS/Entries.Old --cached
    git rm   wcserver/c#/CVS/Repository --cached
    git rm   wcserver/c#/CVS/Root --cached
    git rm   wcserver/c#/WinServerAPI/CVS/Entries --cached
    git rm   wcserver/c#/WinServerAPI/CVS/Entries.Extra --cached
    git rm   wcserver/c#/WinServerAPI/CVS/Entries.Extra.Old --cached
    git rm   wcserver/c#/WinServerAPI/CVS/Entries.Old --cached
    git rm   wcserver/c#/WinServerAPI/CVS/Repository --cached
    git rm   wcserver/c#/WinServerAPI/CVS/Root --cached
    git rm   wcserver/c#/WinServerAPI/CVS/WinServerAPI.csproj,t --cached
    git rm   wcserver/c#/WinServerAPI/Properties/CVS/AssemblyInfo.cs,t --cached
    git rm   wcserver/c#/WinServerAPI/Properties/CVS/Entries --cached
    git rm   wcserver/c#/WinServerAPI/Properties/CVS/Entries.Extra --cached
    git rm   wcserver/c#/WinServerAPI/Properties/CVS/Entries.Extra.Old --cached
    git rm   wcserver/c#/WinServerAPI/Properties/CVS/Entries.Old --cached
    git rm   wcserver/c#/WinServerAPI/Properties/CVS/Repository --cached
    git rm   wcserver/c#/WinServerAPI/Properties/CVS/Root --cached
    git rm   wcserver/c#/WinServerAPI/WinServerAPI.bak --cached
    git rm   wcserver/c#/examples/BSMiniRPTC#.NET/CVS/Entries --cached
    git rm   wcserver/c#/examples/BSMiniRPTC#.NET/CVS/Entries.Extra --cached
    git rm   wcserver/c#/examples/BSMiniRPTC#.NET/CVS/Entries.Extra.Old --cached
    git rm   wcserver/c#/examples/BSMiniRPTC#.NET/CVS/Entries.Old --cached
    git rm   wcserver/c#/examples/BSMiniRPTC#.NET/CVS/Repository --cached
    git rm   wcserver/c#/examples/BSMiniRPTC#.NET/CVS/Root --cached
    git rm   wcserver/c#/examples/BSMiniRPTC#.NET/My Project/CVS/Application.Designer.cs,t --cached
    git rm   wcserver/c#/examples/BSMiniRPTC#.NET/My Project/CVS/Application.myapp,t --cached
    git rm   wcserver/c#/examples/BSMiniRPTC#.NET/My Project/CVS/Entries --cached
    git rm   wcserver/c#/examples/BSMiniRPTC#.NET/My Project/CVS/Entries.Extra --cached
    git rm   wcserver/c#/examples/BSMiniRPTC#.NET/My Project/CVS/Entries.Extra.Old --cached
    git rm   wcserver/c#/examples/BSMiniRPTC#.NET/My Project/CVS/Entries.Old --cached
    git rm   wcserver/c#/examples/BSMiniRPTC#.NET/My Project/CVS/Repository --cached
    git rm   wcserver/c#/examples/BSMiniRPTC#.NET/My Project/CVS/Root --cached
    git rm   wcserver/c#/examples/CVS/Entries --cached
    git rm   wcserver/c#/examples/CVS/Entries.Extra --cached
    git rm   wcserver/c#/examples/CVS/Entries.Extra.Old --cached
    git rm   wcserver/c#/examples/CVS/Entries.Old --cached
    git rm   wcserver/c#/examples/CVS/Repository --cached
    git rm   wcserver/c#/examples/CVS/Root --cached
    git rm   wcserver/c#/examples/Misc/HelloWildcat!.cs --cached
    git rm   wcserver/c#/examples/Misc/HelloWildcat!.exe --cached
    git rm   wcserver/c#/examples/Misc/WinServerAPI.dll --cached
    git rm   wcserver/c#/examples/Misc/csc.txt --cached
    git rm   wcserver/c#/examples/Misc/describe --cached
    git rm   wcserver/c#/examples/Misc/qrun.dat --cached
    git rm   wcserver/c#/examples/Misc/test-argslib.cs --cached
    git rm   wcserver/c#/examples/Misc/test-argslib.exe --cached
    git rm   wcserver/c#/examples/Misc/wcsmw.dll --cached
    git rm   wcserver/c#/examples/Misc/wcsrv2.dll --cached
    git rm   wcserver/c#/examples/Misc/wcvb.dll --cached
    git rm   wcserver/c#/examples/WindowsFormsApplication1/App.config --cached
    git rm   wcserver/c#/examples/WindowsFormsApplication1/Form1.Designer.cs --cached
    git rm   wcserver/c#/examples/WindowsFormsApplication1/Form1.cs --cached
    git rm   wcserver/c#/examples/WindowsFormsApplication1/Form1.resx --cached
    git rm   wcserver/c#/examples/WindowsFormsApplication1/Program.cs --cached
    git rm   wcserver/c#/examples/WindowsFormsApplication1/Properties/AssemblyInfo.cs --cached
    git rm   wcserver/c#/examples/WindowsFormsApplication1/Properties/Resources.Designer.cs --cached
    git rm   wcserver/c#/examples/WindowsFormsApplication1/Properties/Resources.resx --cached
    git rm   wcserver/c#/examples/WindowsFormsApplication1/Properties/Settings.Designer.cs --cached
    git rm   wcserver/c#/examples/WindowsFormsApplication1/Properties/Settings.settings --cached
    git rm   wcserver/c#/examples/WindowsFormsApplication1/WindowsFormsApplication1.csproj --cached
    git rm   wcserver/c#/examples/WindowsFormsApplication1/wcServerAPI.cs --cached
    git rm   wcserver/c#/examples/wcDoor32/wcDoor32-example1/wcDoor32-Example1-Program.cs.1 --cached
    git rm   wcserver/c#/examples/wcDoor32/wcDoor32-example1/wcDoor32-Example1-Program.cs.2 --cached
    git rm   wcserver/c#/examples/wcDoor32/wcDoor32-example1/wcDoor32-Example1-Program.cs.3 --cached
    git rm   wcserver/c#/examples/wcDoor32/wcDoor32-example1/wcDoor32-Example1-Program.cs.4 --cached
    git rm   wcserver/c#/examples/wcDoor32/wcDoor32-example1/wcDoor32-Example1-Program.cs.5 --cached
    git rm   wcserver/c#/examples/wcDoor32/wcDoor32-example1/wcDoor32-Example1-Program.cs.6 --cached
    git rm   wcserver/c#/examples/wcDoor32/wcDoor32-example1/wcDoor32-Example1-Program.cs.7 --cached
    git rm   wcserver/c#/examples/wcDoor32/wcDoor32-example2/foo --cached
    git rm   wcserver/c#/examples/wcDoor32/wcDoor32-example2/foo.bak --cached
    git rm   wcserver/c#/examples/wcDoor32/wcDoor32-example2/wcDoor32-Example2-Program.cs.1 --cached
    git rm   wcserver/c#/examples/wcDoor32/wcDoor32-example2/wcDoor32-Example2-Program.cs.2 --cached
    git rm   wcserver/c#/includes/CVS/Entries --cached
    git rm   wcserver/c#/includes/CVS/Entries.Extra --cached
    git rm   wcserver/c#/includes/CVS/Entries.Extra.Old --cached
    git rm   wcserver/c#/includes/CVS/Entries.Old --cached
    git rm   wcserver/c#/includes/CVS/Repository --cached
    git rm   wcserver/c#/includes/CVS/Root --cached
    git rm   wcserver/c#/includes/Wildcat.Console.cs.1 --cached
    git rm   wcserver/c#/includes/crap --cached
    git rm   wcserver/c#/includes/crap2 --cached
    git rm   wcserver/c#/includes/describe.bak --cached
    git rm   wcserver/c#/includes/foo --cached
    git rm   wcserver/c#/includes/wcBasic-cmdline.bak --cached
    git rm   wcserver/c#/includes/wcDoor32API.cs.1 --cached
    git rm   wcserver/c#/includes/wcDoor32API.cs.2 --cached
    git rm   wcserver/c#/includes/wcDoor32API.cs.3 --cached
    git rm   wcserver/c#/includes/wcMakeWildAPI.cs.1 --cached
    git rm   wcserver/c#/includes/wcMimeLib.cs.1 --cached
    git rm   wcserver/c#/includes/wcServerAPI.cs.1 --cached
    git rm   wcserver/cpp.net/CVS/Entries --cached
    git rm   wcserver/cpp.net/CVS/Entries.Extra --cached
    git rm   wcserver/cpp.net/CVS/Entries.Extra.Old --cached
    git rm   wcserver/cpp.net/CVS/Entries.Old --cached
    git rm   wcserver/cpp.net/CVS/Repository --cached
    git rm   wcserver/cpp.net/CVS/Root --cached
    git rm   wcserver/cpp.net/CVS/wchello.cpp,t --cached
    git rm   wcserver/cpp/CVS/Entries --cached
    git rm   wcserver/cpp/CVS/Entries.Extra --cached
    git rm   wcserver/cpp/CVS/Entries.Extra.Old --cached
    git rm   wcserver/cpp/CVS/Entries.Old --cached
    git rm   wcserver/cpp/CVS/Repository --cached
    git rm   wcserver/cpp/CVS/Root --cached
    git rm   wcserver/cpp/examples/CVS/Entries --cached
    git rm   wcserver/cpp/examples/CVS/Entries.Extra --cached
    git rm   wcserver/cpp/examples/CVS/Entries.Extra.Old --cached
    git rm   wcserver/cpp/examples/CVS/Entries.Old --cached
    git rm   wcserver/cpp/examples/CVS/Entries.bak --cached
    git rm   wcserver/cpp/examples/CVS/Repository --cached
    git rm   wcserver/cpp/examples/CVS/Root --cached
    git rm   wcserver/cpp/examples/EchoServer/CVS/Entries --cached
    git rm   wcserver/cpp/examples/EchoServer/CVS/Entries.Extra --cached
    git rm   wcserver/cpp/examples/EchoServer/CVS/Entries.Extra.Old --cached
    git rm   wcserver/cpp/examples/EchoServer/CVS/Entries.Old --cached
    git rm   wcserver/cpp/examples/EchoServer/CVS/Repository --cached
    git rm   wcserver/cpp/examples/EchoServer/CVS/Root --cached
    git rm   wcserver/cpp/examples/ListMsgs/CVS/Entries --cached
    git rm   wcserver/cpp/examples/ListMsgs/CVS/Entries.Extra --cached
    git rm   wcserver/cpp/examples/ListMsgs/CVS/Entries.Extra.Old --cached
    git rm   wcserver/cpp/examples/ListMsgs/CVS/Entries.Old --cached
    git rm   wcserver/cpp/examples/ListMsgs/CVS/Repository --cached
    git rm   wcserver/cpp/examples/ListMsgs/CVS/Root --cached
    git rm   wcserver/cpp/examples/ListMsgs/Res/CVS/Entries --cached
    git rm   wcserver/cpp/examples/ListMsgs/Res/CVS/Entries.Extra --cached
    git rm   wcserver/cpp/examples/ListMsgs/Res/CVS/Entries.Extra.Old --cached
    git rm   wcserver/cpp/examples/ListMsgs/Res/CVS/Entries.Old --cached
    git rm   wcserver/cpp/examples/ListMsgs/Res/CVS/Repository --cached
    git rm   wcserver/cpp/examples/ListMsgs/Res/CVS/Root --cached
REM git rm   wcserver/cpp/examples/ListMsgs/readmsg.rc --cached
    git rm   wcserver/cpp/examples/ListUser/CVS/Entries --cached
    git rm   wcserver/cpp/examples/ListUser/CVS/Entries.Extra --cached
    git rm   wcserver/cpp/examples/ListUser/CVS/Entries.Extra.Old --cached
    git rm   wcserver/cpp/examples/ListUser/CVS/Entries.Old --cached
    git rm   wcserver/cpp/examples/ListUser/CVS/Repository --cached
    git rm   wcserver/cpp/examples/ListUser/CVS/Root --cached
    git rm   wcserver/cpp/examples/ListUser/Res/CVS/Entries --cached
    git rm   wcserver/cpp/examples/ListUser/Res/CVS/Entries.Extra --cached
    git rm   wcserver/cpp/examples/ListUser/Res/CVS/Entries.Extra.Old --cached
    git rm   wcserver/cpp/examples/ListUser/Res/CVS/Entries.Old --cached
    git rm   wcserver/cpp/examples/ListUser/Res/CVS/Repository --cached
    git rm   wcserver/cpp/examples/ListUser/Res/CVS/Root --cached
REM git rm   wcserver/cpp/examples/ListUser/userlist.rc --cached
    git rm   wcserver/cpp/examples/TriviaServer/CVS/Entries --cached
    git rm   wcserver/cpp/examples/TriviaServer/CVS/Entries.Extra --cached
    git rm   wcserver/cpp/examples/TriviaServer/CVS/Entries.Extra.Old --cached
    git rm   wcserver/cpp/examples/TriviaServer/CVS/Entries.Old --cached
    git rm   wcserver/cpp/examples/TriviaServer/CVS/Repository --cached
    git rm   wcserver/cpp/examples/TriviaServer/CVS/Root --cached
    git rm   wcserver/cpp/examples/channels/CVS/Entries --cached
    git rm   wcserver/cpp/examples/channels/CVS/Entries.Extra --cached
    git rm   wcserver/cpp/examples/channels/CVS/Entries.Extra.Old --cached
    git rm   wcserver/cpp/examples/channels/CVS/Entries.Old --cached
    git rm   wcserver/cpp/examples/channels/CVS/Repository --cached
    git rm   wcserver/cpp/examples/channels/CVS/Root --cached
    git rm   wcserver/cpp/examples/channels/helper-functions.inc --cached
    git rm   wcserver/cpp/examples/door32/CVS/Entries --cached
    git rm   wcserver/cpp/examples/door32/CVS/Entries.Extra --cached
    git rm   wcserver/cpp/examples/door32/CVS/Entries.Extra.Old --cached
    git rm   wcserver/cpp/examples/door32/CVS/Entries.Old --cached
    git rm   wcserver/cpp/examples/door32/CVS/Repository --cached
    git rm   wcserver/cpp/examples/door32/CVS/Root --cached
    git rm   wcserver/cpp/examples/door32/domake.cmd --cached
    git rm   wcserver/cpp/examples/door32/makefile --cached
    git rm   wcserver/cpp/examples/wcFrontEnd/CVS/Entries --cached
    git rm   wcserver/cpp/examples/wcFrontEnd/CVS/Entries.Extra --cached
    git rm   wcserver/cpp/examples/wcFrontEnd/CVS/Entries.Extra.Old --cached
    git rm   wcserver/cpp/examples/wcFrontEnd/CVS/Entries.Old --cached
    git rm   wcserver/cpp/examples/wcFrontEnd/CVS/Repository --cached
    git rm   wcserver/cpp/examples/wcFrontEnd/CVS/Root --cached
    git rm   wcserver/cpp/examples/wcOnlineHost/CVS/Entries --cached
    git rm   wcserver/cpp/examples/wcOnlineHost/CVS/Entries.Extra --cached
    git rm   wcserver/cpp/examples/wcOnlineHost/CVS/Entries.Extra.Old --cached
    git rm   wcserver/cpp/examples/wcOnlineHost/CVS/Entries.Old --cached
    git rm   wcserver/cpp/examples/wcOnlineHost/CVS/Repository --cached
    git rm   wcserver/cpp/examples/wcOnlineHost/CVS/Root --cached
    git rm   wcserver/cpp/examples/wconlineStats/CVS/Entries --cached
    git rm   wcserver/cpp/examples/wconlineStats/CVS/Entries.Extra --cached
    git rm   wcserver/cpp/examples/wconlineStats/CVS/Entries.Extra.Old --cached
    git rm   wcserver/cpp/examples/wconlineStats/CVS/Entries.Old --cached
    git rm   wcserver/cpp/examples/wconlineStats/CVS/Repository --cached
    git rm   wcserver/cpp/examples/wconlineStats/CVS/Root --cached
    git rm   wcserver/cpp/include/CVS/Entries --cached
    git rm   wcserver/cpp/include/CVS/Entries.Extra --cached
    git rm   wcserver/cpp/include/CVS/Entries.Extra.Old --cached
    git rm   wcserver/cpp/include/CVS/Entries.Old --cached
    git rm   wcserver/cpp/include/CVS/Repository --cached
    git rm   wcserver/cpp/include/CVS/Root --cached
    git rm   wcserver/cpp/lib/CVS/Entries --cached
    git rm   wcserver/cpp/lib/CVS/Entries.Extra --cached
    git rm   wcserver/cpp/lib/CVS/Entries.Extra.Old --cached
    git rm   wcserver/cpp/lib/CVS/Entries.Old --cached
    git rm   wcserver/cpp/lib/CVS/Repository --cached
    git rm   wcserver/cpp/lib/CVS/Root --cached
    git rm   wcserver/cpp/libd/CVS/Entries --cached
    git rm   wcserver/cpp/libd/CVS/Entries.Extra --cached
    git rm   wcserver/cpp/libd/CVS/Entries.Extra.Old --cached
    git rm   wcserver/cpp/libd/CVS/Entries.Old --cached
    git rm   wcserver/cpp/libd/CVS/Repository --cached
    git rm   wcserver/cpp/libd/CVS/Root --cached
    git rm   wcserver/csharp-includes.zip --cached
    git rm   wcserver/delphi/CVS/Entries --cached
    git rm   wcserver/delphi/CVS/Entries.Extra --cached
    git rm   wcserver/delphi/CVS/Entries.Extra.Old --cached
    git rm   wcserver/delphi/CVS/Entries.Old --cached
    git rm   wcserver/delphi/CVS/Repository --cached
    git rm   wcserver/delphi/CVS/Root --cached
    git rm   wcserver/delphi/examples/CVS/Entries --cached
    git rm   wcserver/delphi/examples/CVS/Entries.Extra --cached
    git rm   wcserver/delphi/examples/CVS/Entries.Extra.Old --cached
    git rm   wcserver/delphi/examples/CVS/Entries.Old --cached
    git rm   wcserver/delphi/examples/CVS/Repository --cached
    git rm   wcserver/delphi/examples/CVS/Root --cached
    git rm   wcserver/delphi/examples/TriviaDoor/CVS/Entries --cached
    git rm   wcserver/delphi/examples/TriviaDoor/CVS/Entries.Extra --cached
    git rm   wcserver/delphi/examples/TriviaDoor/CVS/Entries.Extra.Old --cached
    git rm   wcserver/delphi/examples/TriviaDoor/CVS/Entries.Old --cached
    git rm   wcserver/delphi/examples/TriviaDoor/CVS/Repository --cached
    git rm   wcserver/delphi/examples/TriviaDoor/CVS/Root --cached
    git rm   wcserver/delphi/examples/TriviaServer/CVS/Entries --cached
    git rm   wcserver/delphi/examples/TriviaServer/CVS/Entries.Extra --cached
    git rm   wcserver/delphi/examples/TriviaServer/CVS/Entries.Extra.Old --cached
    git rm   wcserver/delphi/examples/TriviaServer/CVS/Entries.Old --cached
    git rm   wcserver/delphi/examples/TriviaServer/CVS/Repository --cached
    git rm   wcserver/delphi/examples/TriviaServer/CVS/Root --cached
    git rm   wcserver/delphi/examples/chatmon/CVS/Entries --cached
    git rm   wcserver/delphi/examples/chatmon/CVS/Entries.Extra --cached
    git rm   wcserver/delphi/examples/chatmon/CVS/Entries.Extra.Old --cached
    git rm   wcserver/delphi/examples/chatmon/CVS/Entries.Old --cached
    git rm   wcserver/delphi/examples/chatmon/CVS/Repository --cached
    git rm   wcserver/delphi/examples/chatmon/CVS/Root --cached
    git rm   wcserver/delphi/examples/door32/CVS/Entries --cached
    git rm   wcserver/delphi/examples/door32/CVS/Entries.Extra --cached
    git rm   wcserver/delphi/examples/door32/CVS/Entries.Extra.Old --cached
    git rm   wcserver/delphi/examples/door32/CVS/Entries.Old --cached
    git rm   wcserver/delphi/examples/door32/CVS/Repository --cached
    git rm   wcserver/delphi/examples/door32/CVS/Root --cached
    git rm   wcserver/delphi/examples/wcYell/CVS/Entries --cached
    git rm   wcserver/delphi/examples/wcYell/CVS/Entries.Extra --cached
    git rm   wcserver/delphi/examples/wcYell/CVS/Entries.Extra.Old --cached
    git rm   wcserver/delphi/examples/wcYell/CVS/Entries.Old --cached
    git rm   wcserver/delphi/examples/wcYell/CVS/Repository --cached
    git rm   wcserver/delphi/examples/wcYell/CVS/Root --cached
    git rm   wcserver/delphi/examples/wcYell/CVS/wcyell.exe,t --cached
    git rm   wcserver/delphi/examples/wcYell/CVS/wcyell.pas,t --cached
    git rm   wcserver/delphi/examples/wcspy/CVS/Entries --cached
    git rm   wcserver/delphi/examples/wcspy/CVS/Entries.Extra --cached
    git rm   wcserver/delphi/examples/wcspy/CVS/Entries.Extra.Old --cached
    git rm   wcserver/delphi/examples/wcspy/CVS/Entries.Old --cached
    git rm   wcserver/delphi/examples/wcspy/CVS/Repository --cached
    git rm   wcserver/delphi/examples/wcspy/CVS/Root --cached
    git rm   wcserver/delphi/examples/wcsrvmon/CVS/Entries --cached
    git rm   wcserver/delphi/examples/wcsrvmon/CVS/Entries.Extra --cached
    git rm   wcserver/delphi/examples/wcsrvmon/CVS/Entries.Extra.Old --cached
    git rm   wcserver/delphi/examples/wcsrvmon/CVS/Entries.Old --cached
    git rm   wcserver/delphi/examples/wcsrvmon/CVS/Repository --cached
    git rm   wcserver/delphi/examples/wcsrvmon/CVS/Root --cached
    git rm   wcserver/delphi/lib/CVS/Entries --cached
    git rm   wcserver/delphi/lib/CVS/Entries.Extra --cached
    git rm   wcserver/delphi/lib/CVS/Entries.Extra.Old --cached
    git rm   wcserver/delphi/lib/CVS/Entries.Old --cached
    git rm   wcserver/delphi/lib/CVS/Repository --cached
    git rm   wcserver/delphi/lib/CVS/Root --cached
    git rm   wcserver/describe --cached
    git rm   wcserver/foo --cached
    git rm   wcserver/java/COM/CVS/Entries --cached
    git rm   wcserver/java/COM/CVS/Entries.Extra --cached
    git rm   wcserver/java/COM/CVS/Entries.Extra.Old --cached
    git rm   wcserver/java/COM/CVS/Entries.Old --cached
    git rm   wcserver/java/COM/CVS/Repository --cached
    git rm   wcserver/java/COM/CVS/Root --cached
    git rm   wcserver/java/COM/winserver/CVS/Entries --cached
    git rm   wcserver/java/COM/winserver/CVS/Entries.Extra --cached
    git rm   wcserver/java/COM/winserver/CVS/Entries.Extra.Old --cached
    git rm   wcserver/java/COM/winserver/CVS/Entries.Old --cached
    git rm   wcserver/java/COM/winserver/CVS/Repository --cached
    git rm   wcserver/java/COM/winserver/CVS/Root --cached
    git rm   wcserver/java/COM/winserver/wcnav/CVS/Entries --cached
    git rm   wcserver/java/COM/winserver/wcnav/CVS/Entries.Extra --cached
    git rm   wcserver/java/COM/winserver/wcnav/CVS/Entries.Extra.Old --cached
    git rm   wcserver/java/COM/winserver/wcnav/CVS/Entries.Old --cached
    git rm   wcserver/java/COM/winserver/wcnav/CVS/Repository --cached
    git rm   wcserver/java/COM/winserver/wcnav/CVS/Root --cached
    git rm   wcserver/java/COM/winserver/wcnav/chat/CVS/Entries --cached
    git rm   wcserver/java/COM/winserver/wcnav/chat/CVS/Entries.Extra --cached
    git rm   wcserver/java/COM/winserver/wcnav/chat/CVS/Entries.Extra.Old --cached
    git rm   wcserver/java/COM/winserver/wcnav/chat/CVS/Entries.Old --cached
    git rm   wcserver/java/COM/winserver/wcnav/chat/CVS/Repository --cached
    git rm   wcserver/java/COM/winserver/wcnav/chat/CVS/Root --cached
    git rm   wcserver/java/COM/winserver/wcnav/who/CVS/Entries --cached
    git rm   wcserver/java/COM/winserver/wcnav/who/CVS/Entries.Extra --cached
    git rm   wcserver/java/COM/winserver/wcnav/who/CVS/Entries.Extra.Old --cached
    git rm   wcserver/java/COM/winserver/wcnav/who/CVS/Entries.Old --cached
    git rm   wcserver/java/COM/winserver/wcnav/who/CVS/Repository --cached
    git rm   wcserver/java/COM/winserver/wcnav/who/CVS/Root --cached
    git rm   wcserver/java/COM/winserver/wcnav/wildsock/CVS/Entries --cached
    git rm   wcserver/java/COM/winserver/wcnav/wildsock/CVS/Entries.Extra --cached
    git rm   wcserver/java/COM/winserver/wcnav/wildsock/CVS/Entries.Extra.Old --cached
    git rm   wcserver/java/COM/winserver/wcnav/wildsock/CVS/Entries.Old --cached
    git rm   wcserver/java/COM/winserver/wcnav/wildsock/CVS/Repository --cached
    git rm   wcserver/java/COM/winserver/wcnav/wildsock/CVS/Root --cached
    git rm   wcserver/java/COM/winserver/wildcat/CVS/Entries --cached
    git rm   wcserver/java/COM/winserver/wildcat/CVS/Entries.Extra --cached
    git rm   wcserver/java/COM/winserver/wildcat/CVS/Entries.Extra.Old --cached
    git rm   wcserver/java/COM/winserver/wildcat/CVS/Entries.Old --cached
    git rm   wcserver/java/COM/winserver/wildcat/CVS/Repository --cached
    git rm   wcserver/java/COM/winserver/wildcat/CVS/Root --cached
    git rm   wcserver/java/CVS/Entries --cached
    git rm   wcserver/java/CVS/Entries.Extra --cached
    git rm   wcserver/java/CVS/Entries.Extra.Old --cached
    git rm   wcserver/java/CVS/Entries.Old --cached
    git rm   wcserver/java/CVS/Repository --cached
    git rm   wcserver/java/CVS/Root --cached
    git rm   wcserver/java/classes/CVS/Entries --cached
    git rm   wcserver/java/classes/CVS/Entries.Extra --cached
    git rm   wcserver/java/classes/CVS/Entries.Extra.Old --cached
    git rm   wcserver/java/classes/CVS/Entries.Old --cached
    git rm   wcserver/java/classes/CVS/Repository --cached
    git rm   wcserver/java/classes/CVS/Root --cached
    git rm   wcserver/java/examples/CVS/Entries --cached
    git rm   wcserver/java/examples/CVS/Entries.Extra --cached
    git rm   wcserver/java/examples/CVS/Entries.Extra.Old --cached
    git rm   wcserver/java/examples/CVS/Entries.Old --cached
    git rm   wcserver/java/examples/CVS/Repository --cached
    git rm   wcserver/java/examples/CVS/Root --cached
    git rm   wcserver/java/examples/wcJavaChat/CVS/Entries --cached
    git rm   wcserver/java/examples/wcJavaChat/CVS/Entries.Extra --cached
    git rm   wcserver/java/examples/wcJavaChat/CVS/Entries.Extra.Old --cached
    git rm   wcserver/java/examples/wcJavaChat/CVS/Entries.Old --cached
    git rm   wcserver/java/examples/wcJavaChat/CVS/Repository --cached
    git rm   wcserver/java/examples/wcJavaChat/CVS/Root --cached
    git rm   wcserver/java/examples/wcJavaChat/com/CVS/Entries --cached
    git rm   wcserver/java/examples/wcJavaChat/com/CVS/Entries.Extra --cached
    git rm   wcserver/java/examples/wcJavaChat/com/CVS/Entries.Extra.Old --cached
    git rm   wcserver/java/examples/wcJavaChat/com/CVS/Entries.Old --cached
    git rm   wcserver/java/examples/wcJavaChat/com/CVS/Repository --cached
    git rm   wcserver/java/examples/wcJavaChat/com/CVS/Root --cached
    git rm   wcserver/java/examples/wcJavaChat/com/winserver/CVS/Entries --cached
    git rm   wcserver/java/examples/wcJavaChat/com/winserver/CVS/Entries.Extra --cached
    git rm   wcserver/java/examples/wcJavaChat/com/winserver/CVS/Entries.Extra.Old --cached
    git rm   wcserver/java/examples/wcJavaChat/com/winserver/CVS/Entries.Old --cached
    git rm   wcserver/java/examples/wcJavaChat/com/winserver/CVS/Repository --cached
    git rm   wcserver/java/examples/wcJavaChat/com/winserver/CVS/Root --cached
    git rm   wcserver/java/examples/wcJavaChat/com/winserver/wcnav/CVS/Entries --cached
    git rm   wcserver/java/examples/wcJavaChat/com/winserver/wcnav/CVS/Entries.Extra --cached
    git rm   wcserver/java/examples/wcJavaChat/com/winserver/wcnav/CVS/Entries.Extra.Old --cached
    git rm   wcserver/java/examples/wcJavaChat/com/winserver/wcnav/CVS/Entries.Old --cached
    git rm   wcserver/java/examples/wcJavaChat/com/winserver/wcnav/CVS/Repository --cached
    git rm   wcserver/java/examples/wcJavaChat/com/winserver/wcnav/CVS/Root --cached
    git rm   wcserver/java/examples/wcJavaChat/com/winserver/wcnav/chat/CVS/Entries --cached
    git rm   wcserver/java/examples/wcJavaChat/com/winserver/wcnav/chat/CVS/Entries.Extra --cached
    git rm   wcserver/java/examples/wcJavaChat/com/winserver/wcnav/chat/CVS/Entries.Extra.Old --cached
    git rm   wcserver/java/examples/wcJavaChat/com/winserver/wcnav/chat/CVS/Entries.Old --cached
    git rm   wcserver/java/examples/wcJavaChat/com/winserver/wcnav/chat/CVS/Repository --cached
    git rm   wcserver/java/examples/wcJavaChat/com/winserver/wcnav/chat/CVS/Root --cached
    git rm   wcserver/java/examples/wcJavaChat/com/winserver/wcnav/who/CVS/Entries --cached
    git rm   wcserver/java/examples/wcJavaChat/com/winserver/wcnav/who/CVS/Entries.Extra --cached
    git rm   wcserver/java/examples/wcJavaChat/com/winserver/wcnav/who/CVS/Entries.Extra.Old --cached
    git rm   wcserver/java/examples/wcJavaChat/com/winserver/wcnav/who/CVS/Entries.Old --cached
    git rm   wcserver/java/examples/wcJavaChat/com/winserver/wcnav/who/CVS/Repository --cached
    git rm   wcserver/java/examples/wcJavaChat/com/winserver/wcnav/who/CVS/Root --cached
    git rm   wcserver/java/examples/wcJavaChat/com/winserver/wcnav/wildsock/CVS/Entries --cached
    git rm   wcserver/java/examples/wcJavaChat/com/winserver/wcnav/wildsock/CVS/Entries.Extra --cached
    git rm   wcserver/java/examples/wcJavaChat/com/winserver/wcnav/wildsock/CVS/Entries.Extra.Old --cached
    git rm   wcserver/java/examples/wcJavaChat/com/winserver/wcnav/wildsock/CVS/Entries.Old --cached
    git rm   wcserver/java/examples/wcJavaChat/com/winserver/wcnav/wildsock/CVS/Repository --cached
    git rm   wcserver/java/examples/wcJavaChat/com/winserver/wcnav/wildsock/CVS/Root --cached
    git rm   wcserver/java/examples/wcJavaChat/com/winserver/wildcat/CVS/Entries --cached
    git rm   wcserver/java/examples/wcJavaChat/com/winserver/wildcat/CVS/Entries.Extra --cached
    git rm   wcserver/java/examples/wcJavaChat/com/winserver/wildcat/CVS/Entries.Extra.Old --cached
    git rm   wcserver/java/examples/wcJavaChat/com/winserver/wildcat/CVS/Entries.Old --cached
    git rm   wcserver/java/examples/wcJavaChat/com/winserver/wildcat/CVS/Repository --cached
    git rm   wcserver/java/examples/wcJavaChat/com/winserver/wildcat/CVS/Root --cached
    git rm   wcserver/php-temp.zip --cached
    git rm   wcserver/php/CVS/Entries --cached
    git rm   wcserver/php/CVS/Entries.Extra --cached
    git rm   wcserver/php/CVS/Entries.Extra.Old --cached
    git rm   wcserver/php/CVS/Entries.Old --cached
    git rm   wcserver/php/CVS/Repository --cached
    git rm   wcserver/php/CVS/Root --cached
    git rm   wcserver/php/code/CVS/Entries --cached
    git rm   wcserver/php/code/CVS/Entries.Extra --cached
    git rm   wcserver/php/code/CVS/Entries.Extra.Old --cached
    git rm   wcserver/php/code/CVS/Entries.Old --cached
    git rm   wcserver/php/code/CVS/Repository --cached
    git rm   wcserver/php/code/CVS/Root --cached
    git rm   wcserver/php/code/CVS/arraylib.php,t --cached
    git rm   wcserver/php/code/CVS/getparam.inc.php,t --cached
    git rm   wcserver/php/code/CVS/inilib.inc.php,t --cached
    git rm   wcserver/php/code/CVS/strlib.inc.php,t --cached
    git rm   wcserver/php/code/CVS/testpwe.php,t --cached
    git rm   wcserver/php/code/CVS/wcShareNet.class.php,t --cached
    git rm   wcserver/php/code/CVS/wildcat.console.inc.php,t --cached
    git rm   wcserver/php/code/CVS/wildcat.door32.class.php,t --cached
    git rm   wcserver/php/code/CVS/wildcat.event.class.php,t --cached
    git rm   wcserver/php/code/CVS/wildcat.filetime.inc.php,t --cached
    git rm   wcserver/php/code/CVS/wildcat.mail.class.php,t --cached
    git rm   wcserver/php/code/CVS/wildcat.mailthreads.class.php,t --cached
    git rm   wcserver/php/code/CVS/wildcat.php,t --cached
    git rm   wcserver/php/code/CVS/wildcat.timer.class.php,t --cached
    git rm   wcserver/php/code/CVS/wildcat.topics.class.php,t --cached
    git rm   wcserver/php/code/CVS/wildcat.user.class.php,t --cached
    git rm   wcserver/php/code/CVS/wildcat.username.class.php,t --cached
    git rm   wcserver/php/examples/CVS/Entries --cached
    git rm   wcserver/php/examples/CVS/Entries.Extra --cached
    git rm   wcserver/php/examples/CVS/Entries.Extra.Old --cached
    git rm   wcserver/php/examples/CVS/Entries.Old --cached
    git rm   wcserver/php/examples/CVS/Repository --cached
    git rm   wcserver/php/examples/CVS/Root --cached
    git rm   wcserver/php/pwe/504/CVS/Entries --cached
    git rm   wcserver/php/pwe/504/CVS/Entries.Extra --cached
    git rm   wcserver/php/pwe/504/CVS/Entries.Extra.Old --cached
    git rm   wcserver/php/pwe/504/CVS/Entries.Old --cached
    git rm   wcserver/php/pwe/504/CVS/Repository --cached
    git rm   wcserver/php/pwe/504/CVS/Root --cached
    git rm   wcserver/php/pwe/504/CVS/php_wcsgate.dll,t --cached
    git rm   wcserver/php/pwe/504/CVS/php_wcsmw.dll,t --cached
    git rm   wcserver/php/pwe/504/CVS/php_wildcat.dll,t --cached
    git rm   wcserver/php/pwe/510/CVS/Entries --cached
    git rm   wcserver/php/pwe/510/CVS/Entries.Extra --cached
    git rm   wcserver/php/pwe/510/CVS/Entries.Extra.Old --cached
    git rm   wcserver/php/pwe/510/CVS/Entries.Old --cached
    git rm   wcserver/php/pwe/510/CVS/Repository --cached
    git rm   wcserver/php/pwe/510/CVS/Root --cached
    git rm   wcserver/php/pwe/510/CVS/php_wcsgate.dll,t --cached
    git rm   wcserver/php/pwe/510/CVS/php_wcsmw.dll,t --cached
    git rm   wcserver/php/pwe/510/CVS/php_wildcat.dll,t --cached
    git rm   wcserver/php/pwe/512/CVS/Entries --cached
    git rm   wcserver/php/pwe/512/CVS/Entries.Extra --cached
    git rm   wcserver/php/pwe/512/CVS/Entries.Extra.Old --cached
    git rm   wcserver/php/pwe/512/CVS/Entries.Old --cached
    git rm   wcserver/php/pwe/512/CVS/Repository --cached
    git rm   wcserver/php/pwe/512/CVS/Root --cached
    git rm   wcserver/php/pwe/512/CVS/php_wcsgate.dll,t --cached
    git rm   wcserver/php/pwe/512/CVS/php_wcsmw.dll,t --cached
    git rm   wcserver/php/pwe/512/CVS/php_wildcat.dll,t --cached
    git rm   wcserver/php/pwe/525/CVS/Entries --cached
    git rm   wcserver/php/pwe/525/CVS/Entries.Extra --cached
    git rm   wcserver/php/pwe/525/CVS/Entries.Extra.Old --cached
    git rm   wcserver/php/pwe/525/CVS/Entries.Old --cached
    git rm   wcserver/php/pwe/525/CVS/Repository --cached
    git rm   wcserver/php/pwe/525/CVS/Root --cached
    git rm   wcserver/php/pwe/525/CVS/php_wcsgate.dll,t --cached
    git rm   wcserver/php/pwe/525/CVS/php_wcsmw.dll,t --cached
    git rm   wcserver/php/pwe/525/CVS/php_wildcat.dll,t --cached
    git rm   wcserver/php/pwe/526/CVS/Entries --cached
    git rm   wcserver/php/pwe/526/CVS/Entries.Extra --cached
    git rm   wcserver/php/pwe/526/CVS/Entries.Extra.Old --cached
    git rm   wcserver/php/pwe/526/CVS/Entries.Old --cached
    git rm   wcserver/php/pwe/526/CVS/Repository --cached
    git rm   wcserver/php/pwe/526/CVS/Root --cached
    git rm   wcserver/php/pwe/526/CVS/php_wcsgate.dll,t --cached
    git rm   wcserver/php/pwe/526/CVS/php_wcsmw.dll,t --cached
    git rm   wcserver/php/pwe/526/CVS/php_wildcat.dll,t --cached
    git rm   wcserver/php/pwe/530/CVS/Entries --cached
    git rm   wcserver/php/pwe/530/CVS/Entries.Extra --cached
    git rm   wcserver/php/pwe/530/CVS/Entries.Extra.Old --cached
    git rm   wcserver/php/pwe/530/CVS/Entries.Old --cached
    git rm   wcserver/php/pwe/530/CVS/Repository --cached
    git rm   wcserver/php/pwe/530/CVS/Root --cached
    git rm   wcserver/php/pwe/530/CVS/php_wcsgate.dll,t --cached
    git rm   wcserver/php/pwe/530/CVS/php_wcsmw.dll,t --cached
    git rm   wcserver/php/pwe/530/CVS/php_wildcat.dll,t --cached
    git rm   wcserver/php/pwe/706/CVS/Entries --cached
    git rm   wcserver/php/pwe/706/CVS/Entries.Extra --cached
    git rm   wcserver/php/pwe/706/CVS/Entries.Extra.Old --cached
    git rm   wcserver/php/pwe/706/CVS/Entries.Old --cached
    git rm   wcserver/php/pwe/706/CVS/Repository --cached
    git rm   wcserver/php/pwe/706/CVS/Root --cached
    git rm   wcserver/php/pwe/706/CVS/php_wcsgate.dll,t --cached
    git rm   wcserver/php/pwe/706/CVS/php_wcsmw.dll,t --cached
    git rm   wcserver/php/pwe/706/CVS/php_wildcat.dll,t --cached
    git rm   wcserver/php/pwe/CVS/Entries --cached
    git rm   wcserver/php/pwe/CVS/Entries.Extra --cached
    git rm   wcserver/php/pwe/CVS/Entries.Extra.Old --cached
    git rm   wcserver/php/pwe/CVS/Entries.Old --cached
    git rm   wcserver/php/pwe/CVS/Repository --cached
    git rm   wcserver/php/pwe/CVS/Root --cached
    git rm   wcserver/php/pwe/CVS/php_wcsgate.dll,t --cached
    git rm   wcserver/php/pwe/CVS/php_wcsmw.dll,t --cached
    git rm   wcserver/php/pwe/CVS/php_wildcat.dll,t --cached
    git rm   wcserver/php_orig/CVS/Entries --cached
    git rm   wcserver/php_orig/CVS/Entries.Extra --cached
    git rm   wcserver/php_orig/CVS/Entries.Extra.Old --cached
    git rm   wcserver/php_orig/CVS/Entries.Old --cached
    git rm   wcserver/php_orig/CVS/Repository --cached
    git rm   wcserver/php_orig/CVS/Root --cached
    git rm   wcserver/php_orig/examples/CVS/Entries --cached
    git rm   wcserver/php_orig/examples/CVS/Entries.Extra --cached
    git rm   wcserver/php_orig/examples/CVS/Entries.Extra.Old --cached
    git rm   wcserver/php_orig/examples/CVS/Entries.Old --cached
    git rm   wcserver/php_orig/examples/CVS/Repository --cached
    git rm   wcserver/php_orig/examples/CVS/Root --cached
    git rm   wcserver/php_orig/examples/TriviaDoor/CVS/Entries --cached
    git rm   wcserver/php_orig/examples/TriviaDoor/CVS/Entries.Extra --cached
    git rm   wcserver/php_orig/examples/TriviaDoor/CVS/Entries.Extra.Old --cached
    git rm   wcserver/php_orig/examples/TriviaDoor/CVS/Entries.Old --cached
    git rm   wcserver/php_orig/examples/TriviaDoor/CVS/Repository --cached
    git rm   wcserver/php_orig/examples/TriviaDoor/CVS/Root --cached
    git rm   wcserver/php_orig/examples/TriviaDoor/pwe_door_trivia.php --cached
    git rm   wcserver/php_orig/examples/TriviaDoor/pwe_door_trivia_ob.php --cached
    git rm   wcserver/php_orig/examples/door32/CVS/Entries --cached
    git rm   wcserver/php_orig/examples/door32/CVS/Entries.Extra --cached
    git rm   wcserver/php_orig/examples/door32/CVS/Entries.Extra.Old --cached
    git rm   wcserver/php_orig/examples/door32/CVS/Entries.Old --cached
    git rm   wcserver/php_orig/examples/door32/CVS/Repository --cached
    git rm   wcserver/php_orig/examples/door32/CVS/Root --cached
    git rm   wcserver/php_orig/examples/door32/pwe_door_example1.php --cached
    git rm   wcserver/php_orig/examples/door32/pwe_door_example2.php --cached
    git rm   wcserver/php_orig/examples/door32/pwe_door_example3.php --cached
    git rm   wcserver/php_orig/examples/door32/pwe_door_example4.php --cached
    git rm   wcserver/php_orig/examples/door32/pwe_door_example5.php --cached
    git rm   wcserver/php_orig/examples/door32/pwe_door_example6.php --cached
    git rm   wcserver/php_orig/examples/door32/pwe_door_example7.php --cached
    git rm   wcserver/php_orig/examples/door32/pwe_obdoor_example1.php --cached
    git rm   wcserver/php_orig/examples/door32/pwe_obdoor_example2.php --cached
    git rm   wcserver/php_orig/include/CVS/Entries --cached
    git rm   wcserver/php_orig/include/CVS/Entries.Extra --cached
    git rm   wcserver/php_orig/include/CVS/Entries.Extra.Old --cached
    git rm   wcserver/php_orig/include/CVS/Entries.Old --cached
    git rm   wcserver/php_orig/include/CVS/Repository --cached
    git rm   wcserver/php_orig/include/CVS/Root --cached
    git rm   wcserver/php_orig/src/CVS/Entries --cached
    git rm   wcserver/php_orig/src/CVS/Entries.Extra --cached
    git rm   wcserver/php_orig/src/CVS/Entries.Extra.Old --cached
    git rm   wcserver/php_orig/src/CVS/Entries.Old --cached
    git rm   wcserver/php_orig/src/CVS/Repository --cached
    git rm   wcserver/php_orig/src/CVS/Root --cached
    git rm   wcserver/question1-msdn.txt --cached
    git rm   wcserver/vb.net/CVS/Entries --cached
    git rm   wcserver/vb.net/CVS/Entries.Extra --cached
    git rm   wcserver/vb.net/CVS/Entries.Extra.Old --cached
    git rm   wcserver/vb.net/CVS/Entries.Old --cached
    git rm   wcserver/vb.net/CVS/Repository --cached
    git rm   wcserver/vb.net/CVS/Root --cached
    git rm   wcserver/vb.net/examples/BSMiniRPT.NET/CVS/Entries --cached
    git rm   wcserver/vb.net/examples/BSMiniRPT.NET/CVS/Entries.Extra --cached
    git rm   wcserver/vb.net/examples/BSMiniRPT.NET/CVS/Entries.Extra.Old --cached
    git rm   wcserver/vb.net/examples/BSMiniRPT.NET/CVS/Entries.Old --cached
    git rm   wcserver/vb.net/examples/BSMiniRPT.NET/CVS/Repository --cached
    git rm   wcserver/vb.net/examples/BSMiniRPT.NET/CVS/Root --cached
    git rm   wcserver/vb.net/examples/BSMiniRPT.NET/My Project/CVS/Entries --cached
    git rm   wcserver/vb.net/examples/BSMiniRPT.NET/My Project/CVS/Entries.Extra --cached
    git rm   wcserver/vb.net/examples/BSMiniRPT.NET/My Project/CVS/Entries.Extra.Old --cached
    git rm   wcserver/vb.net/examples/BSMiniRPT.NET/My Project/CVS/Entries.Old --cached
    git rm   wcserver/vb.net/examples/BSMiniRPT.NET/My Project/CVS/Repository --cached
    git rm   wcserver/vb.net/examples/BSMiniRPT.NET/My Project/CVS/Root --cached
    git rm   wcserver/vb.net/examples/CVS/Entries --cached
    git rm   wcserver/vb.net/examples/CVS/Entries.Extra --cached
    git rm   wcserver/vb.net/examples/CVS/Entries.Extra.Old --cached
    git rm   wcserver/vb.net/examples/CVS/Entries.Old --cached
    git rm   wcserver/vb.net/examples/CVS/Repository --cached
    git rm   wcserver/vb.net/examples/CVS/Root --cached
    git rm   wcserver/vb.net/examples/Project1.NET/CVS/Entries --cached
    git rm   wcserver/vb.net/examples/Project1.NET/CVS/Entries.Extra --cached
    git rm   wcserver/vb.net/examples/Project1.NET/CVS/Entries.Extra.Old --cached
    git rm   wcserver/vb.net/examples/Project1.NET/CVS/Entries.Old --cached
    git rm   wcserver/vb.net/examples/Project1.NET/CVS/Repository --cached
    git rm   wcserver/vb.net/examples/Project1.NET/CVS/Root --cached
    git rm   wcserver/vb.net/examples/Project1.NET/My Project/CVS/Entries --cached
    git rm   wcserver/vb.net/examples/Project1.NET/My Project/CVS/Entries.Extra --cached
    git rm   wcserver/vb.net/examples/Project1.NET/My Project/CVS/Entries.Extra.Old --cached
    git rm   wcserver/vb.net/examples/Project1.NET/My Project/CVS/Entries.Old --cached
    git rm   wcserver/vb.net/examples/Project1.NET/My Project/CVS/Repository --cached
    git rm   wcserver/vb.net/examples/Project1.NET/My Project/CVS/Root --cached
    git rm   wcserver/vb.net/examples/wcChat.net/CVS/Entries --cached
    git rm   wcserver/vb.net/examples/wcChat.net/CVS/Entries.Extra --cached
    git rm   wcserver/vb.net/examples/wcChat.net/CVS/Entries.Extra.Old --cached
    git rm   wcserver/vb.net/examples/wcChat.net/CVS/Entries.Old --cached
    git rm   wcserver/vb.net/examples/wcChat.net/CVS/Repository --cached
    git rm   wcserver/vb.net/examples/wcChat.net/CVS/Root --cached
    git rm   wcserver/vb.net/examples/wcChat.net/My Project/CVS/Entries --cached
    git rm   wcserver/vb.net/examples/wcChat.net/My Project/CVS/Entries.Extra --cached
    git rm   wcserver/vb.net/examples/wcChat.net/My Project/CVS/Entries.Extra.Old --cached
    git rm   wcserver/vb.net/examples/wcChat.net/My Project/CVS/Entries.Old --cached
    git rm   wcserver/vb.net/examples/wcChat.net/My Project/CVS/Repository --cached
    git rm   wcserver/vb.net/examples/wcChat.net/My Project/CVS/Root --cached
    git rm   wcserver/vb.net/examples/wcChat.net/Resources/CVS/Entries --cached
    git rm   wcserver/vb.net/examples/wcChat.net/Resources/CVS/Entries.Extra --cached
    git rm   wcserver/vb.net/examples/wcChat.net/Resources/CVS/Entries.Extra.Old --cached
    git rm   wcserver/vb.net/examples/wcChat.net/Resources/CVS/Entries.Old --cached
    git rm   wcserver/vb.net/examples/wcChat.net/Resources/CVS/Repository --cached
    git rm   wcserver/vb.net/examples/wcChat.net/Resources/CVS/Root --cached
    git rm   wcserver/vb.net/modules/CVS/Entries --cached
    git rm   wcserver/vb.net/modules/CVS/Entries.Extra --cached
    git rm   wcserver/vb.net/modules/CVS/Entries.Extra.Old --cached
    git rm   wcserver/vb.net/modules/CVS/Entries.Old --cached
    git rm   wcserver/vb.net/modules/CVS/Repository --cached
    git rm   wcserver/vb.net/modules/CVS/Root --cached
    git rm   wcserver/vb/CVS/Entries --cached
    git rm   wcserver/vb/CVS/Entries.Extra --cached
    git rm   wcserver/vb/CVS/Entries.Extra.Old --cached
    git rm   wcserver/vb/CVS/Entries.Old --cached
    git rm   wcserver/vb/CVS/Repository --cached
    git rm   wcserver/vb/CVS/Root --cached
    git rm   wcserver/vb/examples/CVS/Entries --cached
    git rm   wcserver/vb/examples/CVS/Entries.Extra --cached
    git rm   wcserver/vb/examples/CVS/Entries.Extra.Old --cached
    git rm   wcserver/vb/examples/CVS/Entries.Old --cached
    git rm   wcserver/vb/examples/CVS/Repository --cached
    git rm   wcserver/vb/examples/CVS/Root --cached
    git rm   wcserver/vb/examples/ConfigSession/CVS/Entries --cached
    git rm   wcserver/vb/examples/ConfigSession/CVS/Entries.Extra --cached
    git rm   wcserver/vb/examples/ConfigSession/CVS/Entries.Extra.Old --cached
    git rm   wcserver/vb/examples/ConfigSession/CVS/Entries.Old --cached
    git rm   wcserver/vb/examples/ConfigSession/CVS/Repository --cached
    git rm   wcserver/vb/examples/ConfigSession/CVS/Root --cached
    git rm   wcserver/vb/examples/WildcatExample1/CVS/Entries --cached
    git rm   wcserver/vb/examples/WildcatExample1/CVS/Entries.Extra --cached
    git rm   wcserver/vb/examples/WildcatExample1/CVS/Entries.Extra.Old --cached
    git rm   wcserver/vb/examples/WildcatExample1/CVS/Entries.Old --cached
    git rm   wcserver/vb/examples/WildcatExample1/CVS/Repository --cached
    git rm   wcserver/vb/examples/WildcatExample1/CVS/Root --cached
    git rm   wcserver/vb/examples/WildcatSession/CVS/Entries --cached
    git rm   wcserver/vb/examples/WildcatSession/CVS/Entries.Extra --cached
    git rm   wcserver/vb/examples/WildcatSession/CVS/Entries.Extra.Old --cached
    git rm   wcserver/vb/examples/WildcatSession/CVS/Entries.Old --cached
    git rm   wcserver/vb/examples/WildcatSession/CVS/Repository --cached
    git rm   wcserver/vb/examples/WildcatSession/CVS/Root --cached
    git rm   wcserver/vb/examples/wccCompiler-vb98/CVS/Entries --cached
    git rm   wcserver/vb/examples/wccCompiler-vb98/CVS/Entries.Extra --cached
    git rm   wcserver/vb/examples/wccCompiler-vb98/CVS/Entries.Extra.Old --cached
    git rm   wcserver/vb/examples/wccCompiler-vb98/CVS/Entries.Old --cached
    git rm   wcserver/vb/examples/wccCompiler-vb98/CVS/Repository --cached
    git rm   wcserver/vb/examples/wccCompiler-vb98/CVS/Root --cached
    git rm   wcserver/vb/examples/wccCompiler-vs/CVS/Entries --cached
    git rm   wcserver/vb/examples/wccCompiler-vs/CVS/Entries.Extra --cached
    git rm   wcserver/vb/examples/wccCompiler-vs/CVS/Entries.Extra.Old --cached
    git rm   wcserver/vb/examples/wccCompiler-vs/CVS/Entries.Old --cached
    git rm   wcserver/vb/examples/wccCompiler-vs/CVS/Repository --cached
    git rm   wcserver/vb/examples/wccCompiler-vs/CVS/Root --cached
    git rm   wcserver/vb/examples/wccCompiler-vs/Project1.NET/CVS/Entries --cached
    git rm   wcserver/vb/examples/wccCompiler-vs/Project1.NET/CVS/Entries.Extra --cached
    git rm   wcserver/vb/examples/wccCompiler-vs/Project1.NET/CVS/Entries.Extra.Old --cached
    git rm   wcserver/vb/examples/wccCompiler-vs/Project1.NET/CVS/Entries.Old --cached
    git rm   wcserver/vb/examples/wccCompiler-vs/Project1.NET/CVS/Repository --cached
    git rm   wcserver/vb/examples/wccCompiler-vs/Project1.NET/CVS/Root --cached
    git rm   wcserver/vb/examples/wccCompiler-vs/Project1.NET/My Project/CVS/Entries --cached
    git rm   wcserver/vb/examples/wccCompiler-vs/Project1.NET/My Project/CVS/Entries.Extra --cached
    git rm   wcserver/vb/examples/wccCompiler-vs/Project1.NET/My Project/CVS/Entries.Extra.Old --cached
    git rm   wcserver/vb/examples/wccCompiler-vs/Project1.NET/My Project/CVS/Entries.Old --cached
    git rm   wcserver/vb/examples/wccCompiler-vs/Project1.NET/My Project/CVS/Repository --cached
    git rm   wcserver/vb/examples/wccCompiler-vs/Project1.NET/My Project/CVS/Root --cached
    git rm   wcserver/vb/examples/wccCompiler/CVS/Entries --cached
    git rm   wcserver/vb/examples/wccCompiler/CVS/Entries.Extra --cached
    git rm   wcserver/vb/examples/wccCompiler/CVS/Entries.Extra.Old --cached
    git rm   wcserver/vb/examples/wccCompiler/CVS/Entries.Old --cached
    git rm   wcserver/vb/examples/wccCompiler/CVS/Repository --cached
    git rm   wcserver/vb/examples/wccCompiler/CVS/Root --cached
    git rm   wcserver/vb/examples/wccCompiler/My Project/CVS/Entries --cached
    git rm   wcserver/vb/examples/wccCompiler/My Project/CVS/Entries.Extra --cached
    git rm   wcserver/vb/examples/wccCompiler/My Project/CVS/Entries.Extra.Old --cached
    git rm   wcserver/vb/examples/wccCompiler/My Project/CVS/Entries.Old --cached
    git rm   wcserver/vb/examples/wccCompiler/My Project/CVS/Repository --cached
    git rm   wcserver/vb/examples/wccCompiler/My Project/CVS/Root --cached
    git rm   wcserver/vb/modules/CVS/Entries --cached
    git rm   wcserver/vb/modules/CVS/Entries.Extra --cached
    git rm   wcserver/vb/modules/CVS/Entries.Extra.Old --cached
    git rm   wcserver/vb/modules/CVS/Entries.Old --cached
    git rm   wcserver/vb/modules/CVS/Repository --cached
    git rm   wcserver/vb/modules/CVS/Root --cached
    git rm   wcserver/vfp/CVS/Entries --cached
    git rm   wcserver/vfp/CVS/Entries.Extra --cached
    git rm   wcserver/vfp/CVS/Entries.Extra.Old --cached
    git rm   wcserver/vfp/CVS/Entries.Old --cached
    git rm   wcserver/vfp/CVS/Repository --cached
    git rm   wcserver/vfp/CVS/Root --cached
    git rm   wcserver/vfp/examples/CVS/Entries --cached
    git rm   wcserver/vfp/examples/CVS/Entries.Extra --cached
    git rm   wcserver/vfp/examples/CVS/Entries.Extra.Old --cached
    git rm   wcserver/vfp/examples/CVS/Entries.Old --cached
    git rm   wcserver/vfp/examples/CVS/Repository --cached
    git rm   wcserver/vfp/examples/CVS/Root --cached
    git rm   wcserver/vfp/examples/test1program2.prg --cached
    git rm   wcserver/vfp/examples/test1program3.prg --cached
    git rm   wcserver/vfp/lib/CVS/Entries --cached
    git rm   wcserver/vfp/lib/CVS/Entries.Extra --cached
    git rm   wcserver/vfp/lib/CVS/Entries.Extra.Old --cached
    git rm   wcserver/vfp/lib/CVS/Entries.Old --cached
    git rm   wcserver/vfp/lib/CVS/Repository --cached
    git rm   wcserver/vfp/lib/CVS/Root --cached
    git rm   wcserver/vfp/lib/wcsgate.lib --cached
    git rm   wcserver/vfp/lib/wcsmw.lib --cached
    git rm   wcserver/vfp/lib/wcsrv2.lib --cached
    git rm   wcserver/vfp/lib/wcvfp.lib --cached
    git rm   wcserver/vfp/wcfoxpro.FXP --cached
    git rm   wcserver/vfp/wcfoxpro.prg --cached
    git rm   wcserver/vfp/wcserror.h --cached
    git rm   wcserver/vfp/wcserverapidef.FXP --cached
    git rm   wcserver/vfp/wcserverapidef.prg --cached
    git rm   wcserver/vfp/wctype.h --cached
    git rm   wcserver/vfp/wcvfpdefapi.prg --cached
    git rm   wcserver/vfp/win32apidef.FXP --cached
    git rm   wcserver/vfp/win32apidef.prg --cached
    git rm   wcserver/wcATL/CVS/Entries --cached
    git rm   wcserver/wcATL/CVS/Entries.Extra --cached
    git rm   wcserver/wcATL/CVS/Entries.Extra.Old --cached
    git rm   wcserver/wcATL/CVS/Entries.Old --cached
    git rm   wcserver/wcATL/CVS/Repository --cached
    git rm   wcserver/wcATL/CVS/Root --cached
    git rm   wcserver/wcATL/ConnectServer.cpp --cached
    git rm   wcserver/wcATL/ConnectServer.h --cached
    git rm   wcserver/wcATL/ConnectServer.rgs --cached
    git rm   wcserver/wcATL/StdAfx.cpp --cached
    git rm   wcserver/wcATL/StdAfx.h --cached
    git rm   wcserver/wcATL/WildcatServer.cpp --cached
    git rm   wcserver/wcATL/WildcatServer.h --cached
    git rm   wcserver/wcATL/WildcatServer.rgs --cached
    git rm   wcserver/wcATL/dlldatax.c --cached
    git rm   wcserver/wcATL/dlldatax.h --cached
    git rm   wcserver/wcATL/resource.h --cached
    git rm   wcserver/wcATL/wcATL.cpp --cached
    git rm   wcserver/wcATL/wcATL.def --cached
    git rm   wcserver/wcATL/wcATL.dsp --cached
    git rm   wcserver/wcATL/wcATL.dsw --cached
    git rm   wcserver/wcATL/wcATL.h --cached
    git rm   wcserver/wcATL/wcATL.idl --cached
    git rm   wcserver/wcATL/wcATL.rc --cached
    git rm   wcserver/wcATL/wcATLps.def --cached
    git rm   wcserver/wcATL/wcATLps.mk --cached
    git rm   wcserver/wcBASIC/CVS/Entries --cached
    git rm   wcserver/wcBASIC/CVS/Entries.Extra --cached
    git rm   wcserver/wcBASIC/CVS/Entries.Extra.Old --cached
    git rm   wcserver/wcBASIC/CVS/Entries.Old --cached
    git rm   wcserver/wcBASIC/CVS/Repository --cached
    git rm   wcserver/wcBASIC/CVS/Root --cached
    git rm   wcserver/wcBASIC/Examples/CVS/Entries --cached
    git rm   wcserver/wcBASIC/Examples/CVS/Entries.Extra --cached
    git rm   wcserver/wcBASIC/Examples/CVS/Repository --cached
    git rm   wcserver/wcBASIC/Examples/CVS/Root --cached
    git rm   wcserver/wcBASIC/Examples/Trivia/CVS/Entries --cached
    git rm   wcserver/wcBASIC/Examples/Trivia/CVS/Entries.Extra --cached
    git rm   wcserver/wcBASIC/Examples/Trivia/CVS/Entries.Extra.Old --cached
    git rm   wcserver/wcBASIC/Examples/Trivia/CVS/Entries.Old --cached
    git rm   wcserver/wcBASIC/Examples/Trivia/CVS/Repository --cached
    git rm   wcserver/wcBASIC/Examples/Trivia/CVS/Root --cached
