	git rm "foo" --cached
	git rm "wcserver/c#/examples/BSMiniRPTC#.NET/My Project/CVS/Application.Designer.cs,t" --cached
	git rm "wcserver/c#/examples/BSMiniRPTC#.NET/My Project/CVS/Application.myapp,t" --cached
	git rm "wcserver/c#/examples/BSMiniRPTC#.NET/My Project/CVS/Entries" --cached
	git rm "wcserver/c#/examples/BSMiniRPTC#.NET/My Project/CVS/Entries.Extra" --cached
	git rm "wcserver/c#/examples/BSMiniRPTC#.NET/My Project/CVS/Entries.Extra.Old" --cached
	git rm "wcserver/c#/examples/BSMiniRPTC#.NET/My Project/CVS/Entries.Old" --cached
	git rm "wcserver/c#/examples/BSMiniRPTC#.NET/My Project/CVS/Repository" --cached
	git rm "wcserver/c#/examples/BSMiniRPTC#.NET/My Project/CVS/Root" --cached
	git rm "wcserver/vb.net/examples/BSMiniRPT.NET/My Project/CVS/Entries" --cached
	git rm "wcserver/vb.net/examples/BSMiniRPT.NET/My Project/CVS/Entries.Extra" --cached
	git rm "wcserver/vb.net/examples/BSMiniRPT.NET/My Project/CVS/Entries.Extra.Old" --cached
	git rm "wcserver/vb.net/examples/BSMiniRPT.NET/My Project/CVS/Entries.Old" --cached
	git rm "wcserver/vb.net/examples/BSMiniRPT.NET/My Project/CVS/Repository" --cached
	git rm "wcserver/vb.net/examples/BSMiniRPT.NET/My Project/CVS/Root" --cached
	git rm "wcserver/vb.net/examples/Project1.NET/My Project/CVS/Entries" --cached
	git rm "wcserver/vb.net/examples/Project1.NET/My Project/CVS/Entries.Extra" --cached
	git rm "wcserver/vb.net/examples/Project1.NET/My Project/CVS/Entries.Extra.Old" --cached
	git rm "wcserver/vb.net/examples/Project1.NET/My Project/CVS/Entries.Old" --cached
	git rm "wcserver/vb.net/examples/Project1.NET/My Project/CVS/Repository" --cached
	git rm "wcserver/vb.net/examples/Project1.NET/My Project/CVS/Root" --cached
	git rm "wcserver/vb.net/examples/wcChat.net/My Project/CVS/Entries" --cached
	git rm "wcserver/vb.net/examples/wcChat.net/My Project/CVS/Entries.Extra" --cached
	git rm "wcserver/vb.net/examples/wcChat.net/My Project/CVS/Entries.Extra.Old" --cached
	git rm "wcserver/vb.net/examples/wcChat.net/My Project/CVS/Entries.Old" --cached
	git rm "wcserver/vb.net/examples/wcChat.net/My Project/CVS/Repository" --cached
	git rm "wcserver/vb.net/examples/wcChat.net/My Project/CVS/Root" --cached
	git rm "wcserver/vb/examples/wccCompiler-vs/Project1.NET/My Project/CVS/Entries" --cached
	git rm "wcserver/vb/examples/wccCompiler-vs/Project1.NET/My Project/CVS/Entries.Extra" --cached
	git rm "wcserver/vb/examples/wccCompiler-vs/Project1.NET/My Project/CVS/Entries.Extra.Old" --cached
	git rm "wcserver/vb/examples/wccCompiler-vs/Project1.NET/My Project/CVS/Entries.Old" --cached
	git rm "wcserver/vb/examples/wccCompiler-vs/Project1.NET/My Project/CVS/Repository" --cached
	git rm "wcserver/vb/examples/wccCompiler-vs/Project1.NET/My Project/CVS/Root" --cached
	git rm "wcserver/vb/examples/wccCompiler/My Project/CVS/Entries" --cached
	git rm "wcserver/vb/examples/wccCompiler/My Project/CVS/Entries.Extra" --cached
	git rm "wcserver/vb/examples/wccCompiler/My Project/CVS/Entries.Extra.Old" --cached
	git rm "wcserver/vb/examples/wccCompiler/My Project/CVS/Entries.Old" --cached
	git rm "wcserver/vb/examples/wccCompiler/My Project/CVS/Repository" --cached
	git rm "wcserver/vb/examples/wccCompiler/My Project/CVS/Root" --cached

