// File: TUser.java
// (c) copyright 1999 Santronics Software Inc.
//
//****************************************************
// DO NOT EDIT THIS FILE!!!
// CPP2JAVA GENERATED FROM SOURCE FILE: wctype.h
//****************************************************
//

package COM.winserver.wildcat;

import java.io.IOException;

public class TUser extends WcRecord {
  // Constants
  public static final int ucstNone        = 0;
  public static final int ucstPersonal    = 1;
  public static final int ucstPersonalAll = 2;
  public static final int ucstAll         = 3;
  public static final int ucstMask     = 0x0F;
  public static final int ucfReserved1 = 0x10;
  public static final int ucfReserved2 = 0x20;
  public static final int ucfReserved3 = 0x40;
  public static final int ucfAllAttach = 0x80;
  public static final int SIZE_USER_PHONE = 16;
  public static final int SIZE_USER_ADDRESS = 32;
  public static final int SIZE_USER_STATE = 16;
  public static final int SIZE_USER_ZIP = 12;
  public static final int NUM_USER_SECURITY = 10;
  public static final int sNotDisclosed = 0;
  public static final int sMale = 1;
  public static final int sFemale = 2;
  public static final int ePrompt = 0;
  public static final int eLine = 1;
  public static final int eFullScreen = 2;
  public static final int hlNovice = 0;
  public static final int hlRegular = 1;
  public static final int hlExpert = 2;
  public static final int ttAuto = 0;
  public static final int ttTTY = 1;
  public static final int ttAnsi = 2;
  public static final int fdSingle = 0;
  public static final int fdDouble = 1;
  public static final int fdFull = 2;
  public static final int fdAnsi = 3;
  public static final int mdScroll = 0;
  public static final int mdClear = 1;
  public static final int mdKeepHeader = 2;
  public static final int ptText = 0;
  public static final int ptQwk = 1;

  // Members
  public int Status;
  public TUserInfo Info;
  public String From;
  public String Password;
  public String[] Security;
  public boolean AllowMultipleLogins;
  public String RealName;
  public String PhoneNumber;
  public String Company;
  public String Address1;
  public String Address2;
  public String City;
  public String State;
  public String Zip;
  public String Country;
  public int Sex;
  public int Editor;
  public int HelpLevel;
  public int Protocol;
  public int TerminalType;
  public int FileDisplay;
  public int MsgDisplay;
  public int PacketType;
  public int LinesPerPage;
  public boolean HotKeys;
  public boolean QuoteOnReply;
  public boolean SortedListings;
  public boolean PageAvailable;
  public boolean EraseMorePrompt;
  public String Language;
  public long LastCall;
  public long LastNewFiles;
  public long ExpireDate;
  public long FirstCall;
  public long BirthDate;
  public int Conference;
  public int MsgsWritten;
  public int Uploads;
  public int TotalUploadKbytes;
  public int Downloads;
  public int TotalDownloadKbytes;
  public int DownloadCountToday;
  public int DownloadKbytesToday;
  public int TimesOn;
  public int TimeLeftToday;
  public int MinutesLogged;
  public int SubscriptionBalance;
  public int NetmailBalance;
  public boolean AccountLockedOut;
  public boolean PreserveMimeMessages;
  public boolean ShowEmailHeaders;

  // Total size
  public static final int SIZE = 0+4+TUserInfo.SIZE+32+32+10*24+4+4+4+72+16+32+32+32+32+16+12+32+4+4+4+4+4+4+4+4+4+4+4+4+4+4+4+12+8+8+8+8+8+4+4+4+4+4+4+4+4+4+4+4+4+4+4+4+4+36*1;

  // Constructors
  public TUser()
  {
  }

  public TUser(byte[] x)
  {
    fromByteArray(x);
  }

  // Methods
  protected void writeTo(WcOutputStream out) throws IOException
  {
    super.writeTo(out);
    out.writeInt(Status);
    Info.writeTo(out);
    out.writeString(From, 32);
    out.writeString(Password, 32);
    for (int i = 0; i < 10; i++) {
      if (i < Security.length) {
        out.writeString(Security[i], 24);
      } else {
        out.write(new byte[24]);
      }
    }
    out.write(new byte[4]);
    out.writeBoolean(AllowMultipleLogins);
    out.write(new byte[4]);
    out.writeString(RealName, 72);
    out.writeString(PhoneNumber, 16);
    out.writeString(Company, 32);
    out.writeString(Address1, 32);
    out.writeString(Address2, 32);
    out.writeString(City, 32);
    out.writeString(State, 16);
    out.writeString(Zip, 12);
    out.writeString(Country, 32);
    out.writeInt(Sex);
    out.writeInt(Editor);
    out.writeInt(HelpLevel);
    out.writeInt(Protocol);
    out.writeInt(TerminalType);
    out.writeInt(FileDisplay);
    out.writeInt(MsgDisplay);
    out.writeInt(PacketType);
    out.writeInt(LinesPerPage);
    out.writeBoolean(HotKeys);
    out.writeBoolean(QuoteOnReply);
    out.writeBoolean(SortedListings);
    out.writeBoolean(PageAvailable);
    out.writeBoolean(EraseMorePrompt);
    out.write(new byte[4]);
    out.writeString(Language, 12);
    out.writeLong(LastCall);
    out.writeLong(LastNewFiles);
    out.writeLong(ExpireDate);
    out.writeLong(FirstCall);
    out.writeLong(BirthDate);
    out.writeInt(Conference);
    out.writeInt(MsgsWritten);
    out.writeInt(Uploads);
    out.writeInt(TotalUploadKbytes);
    out.writeInt(Downloads);
    out.writeInt(TotalDownloadKbytes);
    out.writeInt(DownloadCountToday);
    out.writeInt(DownloadKbytesToday);
    out.writeInt(TimesOn);
    out.writeInt(TimeLeftToday);
    out.writeInt(MinutesLogged);
    out.writeInt(SubscriptionBalance);
    out.writeInt(NetmailBalance);
    out.writeBoolean(AccountLockedOut);
    out.writeBoolean(PreserveMimeMessages);
    out.writeBoolean(ShowEmailHeaders);
    out.write(new byte[36*1]);
  }

  protected void readFrom(WcInputStream in) throws IOException
  {
    super.readFrom(in);
    Status = in.readInt();
    Info = new TUserInfo(); Info.readFrom(in);
    From = in.readString(32);
    Password = in.readString(32);
    Security = new String[10];
    for (int i = 0; i < 10; i++) {
      Security[i] = in.readString(24);
    }
    in.skip(4);
    AllowMultipleLogins = in.readBoolean();
    in.skip(4);
    RealName = in.readString(72);
    PhoneNumber = in.readString(16);
    Company = in.readString(32);
    Address1 = in.readString(32);
    Address2 = in.readString(32);
    City = in.readString(32);
    State = in.readString(16);
    Zip = in.readString(12);
    Country = in.readString(32);
    Sex = in.readInt();
    Editor = in.readInt();
    HelpLevel = in.readInt();
    Protocol = in.readInt();
    TerminalType = in.readInt();
    FileDisplay = in.readInt();
    MsgDisplay = in.readInt();
    PacketType = in.readInt();
    LinesPerPage = in.readInt();
    HotKeys = in.readBoolean();
    QuoteOnReply = in.readBoolean();
    SortedListings = in.readBoolean();
    PageAvailable = in.readBoolean();
    EraseMorePrompt = in.readBoolean();
    in.skip(4);
    Language = in.readString(12);
    LastCall = in.readLong();
    LastNewFiles = in.readLong();
    ExpireDate = in.readLong();
    FirstCall = in.readLong();
    BirthDate = in.readLong();
    Conference = in.readInt();
    MsgsWritten = in.readInt();
    Uploads = in.readInt();
    TotalUploadKbytes = in.readInt();
    Downloads = in.readInt();
    TotalDownloadKbytes = in.readInt();
    DownloadCountToday = in.readInt();
    DownloadKbytesToday = in.readInt();
    TimesOn = in.readInt();
    TimeLeftToday = in.readInt();
    MinutesLogged = in.readInt();
    SubscriptionBalance = in.readInt();
    NetmailBalance = in.readInt();
    AccountLockedOut = in.readBoolean();
    PreserveMimeMessages = in.readBoolean();
    ShowEmailHeaders = in.readBoolean();
    in.skip(36*1);
  }
}
