// File: Wildcat.java
// (c) copyright 1999 Santronics Software Inc.
//
//****************************************************
// DO NOT EDIT THIS FILE!!!
// CPP2JAVA GENERATED FROM SOURCE FILE: wctype.h
//****************************************************
//

package COM.winserver.wildcat;

import java.io.IOException;

public class Wildcat {
  public static final int MAX_PATH = 260;
  public static final int WILDCAT_VERSION      = 1;
  public static final int WILDCAT_MKTG_VERSION = 5;
  public static final String WILDCAT_MARKETING_VERSION = "5.0";
  public static final int WILDCAT_COMPONENT_ICP = 0x00000001;
  public static final int SIZE_FILE_NAME            = 16;
  public static final int SIZE_COMPUTER_NAME        = 16;
  public static final int SIZE_CONFERENCE_NAME      = 60;
  public static final int SIZE_CONFERENCEGROUP_NAME = 32;
  public static final int SIZE_DOMAIN_NAME          = 64;
  public static final int SIZE_DOOR_NAME            = 40;
  public static final int SIZE_ENCODED_PASSWORD     = 20;
  public static final int SIZE_EXTENSION            = 4;
  public static final int SIZE_FILEAREA_NAME        = 32;
  public static final int SIZE_FILEGROUP_NAME       = 32;
  public static final int SIZE_LANGUAGE_NAME        = 12;
  public static final int SIZE_MENU_DESCRIPTION     = 40;
  public static final int SIZE_MODEM_NAME           = 32;
  public static final int SIZE_PASSWORD             = 32;
  public static final int SIZE_SECURITY_NAME        = 24;
  public static final int SIZE_SERVICE_NAME         = 64;
  public static final int SIZE_USER_NAME            = 72;
  public static final int MAX_USER_NAME = 28;
  public static final int MASK_OBJECTCLASS            = 0xFF000000;
  public static final int OBJECTCLASS_RIGHTS          = 0x01000000;
  public static final int OBJECTCLASS_CONFERENCE      = 0x02000000;
  public static final int OBJECTCLASS_CONFERENCEGROUP = 0x03000000;
  public static final int OBJECTCLASS_FILEAREA        = 0x04000000;
  public static final int OBJECTCLASS_FILEGROUP       = 0x05000000;
  public static final int OBJECTCLASS_DOOR            = 0x06000000;
  public static final int OBJECTCLASS_MENU            = 0x07000000;
  public static final int OBJECTCLASS_CODE            = 0x08000000;
  public static final int OBJECTCLASS_CLIENT          = 0x09000000;
  public static final int OBJECTCLASS_SAPPHIRE_QUERY  = 0x0a000000;
  public static final int OBJECTCLASS_CHAT_CHANNEL    = 0x0b000000;
  public static final int OBJECTCLASS_RADIUS_CLIENT   = 0x0c000000;
  public static final int OBJECTID_BULLETINS_OPTIONAL          = OBJECTCLASS_RIGHTS + 1;
  public static final int OBJECTID_CHANGE_PHONE                = OBJECTCLASS_RIGHTS + 2;
  public static final int OBJECTID_CHANGE_BIRTHDATE            = OBJECTCLASS_RIGHTS + 4;
  public static final int OBJECTID_QWK_ALLOW_BULLETINS         = OBJECTCLASS_RIGHTS + 5;
  public static final int OBJECTID_QWK_ALLOW_NEWS              = OBJECTCLASS_RIGHTS + 6;
  public static final int OBJECTID_QWK_ALLOW_FILES             = OBJECTCLASS_RIGHTS + 7;
  public static final int OBJECTID_QWK_DETAIL_DOWNLOAD         = OBJECTCLASS_RIGHTS + 8;
  public static final int OBJECTID_QWK_CHECK_DUPES             = OBJECTCLASS_RIGHTS + 9;
  public static final int OBJECTID_QWK_SAVE_PACKETS            = OBJECTCLASS_RIGHTS + 10;
  public static final int OBJECTID_MASTER_SYSOP                = OBJECTCLASS_RIGHTS + 11;
  public static final int OBJECTID_RATIO_ACTION                = OBJECTCLASS_RIGHTS + 12;
  public static final int OBJECTID_ALLOW_FAST_LOGIN            = OBJECTCLASS_RIGHTS + 13;
  public static final int OBJECTID_SHOW_PASSWORD_FILES         = OBJECTCLASS_RIGHTS + 15;
  public static final int OBJECTID_ALLOW_OFFLINE_FILE_REQUESTS = OBJECTCLASS_RIGHTS + 16;
  public static final int OBJECTID_ALLOW_UPLOAD_OVER_TIME      = OBJECTCLASS_RIGHTS + 17;
  public static final int OBJECTID_ALLOW_DOWNLOAD_OVER_TIME    = OBJECTCLASS_RIGHTS + 18;
  public static final int OBJECTID_ALLOW_UPLOADER_MODIFY_FILE  = OBJECTCLASS_RIGHTS + 20;
  public static final int OBJECTID_QWK_NETSTATUS               = OBJECTCLASS_RIGHTS + 26;
  public static final int OBJECTID_SYSOP_READ_PRIVATE_MAIL     = OBJECTCLASS_RIGHTS + 27;
  public static final int OBJECTID_ALLOW_INTERNET_EMAIL        = OBJECTCLASS_RIGHTS + 28;
  public static final int OBJECTID_ALLOW_ANY_TELNET            = OBJECTCLASS_RIGHTS + 29;
  public static final int OBJECTID_ALLOW_ANY_FTP               = OBJECTCLASS_RIGHTS + 30;
  public static final int OBJECTID_ALLOW_HTTP_PROXY            = OBJECTCLASS_RIGHTS + 31;
  public static final int OBJECTID_ALLOW_ALL_IP                = OBJECTCLASS_RIGHTS + 32;
  public static final int OBJECTID_ALLOW_DEFAULT_IP            = OBJECTCLASS_RIGHTS + 33;
  public static final int OBJECTID_ALLOW_PPP                   = OBJECTCLASS_RIGHTS + 34;
  public static final int OBJECTID_IGNORE_TIME_ONLINE          = OBJECTCLASS_RIGHTS + 35;
  public static final int OBJECTID_IGNORE_IDLE_TIME            = OBJECTCLASS_RIGHTS + 36;
  public static final int OBJECTID_ALLOW_SMTP_AUTH			 = OBJECTCLASS_RIGHTS + 37;
  public static final int OBJECTID_PROTOCOL_ACCESS             = OBJECTCLASS_RIGHTS + 0x00010000;
  public static final int OBJECTID_NODE_ACCESS                 = OBJECTCLASS_RIGHTS + 0x00020000;
  public static final int OBJECTFLAGS_CONFERENCE_JOIN  = 0x00000001;
  public static final int OBJECTFLAGS_CONFERENCE_READ  = 0x00000002;
  public static final int OBJECTFLAGS_CONFERENCE_WRITE = 0x00000004;
  public static final int OBJECTFLAGS_CONFERENCE_SYSOP = 0x00000008;
  public static final int OBJECTFLAGS_FILEAREA_LIST     = 0x00000001;
  public static final int OBJECTFLAGS_FILEAREA_DOWNLOAD = 0x00000002;
  public static final int OBJECTFLAGS_FILEAREA_UPLOAD   = 0x00000004;
  public static final int OBJECTFLAGS_FILEAREA_SYSOP    = 0x00000008;
  public static final int MSF_FORWARD = 0x00000001;
  public static final int MSF_FROM    = 0x00000002;
  public static final int MSF_TO      = 0x00000004;
  public static final int MSF_SUBJECT = 0x00000008;
  public static final int MSF_BODY    = 0x00000010;
  public static final int CONNECT_RAW          = 0;
  public static final int CONNECT_TELNET_ASCII = 1;
  public static final int CONNECT_TELNET_7BIT  = 2;
  public static final int CONNECT_TELNET_8BIT  = 3;
  public static final int UserIdKey       = 0;
  public static final int UserNameKey     = 1;
  public static final int UserLastNameKey = 2;
  public static final int UserSecurityKey = 3;
  public static final int FileNameAreaKey = 0;
  public static final int FileAreaNameKey = 1;
  public static final int FileAreaDateKey = 2;
  public static final int FileUploaderKey = 3;
}
