// File: TChannelMessage.java
// (c) copyright 1999 Santronics Software Inc.
//
//****************************************************
// DO NOT EDIT THIS FILE!!!
// CPP2JAVA GENERATED FROM SOURCE FILE: wctype.h
//****************************************************
//

package COM.winserver.wildcat;

import java.io.IOException;

public class TChannelMessage extends WcRecord {
  // Constants
  public static final int CHANNEL_MESSAGE_HEADER_SIZE = 12;
  public static final int MAX_CHANNEL_MESSAGE_SIZE = 500;

  // Members
  public int Channel;
  public int SenderId;
  public int UserData;
  public int DataSize;
  public byte[] Data;

  // Total size
  public static final int SIZE = 0+4+4+2+2+500;

  // Constructors
  public TChannelMessage()
  {
  }

  public TChannelMessage(byte[] x)
  {
    fromByteArray(x);
  }

  // Methods
  protected void writeTo(WcOutputStream out) throws IOException
  {
    super.writeTo(out);
    out.writeInt(Channel);
    out.writeInt(SenderId);
    out.writeShort(UserData);
    out.writeShort(DataSize);
    out.write(Data);
  }

  protected void readFrom(WcInputStream in) throws IOException
  {
    super.readFrom(in);
    Channel = in.readInt();
    SenderId = in.readInt();
    UserData = in.readUnsignedShort();
    DataSize = in.readUnsignedShort();
    Data = new byte[500]; in.read(Data);
  }
}
