// File: TGetCurrentUser_Response.java
// (c) copyright 1999 Santronics Software Inc.
//
//****************************************************
// DO NOT EDIT THIS FILE!!!
// CPP2JAVA GENERATED FROM SOURCE FILE: wcgui.h
//****************************************************
//

package COM.winserver.wildcat;

import java.io.IOException;

public class TGetCurrentUser_Response extends TWildcatRequest {
  public TUser User;

  // Total size
  public static final int SIZE = TWildcatRequest.SIZE+TUser.SIZE;

  // Constructors
  public TGetCurrentUser_Response()
  {
  }

  public TGetCurrentUser_Response(byte[] x)
  {
    fromByteArray(x);
  }

  // Methods
  protected void writeTo(WcOutputStream out) throws IOException
  {
    super.writeTo(out);
    User.writeTo(out);
  }

  protected void readFrom(WcInputStream in) throws IOException
  {
    super.readFrom(in);
    User = new TUser(); User.readFrom(in);
  }
}
