//------------------------------------------------------------------------
// Delphi Wildcat! SDK API v6.0.451.1
// Copyright (c) 1998-2004 Santronics Software, Inc. All Rights Reserved.
//
// DO NOT EDIT THIS FILE!!!
// Automatically generated from wcgtype.h by cpp2pas.
//------------------------------------------------------------------------
{$O+,F+,I-,S-,R-}
unit wcgtype;

interface

{$IFDEF WIN32}
uses windows, wctype;
{$ELSE}
uses WinTypes, wctype;
{$ENDIF}


//! Group: Configuration Gateway Structures

const SIZE_GATE_HOST_NAME                   = SIZE_MESSAGE_NETWORK;

type TAutoResponseName = record
  name : array[0..SIZE_USER_NAME-1] of char;
end;

type TGateQwkHost = record
  Name : array[0..SIZE_GATE_HOST_NAME-1] of char;
  QwkPath : array[0..MAX_PATH-1] of char;
  RepPath : array[0..MAX_PATH-1] of char;
  AttachmentSizeLimit : DWORD;
  Packer : DWORD;
  AtFilter : BOOL;
  GateTag : BOOL;
  AppendRepPackets : BOOL;
  Index : DWORD;
  Reserved : array[0..84-1] of BYTE;
end;

type TGateQwkConf = record
  Conference : DWORD;
  HubConference : DWORD;
  TaglineId : DWORD;
  ExportPrivateMail : BOOL;
end;

const SIZE_GATE_ORGANIZATION                = 80;

type TGateUucpConfig = record
  AdministratorName : array[0..SIZE_USER_NAME-1] of char;
  LocalDomain : array[0..SIZE_DOMAIN_NAME-1] of char;
  LocalSiteName : array[0..SIZE_DOMAIN_NAME-1] of char;
  AlternateDomain : array[0..SIZE_DOMAIN_NAME-1] of char;
  Organization : array[0..SIZE_GATE_ORGANIZATION-1] of char;
  NewsRequestName : array[0..SIZE_USER_NAME-1] of char;
  PrimaryProvider : array[0..SIZE_GATE_HOST_NAME-1] of char;
  Reserved1 : DWORD;
  BounceInvalidMessages : BOOL;
  MaxExportMessageCount : DWORD;
  Reserved : array[0..72-1] of BYTE;
end;

const hfAllowHtmlImport                     =  $00000001;
const hfDisableEmailImport                  =  $00000010;
const hfDisableEmailExport                  =  $00000020;
const hfDisableNewsImport                   =  $00000100;
const hfDisableNewsExport                   =  $00000200;

type TGateUucpHost = record
  Name : array[0..SIZE_GATE_HOST_NAME-1] of char;
  Administrator : array[0..SIZE_USER_NAME-1] of char;
  Domain : array[0..SIZE_DOMAIN_NAME-1] of char;
  SiteName : array[0..SIZE_DOMAIN_NAME-1] of char;
  AttachmentSizeLimit : DWORD;
  DeleteFiles : BOOL;
  AllowNewsRequests : BOOL;
  SpoolPath : array[0..MAX_PATH-1] of char;
  AdditionalSpoolPath : array[0..MAX_PATH-1] of char;
  dwHostFlags : DWORD;
  EmailConference : DWORD;
  Reserved : array[0..16-1] of BYTE;
end;

const teBoth                     = 0;
const teImport                   = 1;
const teExport                   = 2;

type TGateTranslateEntry = record
  TranslateType : DWORD;
  LocalName : array[0..SIZE_USER_NAME-1] of char;
  ExternalName : array[0..SIZE_USER_NAME-1] of char;
end;

type TRpcTextData = record
  size : DWORD;
  data : char;
end;

type TGateMailingList = record
  Name : array[0..SIZE_USER_NAME-1] of char;
  Conference : DWORD;
  Reserved : array[0..52-1] of BYTE;
end;

type PGateAutoResponseName = ^TGateAutoResponseName;
     TGateAutoResponseName = array [0..SIZE_USER_NAME-1] of Char;

implementation

end.
