//------------------------------------------------------------------------
// Delphi Wildcat! SDK API v8.0.454.16
// Copyright (c) 1998-2025 Santronics Software, Inc. All Rights Reserved.
//
// DO NOT EDIT THIS FILE!!!
//
// Automatically generated from ..\include\wcgtype.h by cpp2pas.
//------------------------------------------------------------------------
{$O+,F+,I-,S-,R-}
unit wcgtype;

interface

{$IFDEF WIN32}
uses windows, wctype;
{$ELSE}
uses WinTypes, wctype;
{$ENDIF}


{$DEFINE __WCGTYPE_H}

//! Group: Configuration Gateway Structures

const SIZE_GATE_HOST_NAME                   = SIZE_MESSAGE_NETWORK;

type TAutoResponseName = record
  name : array[0..SIZE_USER_NAME-1] of char;
end;

type TGateQwkHost = record
  Name : array[0..SIZE_GATE_HOST_NAME-1] of char;
  QwkPath : array[0..MAX_PATH-1] of char;
  RepPath : array[0..MAX_PATH-1] of char;
  AttachmentSizeLimit : DWORD;
  Packer : DWORD;
  AtFilter : BOOL;
  GateTag : BOOL;
  AppendRepPackets : BOOL;
  Index : DWORD;
  Reserved : array[0..84-1] of BYTE;
end;

type TGateQwkConf = record
  Conference : DWORD;
  HubConference : DWORD;
  TaglineId : DWORD;
  ExportPrivateMail : BOOL;
end;

const SIZE_GATE_ORGANIZATION                = 80;

type TGateUucpConfig = record
  AdministratorName : array[0..SIZE_USER_NAME-1] of char;
  LocalDomain : array[0..SIZE_DOMAIN_NAME-1] of char;
  LocalSiteName : array[0..SIZE_DOMAIN_NAME-1] of char;
  AlternateDomain : array[0..SIZE_DOMAIN_NAME-1] of char;
  Organization : array[0..SIZE_GATE_ORGANIZATION-1] of char;
  NewsRequestName : array[0..SIZE_USER_NAME-1] of char;
  PrimaryProvider : array[0..SIZE_GATE_HOST_NAME-1] of char;
  Reserved1 : DWORD;
  BounceInvalidMessages : BOOL;
  MaxExportMessageCount : DWORD;
  Reserved : array[0..72-1] of BYTE;
end;

const hfAllowHtmlImport                     =  $00000001;
const hfDisableEmailImport                  =  $00000010;
const hfDisableEmailExport                  =  $00000020;
const hfDisableNewsImport                   =  $00000100;
const hfDisableNewsExport                   =  $00000200;
const hfReserved                            =  $00001000;  // 451.6
const hfLocalHost                           =  $00002000;  // 451.6 if off, Remote Host
const hfRouteSMTP                           =  $00004000;  // 451.6 if off, Keep in spool

const htEmailAndNews             = 0;  // = 0 default (compatible)
const htEmailOnly                = 1;
const htNewsOnly                 = 2;

type TGateUucpHost = record
  Name : array[0..SIZE_GATE_HOST_NAME-1] of char;
  Administrator : array[0..SIZE_USER_NAME-1] of char;
  Domain : array[0..SIZE_DOMAIN_NAME-1] of char;
  SiteName : array[0..SIZE_DOMAIN_NAME-1] of char;
  AttachmentSizeLimit : DWORD;
  DeleteFiles : BOOL;
  AllowNewsRequests : BOOL;
  SpoolPath : array[0..MAX_PATH-1] of char;
  AdditionalSpoolPath : array[0..MAX_PATH-1] of char;
  dwHostFlags : DWORD;
  EmailConference : DWORD;
  HostType : DWORD;
  Reserved : array[0..12-1] of BYTE;
end;

const teBoth                     = 0;
const teImport                   = 1;
const teExport                   = 2;

type TGateTranslateEntry = record
  TranslateType : DWORD;
  LocalName : array[0..SIZE_USER_NAME-1] of char;
  ExternalName : array[0..SIZE_USER_NAME-1] of char;
end;

type TGateMailingList = record
  Name : array[0..SIZE_USER_NAME-1] of char;
  Conference : DWORD;
  Reserved : array[0..52-1] of BYTE;
end;

type PGateAutoResponseName = ^TGateAutoResponseName;
     TGateAutoResponseName = array [0..SIZE_USER_NAME-1] of Char;

implementation

end.
