//------------------------------------------------------------------------
// Delphi Wildcat! SDK API v8.0.454.16
// Copyright (c) 1998-2025 Santronics Software, Inc. All Rights Reserved.
//
// DO NOT EDIT THIS FILE!!!
//
// Automatically generated from ..\include\wctypemw.h by cpp2pas.
//------------------------------------------------------------------------
{$O+,F+,I-,S-,R-}
unit wctypemw;

interface

{$IFDEF WIN32}
uses windows, wctype;
{$ELSE}
uses WinTypes, wctype;
{$ENDIF}


{$DEFINE __WCTYPEMW_H}

// const BOOL                                  = long;

const MAX_PATH                              = 260;

//! Group: Configuration Structures

//!---------------------------------------------------------
//! TConferencePaths provides the various directory setups
//! per mail confeference
//!---------------------------------------------------------

type TConferencePaths = record
  Display : array[0..MAX_PATH-1] of char;
  Bulletin : array[0..MAX_PATH-1] of char;
  Help : array[0..MAX_PATH-1] of char;
  Menu : array[0..MAX_PATH-1] of char;
  Questionnaire : array[0..MAX_PATH-1] of char;
  MsgDatabase : array[0..MAX_PATH-1] of char;
  Attach : array[0..MAX_PATH-1] of char;
end;

//!---------------------------------------------------------
//! TWildcatServerPrivateConfig is the configuration "MakeWild"
//! structure. The public field is exposed to normal
//! SDK clients.
//!---------------------------------------------------------

type TWildcatServerPrivateConfig = record
  Public : TMakewild;
  FileDatabasePath : array[0..MAX_PATH-1] of char;
  UserDatabasePath : array[0..MAX_PATH-1] of char;
  DefaultConferencePaths : TConferencePaths;
  SystemPassword : array[0..SIZE_ENCODED_PASSWORD-1] of char;
  MakewildPassword : array[0..SIZE_ENCODED_PASSWORD-1] of char;
  LanguagePath : array[0..MAX_PATH-1] of char;
  BatchFilePath : array[0..MAX_PATH-1] of char;
  dwServerOptions : DWORD;
end;

const srvFingerServer                       =  $00000001;  //! Enable Finger Server
const srvWcxMwLogin                         =  $00000002;  //! Allow WCX MwLogin
const srvWcxIpCheck                         =  $00000004;  //! Check WCX Peer Address
const srvOnlyLocalRPC                       =  $00000008;  //! Local RPC Only (v5.7)
const srvEnableGeoIP                        =  $00000010;  //! Open GeoIP database

//!---------------------------------------------------------
//! TWildcatServerPrivateConfDesc defines a mail conference
//! setup.
//!---------------------------------------------------------

type TWildcatServerPrivateConfDesc = record
  Public : TConfDesc;
  Paths : TConferencePaths;
end;

//!---------------------------------------------------------
//! TWildcatServerPrivateConfDesc defines a mail conference
//! setup.
//!---------------------------------------------------------

type TWildcatServerPrivateFileArea = record
  Public : TFileArea;
  Path : array[0..MAX_PATH-1] of char;
  Reserved : array[0..40-1] of BYTE;
end;

//!---------------------------------------------------------
//! TWildcatServerPrivateFileVolumec provides CD volume
//! setup information.
//!---------------------------------------------------------

type TWildcatServerPrivateFileVolume = record
  Name : array[0..SIZE_SHORT_FILE_NAME-1] of char;
  VolumeLabel : array[0..SIZE_SHORT_FILE_NAME-1] of char;
  UniqueFile : array[0..MAX_PATH-1] of char;
  Path : array[0..MAX_PATH-1] of char;
  Offline : BOOL;
  Reserved : array[0..84-1] of BYTE;
end;

// const BOOL                                  = int;

type PComputerName = ^TComputerName;
     TComputerName = array [0..SIZE_COMPUTER_NAME-1] of Char;

type PVolumeName = ^TVolumeName;
     TVolumeName = array [0..SIZE_VOLUME_NAME-1] of Char;

type PDoorName = ^TDoorName;
     TDoorName = array [0..SIZE_DOOR_NAME-1] of Char;

implementation

end.
