unit wccache;

{ DO NOT EDIT THIS FILE!!! }
{ This file is automatically generated from wccache.h by cpp2pas. }

interface

uses WinTypes, wctype, wchkeys;

function WcEnumKey(
  hkey: WCHKEY; 
  subkeyindex: Longint; 
  subkey: PChar; 
  cbsubkey: Longint): Longint;
function WcCreateKey(
  hkey: WCHKEY; 
  const subkey: PChar; 
  var phkey: WCHKEY): Longint;
function WcDeleteKey(
  hkey: WCHKEY; 
  const subkey: PChar): Longint;
function WcOpenKey(
  hkey: WCHKEY; 
  const subkey: PChar; 
  var phkey: WCHKEY): Longint;
function WcCloseKey(
  hkey: WCHKEY): Longint;
function WcSetValue(
  hkey: WCHKEY; 
  const value: PChar; 
  data: Pointer; 
  cbdata: Longint): Longint;
function WcQueryValue(
  hkey: WCHKEY; 
  const value: PChar; 
  data: Pointer; 
  var cbdata: Longint): Longint;
function WcDeleteValue(
  hkey: WCHKEY; 
  const value: PChar): Longint;
function WcQueryValueCRC(
  hkey: WCHKEY; 
  const value: PChar; 
  var crc: Longint): Longint;
function WcEnumValue(
  hkey: WCHKEY; 
  valueindex: Longint; 
  value: PChar; 
  cbvalue: Longint): Longint;
function WcGetKeyName(
  hkey: WCHKEY; 
  includepath: WordBool; 
  keyname: PChar; 
  cbkeyname: Longint): Longint;

implementation

function WcEnumKey; external 'wccache.dll';
function WcCreateKey; external 'wccache.dll';
function WcDeleteKey; external 'wccache.dll';
function WcOpenKey; external 'wccache.dll';
function WcCloseKey; external 'wccache.dll';
function WcSetValue; external 'wccache.dll';
function WcQueryValue; external 'wccache.dll';
function WcDeleteValue; external 'wccache.dll';
function WcQueryValueCRC; external 'wccache.dll';
function WcEnumValue; external 'wccache.dll';
function WcGetKeyName; external 'wccache.dll';

end.
