unit wchkeys;

{ DO NOT EDIT THIS FILE!!! }
{ This file is automatically generated from wchkey.h by cpp2pas. }

interface

uses WinTypes, wctype;

type WCHKEY = Longint;
const WCHKEY_ROOT                    =  $00000001;
const WCHKEY_SYSTEMS_ROOT            =  $00000002;
const WCHKEY_ADDRESSBOOK_ROOT        =  $00000003;
const WCHKEY_ADDRESSBOOK_USERS_ROOT  =  $00000004;
const WCHKEY_ADDRESSBOOK_GROUPS_ROOT =  $00000005;
const WCHKEY_CURRENT_SYSTEM          =  $00000018;

implementation


end.
