unit wcstype;

{ DO NOT EDIT THIS FILE!!! }
{ This file is automatically generated from wcstype.h by cpp2pas. }

interface

uses WinTypes, wctype;

const WCCT_NOTIFY_MESSAGE = 'WCCT_NOTIFY';
const WPARAM_DATA = 0;
const WPARAM_CLOSE = 1;
const WPARAM_DISCONNECT = 2;
const WPARAM_CLOSECLIENT = 3;
type client_info = object
  hWnd: HWnd;
  wMsg: Word;
  flags: Longint;
end;

const CLIENT_CLOSE_ON_DISCONNECT =  $00000001;
const INSTANT_CLIENT_WRITE_USER_PAGE = 'WC_WRITE_USER_PAGE';
const INSTANT_CLIENT_WRITE_USER_PAGE_DIRECT = 'WC_WRITE_USER_PAGE_DIRECT';
const INSTANT_MESSAGE_CLIENT_CLASS = 'WILDCAT INSTANT MESSAGE CLIENT CLASS';
const PAGE_NO_EDIT_TOUSER =  $0001;
const PAGE_INVITE_TO_CHAT =  $0002;
type TWriteUserPage = object
  ToUser: array [0..SIZE_USER_NAME-1] of char;
  FromUser: array [0..SIZE_USER_NAME-1] of char;
  Message: array [0..3-1, 0..80-1] of Char;
  Flags: Longint;
end;

const WcVersionRunClientMessage     = 'WildcatNavigatorRunClient';
const WcNavigatorCommandLineMessage = 'WildcatNavigatorCommandLine';
const SIZE_VERSION_CLASSNAME = 64;
const RUNCLIENT_EX_NO_SHOWWINDOW   =  $0001;
const RUNCLIENT_EX_NO_ERRORMESSAGE =  $0002;
type WcRunClientStructure = record
  Message: Word;
  wParam: Word;
  lParam: Longint;
  GlobalFreeLPARAM: WordBool;
  CommandLine: array [0.._MAX_PATH-1] of char;
  nCmdShow: Integer;
end;

const SIZE_ADDRESSBOOK_USER_NAME       = 72;
const SIZE_ADDRESSBOOK_ADDRESSTYPE     = 20;
const SIZE_ADDRESSBOOK_ADDRESS         = 256;
const SIZE_ADDRESSBOOK_SYSTEM_NAME     = 31;
const SIZE_ADDRESSBOOK_CACHE_NAME      = 31;
const WcAddressBook_Name              = 'Name';
const WcAddressBook_Title             = 'Title';
const WcAddressBook_Company           = 'Company';
const WcAddressBook_Phone             = 'Phone';
const WcAddressBook_Notes             = 'Notes';
const WcAddressBook_DefaultAddress    = 'Default Address';
const WcAddressBook_EmailAddress      = 'Email Address';
const WcAddressBook_EmailDestination  = 'Email Destination';
const WcAddressBook_AddressType       = 'AddressType';
const WcAddressBook_System            = 'System';
const WcAddressBook_Conference        = 'Conference';
const WcAddressBook_StreetAddress     = 'Address';
const WcAddressBook_City              = 'City';
const WcAddressBook_State             = 'State';
const WcAddressBook_ZipCode           = 'ZipCode';
const WcAddressBook_Country           = 'Country';
const WcAddressBook_Group             = 'Group';
const WcAddressBook_WildcatAddressType = 'Wildcat';
const WcAddressBook_AddUserAddressMessage = 'WildcatGUIAddUserAddress';
const WcAddressBook_GetRecipientListMessage = 'WildcatGUIGetRecipientList';
type WcAddressBookEntry = record
  AddressType: array [0..SIZE_ADDRESSBOOK_ADDRESSTYPE-1] of char;
  UserName: array [0..SIZE_ADDRESSBOOK_USER_NAME-1] of char;
  UserAddress: array [0..SIZE_ADDRESSBOOK_ADDRESS-1] of char;
  SystemName: array [0..SIZE_ADDRESSBOOK_SYSTEM_NAME-1] of char;
  Conference: Longint;
  IsGroup: WordBool;
  AddressCacheName: array [0..SIZE_ADDRESSBOOK_CACHE_NAME-1] of char;
end;

type WcAddressBookList = record
  entryCount: Longint;
  entries: array [0..1-1] of WcAddressBookEntry;
end;


implementation


end.
