unit wctype;

{ DO NOT EDIT THIS FILE!!! }
{ This file is automatically generated from wctype.h by cpp2pas. }

interface

uses WinTypes;

type TFileTime = record
  dwLowDateTime, dwHighDateTime: Longint;
end;

const _MAX_PATH = 260;

const MAX_PATH = 260;
type FILETIME = object
  dwLowDateTime: Longint;
  dwHighDateTime: Longint;
end;

const WILDCAT_VERSION         = 1;
const WILDCAT_MKTG_VERSION    = 5;
const WILDCAT_MARKETING_VERSION = '5.0';
const WILDCAT_COMPONENT_ICP   =  $00000001;
const SIZE_SHORT_FILE_NAME      = 16;
const SIZE_LONG_FILE_NAME       = MAX_PATH;
const SIZE_VOLUME_NAME          = 16;
const SIZE_CALLTYPE             = 32;
const SIZE_COMPUTER_NAME        = 16;
const SIZE_CONFERENCE_NAME      = 60;
const SIZE_CONFERENCEGROUP_NAME = 32;
const SIZE_DOMAIN_NAME          = 64;
const SIZE_DOOR_NAME            = 40;
const SIZE_ENCODED_PASSWORD     = 20;
const SIZE_EXTENSION            = 4;
const SIZE_FILEAREA_NAME        = 32;
const SIZE_FILEGROUP_NAME       = 32;
const SIZE_LANGUAGE_NAME        = 12;
const SIZE_MENU_DESCRIPTION     = 40;
const SIZE_MODEM_NAME           = 32;
const SIZE_PASSWORD             = 32;
const SIZE_SECURITY_NAME        = 24;
const SIZE_SERVICE_NAME         = 64;
const SIZE_USER_NAME            = 72;
const MAX_USER_NAME = 28;
const MASK_OBJECTCLASS            =  $FF000000;
const OBJECTCLASS_RIGHTS          =  $01000000;
const OBJECTCLASS_CONFERENCE      =  $02000000;
const OBJECTCLASS_CONFERENCEGROUP =  $03000000;
const OBJECTCLASS_FILEAREA        =  $04000000;
const OBJECTCLASS_FILEGROUP       =  $05000000;
const OBJECTCLASS_DOOR            =  $06000000;
const OBJECTCLASS_MENU            =  $07000000;
const OBJECTCLASS_CODE            =  $08000000;
const OBJECTCLASS_CLIENT          =  $09000000;
const OBJECTCLASS_SAPPHIRE_QUERY  =  $0a000000;
const OBJECTCLASS_CHAT_CHANNEL    =  $0b000000;
const OBJECTCLASS_RADIUS_CLIENT   =  $0c000000;
const OBJECTCLASS_DOMAINS         =  $0d000000;
const OBJECTID_BULLETINS_OPTIONAL          = OBJECTCLASS_RIGHTS + 1;
const OBJECTID_CHANGE_PHONE                = OBJECTCLASS_RIGHTS + 2;
const OBJECTID_CHANGE_BIRTHDATE            = OBJECTCLASS_RIGHTS + 4;
const OBJECTID_QWK_ALLOW_BULLETINS         = OBJECTCLASS_RIGHTS + 5;
const OBJECTID_QWK_ALLOW_NEWS              = OBJECTCLASS_RIGHTS + 6;
const OBJECTID_QWK_ALLOW_FILES             = OBJECTCLASS_RIGHTS + 7;
const OBJECTID_QWK_DETAIL_DOWNLOAD         = OBJECTCLASS_RIGHTS + 8;
const OBJECTID_QWK_CHECK_DUPES             = OBJECTCLASS_RIGHTS + 9;
const OBJECTID_QWK_SAVE_PACKETS            = OBJECTCLASS_RIGHTS + 10;
const OBJECTID_MASTER_SYSOP                = OBJECTCLASS_RIGHTS + 11;
const OBJECTID_RATIO_ACTION                = OBJECTCLASS_RIGHTS + 12;
const OBJECTID_ALLOW_FAST_LOGIN            = OBJECTCLASS_RIGHTS + 13;
const OBJECTID_ALLOW_OVERWRITE_FILES       = OBJECTCLASS_RIGHTS + 14;
const OBJECTID_SHOW_PASSWORD_FILES         = OBJECTCLASS_RIGHTS + 15;
const OBJECTID_ALLOW_OFFLINE_FILE_REQUESTS = OBJECTCLASS_RIGHTS + 16;
const OBJECTID_ALLOW_UPLOAD_OVER_TIME      = OBJECTCLASS_RIGHTS + 17;
const OBJECTID_ALLOW_DOWNLOAD_OVER_TIME    = OBJECTCLASS_RIGHTS + 18;
const OBJECTID_ALLOW_UPLOADER_MODIFY_FILE  = OBJECTCLASS_RIGHTS + 20;
const OBJECTID_QWK_NETSTATUS               = OBJECTCLASS_RIGHTS + 26;
const OBJECTID_SYSOP_READ_PRIVATE_MAIL     = OBJECTCLASS_RIGHTS + 27;
const OBJECTID_ALLOW_INTERNET_EMAIL        = OBJECTCLASS_RIGHTS + 28;
const OBJECTID_ALLOW_ANY_TELNET            = OBJECTCLASS_RIGHTS + 29;
const OBJECTID_ALLOW_ANY_FTP               = OBJECTCLASS_RIGHTS + 30;
const OBJECTID_ALLOW_HTTP_PROXY            = OBJECTCLASS_RIGHTS + 31;
const OBJECTID_ALLOW_ALL_IP                = OBJECTCLASS_RIGHTS + 32;
const OBJECTID_ALLOW_DEFAULT_IP            = OBJECTCLASS_RIGHTS + 33;
const OBJECTID_ALLOW_PPP                   = OBJECTCLASS_RIGHTS + 34;
const OBJECTID_IGNORE_TIME_ONLINE          = OBJECTCLASS_RIGHTS + 35;
const OBJECTID_IGNORE_IDLE_TIME            = OBJECTCLASS_RIGHTS + 36;
const OBJECTID_ALLOW_SMTP_AUTH			 = OBJECTCLASS_RIGHTS + 37;
const OBJECTID_ALLOW_NNTP     			 = OBJECTCLASS_RIGHTS + 38;
const OBJECTID_USERBIN_ACCESS    			 = OBJECTCLASS_RIGHTS + 39;
const OBJECTID_PROTOCOL_ACCESS             = OBJECTCLASS_RIGHTS +  $00010000;
const OBJECTID_NODE_ACCESS                 = OBJECTCLASS_RIGHTS +  $00020000;
const OBJECTFLAGS_CONFERENCE_JOIN  =  $00000001;
const OBJECTFLAGS_CONFERENCE_READ  =  $00000002;
const OBJECTFLAGS_CONFERENCE_WRITE =  $00000004;
const OBJECTFLAGS_CONFERENCE_SYSOP =  $00000008;
const OBJECTFLAGS_FILEAREA_LIST     =  $00000001;
const OBJECTFLAGS_FILEAREA_DOWNLOAD =  $00000002;
const OBJECTFLAGS_FILEAREA_UPLOAD   =  $00000004;
const OBJECTFLAGS_FILEAREA_SYSOP    =  $00000008;
const MSF_FORWARD =  $00000001;
const MSF_FROM    =  $00000002;
const MSF_TO      =  $00000004;
const MSF_SUBJECT =  $00000008;
const MSF_BODY    =  $00000010;
const CONNECT_RAW          = 0;
const CONNECT_TELNET_ASCII = 1;
const CONNECT_TELNET_7BIT  = 2;
const CONNECT_TELNET_8BIT  = 3;
const UserIdKey       = 0;
const UserNameKey     = 1;
const UserLastNameKey = 2;
const UserSecurityKey = 3;
const FileNameAreaKey = 0;
const FileAreaNameKey = 1;
const FileAreaDateKey = 2;
const FileUploaderKey = 3;
const FileDateAreaKey = 4;
const CHANNEL_MESSAGE_HEADER_SIZE = 12;
const MAX_CHANNEL_MESSAGE_SIZE = 500;
type TChannelMessage = record
  Channel: Longint;
  SenderId: Longint;
  UserData: Word;
  DataSize: Word;
  Data: array [0..MAX_CHANNEL_MESSAGE_SIZE-1] of Byte;
end;

type TObjectName = record
  Status: Longint;
  ObjectId: Longint;
  Number: Longint;
  Name: array [0..MAX_PATH-1] of char;
end;

const SIZE_PACKER_DESCRIPTION = 32;
const SIZE_PACKER_COMMAND = 40;
type TPackerRec = record
  Letter: Longint;
  Description: array [0..SIZE_PACKER_DESCRIPTION-1] of char;
  Extension: array [0..SIZE_EXTENSION-1] of char;
  Packer: array [0..SIZE_PACKER_COMMAND-1] of char;
  Unpacker: array [0..SIZE_PACKER_COMMAND-1] of char;
end;

const MAX_PACKER_COUNT = 10;
const SIZE_MAKEWILD_BBSNAME       = 52;
const SIZE_MAKEWILD_CITY          = 32;
const SIZE_MAKEWILD_PHONE         = 28;
const SIZE_MAKEWILD_FIRSTCALL     = 28;
const SIZE_MAKEWILD_PACKETID      = 12;
const SIZE_MAKEWILD_REGSTRING     = 8;
const saOpen = 0;
const // = 1;
const Open = 2;
const accounts = 3;
const created = 4;
const dusNone = 0;
const dusAsk = 1;
const dusAllow = 2;
type TWildcatTimeouts = record
  dwVersion: Word;
  dwRevision: Word;
  Web: Longint;
  WebQues: Longint;
  Telnet: Longint;
  TelnetLogin: Longint;
  Ftp: Longint;
  wcPPP: Longint;
  wcNAV: Longint;
  Reserved: array [0..92-1] of char;
end;

type TWildcatHttpd = record
   dwVersion: Word;
   dwRevision: Word;
  CommonLogFile: WordBool;
  DeutschIVW: WordBool;
  DailyLogsEnabled: WordBool;
  Reserved: array [0..96-1] of char;
end;

type TWildcatSMTP = record
   dwVersion: Word;
   dwRevision: Word;
  port: Longint;
  sendthreads: Longint;
  VerboseLogging: Longint;
  acceptonly: WordBool;
  retries: Longint;
  retrywait: Longint;
  smarthost: array [0..52-1] of char;
  sizelimit: Longint;
  localonly: WordBool;
  MAPSRBL: WordBool;
  MAPSRBLServer: array [0..52-1] of char;
  ESMTP: WordBool;
  reqauth: WordBool;
  VRFY: WordBool;
  AllowRelay: WordBool;
  CheckRCPT: WordBool;
  EnableBadFilter: WordBool;
  RequireMX: WordBool;
  RequireHostMatch: WordBool;
end;

const mhcUpperCase = 0;
const mhcLowerCase = 1;
type TMakewild = record
  Version: Longint;
  BBSName: array [0..SIZE_MAKEWILD_BBSNAME-1] of char;
  SysopName: array [0..MAX_USER_NAME-1] of char;
  City: array [0..SIZE_MAKEWILD_CITY-1] of char;
  Phone: array [0..SIZE_MAKEWILD_PHONE-1] of char;
  FirstCall: array [0..SIZE_MAKEWILD_FIRSTCALL-1] of char;
  PacketId: array [0..SIZE_MAKEWILD_PACKETID-1] of char;
  RegString: array [0..SIZE_MAKEWILD_REGSTRING-1] of char;
  SystemAccess: Longint;
  MaxLoginAttempts: Longint;
  FreeFormPhone: WordBool;
  HideAnonFtpPassword: WordBool;
  LogonLanguagePrompt: WordBool;
  Assume8N1: WordBool;
  LoginAskLocation: WordBool;
  NewUserSecurity: array [0..SIZE_SECURITY_NAME-1] of char;
  DefaultExt: array [0..SIZE_EXTENSION-1] of char;
  ThumbnailFile: array [0..SIZE_SHORT_FILE_NAME-1] of char;
  OldDoorPath: array [0..MAX_PATH-1] of char;
  EnableHttpProxy: WordBool;
  Reserved: array [0..772-1] of char;
  CaseSensitivePasswords: WordBool;
  MsgHeaderCaseMode: Longint;
  SpamAllowAuth: WordBool;
  SMTPConfig: TWildcatSMTP;
  HttpdConfig: TWildcatHttpd;
  Timeouts: TWildcatTimeouts;
  DefaultColors: array [0..28-1] of Byte;
  ExcludeBulletins: array [0..40-1] of Longint;
  InstalledComponents: Longint;
  ResolveHostnames: WordBool;
  BuildDate: array [0..16-1] of char;
  DomainName: array [0..SIZE_DOMAIN_NAME-1] of char;
  WindowsCharset: WordBool;
  LogonUserNameOnly: WordBool;
end;

type TComputerConfig = record
  Name: array [0..SIZE_COMPUTER_NAME-1] of char;
  DoorPath: array [0..MAX_PATH-1] of char;
  CgiPath: array [0..MAX_PATH-1] of char;
  HttpPort: Longint;
  FtpPort: Longint;
  WWWHostname: array [0..80-1] of char;
  Servers: Longint;
  HttpProxyPort: Longint;
  Reserved: array [0..392-1] of Byte;
end;

const pNone = 0;
const pAscii = 1;
const pXmodem = 2;
const pXmodemCRC = 3;
const pXmodem1K = 4;
const pXmodem1KG = 5;
const pYmodem = 6;
const pYmodemG = 7;
const pKermit = 8;
const pZmodem = 9;
const NumProtocols = 10;
const fiaAllow = 0;
const fiaLogoff = 1;
const fiaLockout = 2;
const pwdChangeForce     =  $0001;
const pwdChangeDisallow  =  $0002;
const pwdChangeExpire    =  $0004;
const pwdExpireLockout   =  $0008;
type TLogonhours = record
  day: array [0..7-1] of Longint;
end;

const lh12am              =  $00000001;
const lh1am               =  $00000002;
const lh2am               =  $00000004;
const lh3am               =  $00000008;
const lh4am               =  $00000010;
const lh5am               =  $00000020;
const lh6am               =  $00000040;
const lh7am               =  $00000080;
const lh8am               =  $00000100;
const lh9am               =  $00000200;
const lh10am              =  $00000400;
const lh11am              =  $00000800;
const lh12pm              =  $00001000;
const lh1pm               =  $00002000;
const lh2pm               =  $00004000;
const lh3pm               =  $00008000;
const lh4pm               =  $00010000;
const lh5pm               =  $00020000;
const lh6pm               =  $00040000;
const lh7pm               =  $00080000;
const lh8pm               =  $00100000;
const lh9pm               =  $00200000;
const lh10pm              =  $00400000;
const lh11pm              =  $00800000;
const lhAllHours          =  $00FFFFFF;
const lhSun               =  $01;
const lhMon               =  $02;
const lhTue               =  $04;
const lhWed               =  $08;
const lhThu               =  $10;
const lhFri               =  $20;
const lhSat               =  $40;
const lhAllDays           =  $7F;
const lhStartofWeek       = lhSun;
const lhEndofWeek         = lhSat;
type TSecurityProfile = record
  Name: array [0..SIZE_SECURITY_NAME-1] of char;
  ExpiredName: array [0..SIZE_SECURITY_NAME-1] of char;
  DisplayFileName: array [0..SIZE_SHORT_FILE_NAME-1] of char;
  DoorSysProfileName: array [0..SIZE_SECURITY_NAME-1] of char;
  MenuDisplaySet: array [0..SIZE_SHORT_FILE_NAME-1] of char;
  DailyTimeLimit: Longint;
  PerCallTimeLimit: Longint;
  VerifyPhoneInterval: Longint;
  VerifyBirthdateInterval: Longint;
  FailedInfoAction: Longint;
  MaxDownloadCountPerDay: Longint;
  DownloadRatioLimit: Longint;
  MaxDownloadKbytesPerDay: Longint;
  DownloadKbytesRatioLimit: Longint;
  UploadTimeCredit: Longint;
  ExpireDays: Longint;
  PasswordOptions: Word;
  PasswordExpireDays: Word;
  FtpSpaceKbytes: Longint;
  EmailDomainName: array [0..SIZE_DOMAIN_NAME-1] of char;
  MaximumLogons: Longint;
  RestrictedHours: WordBool;
  LogonHours: TLogonHours;
end;

const SIZE_CONFERENCE_ECHOTAG = 64;
const mtNormalPublicPrivate = 0;
const mtNormalPublic = 1;
const mtNormalPrivate = 2;
const mtFidoNetmail = 3;
const mtEmailOnly = 4;
const mtUsenetNewsgroup = 5;
const mtUsenetNewsgroupModerated = 6;
const mtInternetMailingList = 7;
const 02 = 8;
const mtFidoEcho = 9;
const mtListServeForum = 10;
const 05 = 11;
const mtUserEmail = 12;
const mtUserEmail = 13;
const (null) = 14;
const mtEND = 15;
const vnYes = 0;
const vnNo = 1;
const vnPrompt = 2;
const maAllowMailSnooping =  $00000001;
const authorDefaultName = 0;
const authorForceUserName = 1;
const authorForceAliasName = 2;
const authorAllowBoth = 3;
const authorAnonymousName = 4;
type TConfDesc = record
  ObjectId: Longint;
  Number: Longint;
  Name: array [0..SIZE_CONFERENCE_NAME-1] of char;
  Reserved1: array [0..16-1] of char;
  ConferenceSysop: array [0..MAX_USER_NAME-1] of char;
  EchoTag: array [0..SIZE_CONFERENCE_ECHOTAG-1] of char;
  ReplyToAddress: array [0..SIZE_USER_NAME-1] of char;
  Distribution: array [0..SIZE_USER_NAME-1] of char;
  MailType: Longint;
  PromptToKillMsg: WordBool;
  PromptToKillAttach: WordBool;
  AllowHighAscii: WordBool;
  AllowCarbon: WordBool;
  AllowReturnReceipt: WordBool;
  LongHeaderFormat: WordBool;
  AllowAttach: WordBool;
  ShowCtrlLines: WordBool;
  ValidateNames: Longint;
  DefaultFileGroup: Longint;
  MaxMessages: Longint;
  DaysToKeepReceivedMail: Longint;
  DaysToKeepPublicMail: Longint;
  RenumberThreshold: Longint;
  DaysToKeepExternalMail: Longint;
   DeleteSMTPDelivered: WordBool;
  PublishAsLocalNewsGroup: WordBool;
  Options: Longint;
  AuthorType: Longint;
  Reserved: array [0..10-1] of Byte;
  DefaultFromAddress: array [0..SIZE_USER_NAME-1] of char;
   wVersion: Word;
end;

type TShortConfDesc = record
  ObjectId: Longint;
  Name: array [0..SIZE_CONFERENCE_NAME-1] of char;
  MailType: Longint;
end;

type TConferenceGroup = record
  ObjectId: Longint;
  Number: Longint;
  Name: array [0..SIZE_CONFERENCEGROUP_NAME-1] of char;
  Reserved: array [0..24-1] of Byte;
end;

const faIsVolume          =  $00000001;
const faAllowPrivateFiles =  $00000002;
type TFileArea = record
  ObjectId: Longint;
  Number: Longint;
  Name: array [0..SIZE_FILEAREA_NAME-1] of char;
  ExcludeFromNewFiles: WordBool;
  PromptForPasswordProtect: WordBool;
  FtpDirectoryName: array [0..SIZE_FILEAREA_NAME-1] of char;
  Options: Longint;
end;

type TShortFileArea = record
  ObjectId: Longint;
  Name: array [0..SIZE_FILEAREA_NAME-1] of char;
end;

type TFileGroup = record
  ObjectId: Longint;
  Number: Longint;
  Name: array [0..SIZE_FILEGROUP_NAME-1] of char;
  Reserved: array [0..24-1] of Byte;
end;

const dtGeneric16 = 0;
const dtDoor32 = 1;
const dtDoorway = 2;
type TDoorInfo = record
  ObjectId: Longint;
  Name: array [0..SIZE_DOOR_NAME-1] of char;
  Batch: array [0..SIZE_SHORT_FILE_NAME-1] of char;
  Display: array [0..SIZE_SHORT_FILE_NAME-1] of char;
  DoorMenuIndex: Longint;
  MultiUser: WordBool;
  SmallDoorSys: WordBool;
  DoorType: Longint;
  Reserved: array [0..36-1] of Byte;
end;

const SIZE_LANGUAGE_DESCRIPTION     = 72;
const MAX_LANGUAGE_SUBCOMMAND_CHARS = 100;
const LSC_YES   = 0;
const LSC_NO    = 1;
type TLanguageInfo = record
  Name: array [0..SIZE_LANGUAGE_NAME-1] of char;
  Description: array [0..SIZE_LANGUAGE_DESCRIPTION-1] of char;
  SubcommandChars: array [0..MAX_LANGUAGE_SUBCOMMAND_CHARS-1] of char;
  Reserved: array [0..72-1] of Byte;
end;

const SIZE_MODEM_STRING = 64;
const aRing = 0;
const aResult = 1;
const aAutoAnswer = 2;
type TShortModemProfile = record
  UserDefined: WordBool;
  Name: array [0..SIZE_MODEM_NAME-1] of char;
end;

type TModemProfile = record
  Version: Longint;
  UserDefined: WordBool;
  Name: array [0..SIZE_MODEM_NAME-1] of char;
  InitBaud: Longint;
  LockDTE: WordBool;
  HardwareFlow: WordBool;
  ExitOffHook: WordBool;
  CarrierDelay: Longint;
  RingDelay: Longint;
  DropDtrDelay: Longint;
  PrelogDelay: Longint;
  ResultDelay: Longint;
  ResetDelay: Longint;
  AnswerMethod: Longint;
  EnableCallerId: Longint;
  ResetCommand: array [0..SIZE_MODEM_STRING-1] of char;
  AnswerCommand: array [0..SIZE_MODEM_STRING-1] of char;
  Reserved1: array [0..SIZE_MODEM_STRING-1] of char;
  OffHook: array [0..SIZE_MODEM_STRING-1] of char;
  RingResult: array [0..SIZE_MODEM_STRING-1] of char;
  ConnectResult: array [0..SIZE_MODEM_STRING-1] of char;
  Reserved2: array [0..SIZE_MODEM_STRING-1] of char;
  ErrorFreeResult: array [0..SIZE_MODEM_STRING-1] of char;
  ExtraBaudResults: array [0..10-1, 0..SIZE_MODEM_STRING-1] of Char;
  ExtraBaudResultNumbers: array [0..10-1] of Longint;
  Reserved3: array [0..SIZE_MODEM_STRING-1] of char;
  InitCommand: array [0..SIZE_MODEM_STRING-1] of char;
  Reserved4: array [0..SIZE_MODEM_STRING-1] of char;
  Reserved5: array [0..3-1, 0..SIZE_MODEM_STRING-1] of Char;
  Reserved6: array [0..256-1] of char;
  Reserved: array [0..128-1] of Byte;
end;

const CALLTYPE_LOCAL    =  $00000001;
const CALLTYPE_DIALUP   =  $00000002;
const CALLTYPE_TELNET   =  $00000004;
const CALLTYPE_FTP      =  $00000008;
const CALLTYPE_HTTP     =  $00000010;
const CALLTYPE_FRONTEND =  $00000020;
const CALLTYPE_POP3     =  $00000040;
const CALLTYPE_SMTP     =  $00000080;
const CALLTYPE_PPP      =  $00000100;
const CALLTYPE_RADIUS   =  $00000200;
const CALLTYPE_NNTP     =  $00000400;
const SIZE_NODECONFIG_COMPUTER = 16;
const SIZE_NODECONFIG_PORTNAME = 16;
type TNodeConfig = record
  CallTypesAllowed: Longint;
  ModemName: array [0..SIZE_MODEM_NAME-1] of char;
  Computer: array [0..SIZE_NODECONFIG_COMPUTER-1] of char;
  Port: array [0..SIZE_NODECONFIG_PORTNAME-1] of char;
  PermanentLineID: Longint;
  VirtualDoorPort: array [0..8-1] of char;
  Reserved: array [0..48-1] of Byte;
end;

const SIZE_SERVERSTATE_PORT = 80;
const SERVERSTATE_OFFLINE = 0;
const SERVERSTATE_DOWN    = 1;
const SERVERSTATE_REFUSE  = 2;
const SERVERSTATE_UP      = 3;
type TServerState = record
  OwnerId: Longint;
  Computer: array [0..SIZE_NODECONFIG_COMPUTER-1] of char;
  Port: array [0..SIZE_SERVERSTATE_PORT-1] of char;
  State: Longint;
end;

const MENU_TOPLEVEL  =  $00000002;
const MAX_MENU_ITEMS = 40;
const SIZE_MENUITEM_SELECTION = 16;
const SIZE_MENUITEM_DESCRIPTION = 32;
const SIZE_MENUITEM_COMMAND = 48;
type TwcMenuItem = record
  Selection: array [0..SIZE_MENUITEM_SELECTION-1] of char;
  Description: array [0..SIZE_MENUITEM_DESCRIPTION-1] of char;
  Command: array [0..SIZE_MENUITEM_COMMAND-1] of char;
  Parameters: array [0..SIZE_MENUITEM_COMMAND-1] of char;
  Reserved: array [0..4-1] of Byte;
end;

type TMenu = record
  ObjectId: Longint;
  Description: array [0..SIZE_MENU_DESCRIPTION-1] of char;
  DisplayName: array [0..SIZE_SHORT_FILE_NAME-1] of char;
  Flags: Longint;
  Count: Longint;
  Items: array [0..MAX_MENU_ITEMS-1] of TwcMenuItem;
  FastLoginChar: Longint;
  SecurityEntryName: array [0..SIZE_SECURITY_NAME-1] of char;
  Reserved: array [0..128-1] of Byte;
end;

const SIZE_USER_TITLE = 12;
type TUserInfo = record
  Id: Longint;
  Name: array [0..SIZE_USER_NAME-1] of char;
  Title: array [0..SIZE_USER_TITLE-1] of char;
end;

const clSessionNone = 0;
const clSessionUser = 1;
const clSessionSystem = 2;
const clSessionConfig = 3;
const nsDown = 0;
const nsUp = 1;
const nsSigningOn = 2;
const nsLoggedIn = 3;
const SIZE_NODEINFO_ACTIVITY = 32;
const SIZE_NODEINFO_SPEED = 8;
const SIZE_NODEINFO_LASTCALLER = 48;
const SIZE_USER_FROM = 32;
type TwcNodeInfo = record
  NodeStatus: Longint;
  ServerState: Longint;
  ConnectionId: Longint;
  LastCaller: array [0..SIZE_NODEINFO_LASTCALLER-1] of char;
  User: TUserInfo;
  UserFrom: array [0..SIZE_USER_FROM-1] of char;
  UserPageAvailable: WordBool;
  Reserved1: WordBool;
  Activity: array [0..SIZE_NODEINFO_ACTIVITY-1] of char;
  Speed: array [0..SIZE_NODEINFO_SPEED-1] of char;
  TimeCalled: TFileTime;
  CurrentTime: TFileTime;
  Reserved2: Longint;
  NodeNumber: Longint;
  MinutesLeft: Longint;
end;

const ucstNone        = 0;
const ucstPersonal    = 1;
const ucstPersonalAll = 2;
const ucstAll         = 3;
const ucstMask     =  $0F;
const ucfReserved1 =  $10;
const ucfReserved2 =  $20;
const ucfReserved3 =  $40;
const ucfAllAttach =  $80;
const SIZE_USER_PHONE = 16;
const SIZE_USER_ADDRESS = 32;
const SIZE_USER_STATE = 16;
const SIZE_USER_ZIP = 12;
const NUM_USER_SECURITY = 10;
const sNotDisclosed = 0;
const sMale = 1;
const sFemale = 2;
const ePrompt = 0;
const eLine = 1;
const eFullScreen = 2;
const hlNovice = 0;
const hlRegular = 1;
const hlExpert = 2;
const ttAuto = 0;
const ttTTY = 1;
const ttAnsi = 2;
const fdSingle = 0;
const fdDouble = 1;
const fdFull = 2;
const fdAnsi = 3;
const mdScroll = 0;
const mdClear = 1;
const mdKeepHeader = 2;
const ptText = 0;
const ptQwk = 1;
const ptOPX = 2;
const vsNone = 0;
const // = 1;
const No = 2;
const validation = 3;
const required = 4;
type TUser = record
  Status: Longint;
  Info: TUserInfo;
  From: array [0..SIZE_USER_FROM-1] of char;
  Password: array [0..SIZE_PASSWORD-1] of char;
  Security: array [0..NUM_USER_SECURITY-1, 0..SIZE_SECURITY_NAME-1] of Char;
  Reserved1: Longint;
  AllowMultipleLogins: WordBool;
  LogonHoursOverride: WordBool;
  RealName: array [0..SIZE_USER_NAME-1] of char;
  PhoneNumber: array [0..SIZE_USER_PHONE-1] of char;
  Company: array [0..SIZE_USER_ADDRESS-1] of char;
  Address1: array [0..SIZE_USER_ADDRESS-1] of char;
  Address2: array [0..SIZE_USER_ADDRESS-1] of char;
  City: array [0..SIZE_USER_ADDRESS-1] of char;
  State: array [0..SIZE_USER_STATE-1] of char;
  Zip: array [0..SIZE_USER_ZIP-1] of char;
  Country: array [0..SIZE_USER_ADDRESS-1] of char;
  Sex: Longint;
  Editor: Longint;
  HelpLevel: Longint;
  Protocol: Longint;
  TerminalType: Longint;
  FileDisplay: Longint;
  MsgDisplay: Longint;
  PacketType: Longint;
  LinesPerPage: Longint;
  HotKeys: WordBool;
  QuoteOnReply: WordBool;
  SortedListings: WordBool;
  PageAvailable: WordBool;
  EraseMorePrompt: WordBool;
  Reserved3: WordBool;
  Language: array [0..SIZE_LANGUAGE_NAME-1] of char;
  LastCall: TFileTime;
  LastNewFiles: TFileTime;
  ExpireDate: TFileTime;
  FirstCall: TFileTime;
  BirthDate: TFileTime;
  Conference: Longint;
  MsgsWritten: Longint;
  Uploads: Longint;
  TotalUploadKbytes: Longint;
  Downloads: Longint;
  TotalDownloadKbytes: Longint;
  DownloadCountToday: Longint;
  DownloadKbytesToday: Longint;
  TimesOn: Longint;
  TimeLeftToday: Longint;
  MinutesLogged: Longint;
  SubscriptionBalance: Longint;
  NetmailBalance: Longint;
  AccountLockedOut: WordBool;
  PreserveMimeMessages: WordBool;
  ShowEmailHeaders: WordBool;
  LastUpdate: TFileTime;
  SystemFlags: Word;
  UserFlags: Word;
  Validation: Longint;
  PasswordOptions: Word;
  PasswordExpireDays: Word;
  PasswordChangeDate: TFileTime;
  AnonymousOnly: WordBool;
  AllowUserDirectory: WordBool;
end;

const SIZE_MESSAGE_SUBJECT = 72;
const SIZE_MESSAGE_NETWORK = 12;
type TFidoAddress = record
  Zone: Word;
  Net: Word;
  Node: Word;
  Point: Word;
end;

const mfPOP3Received      =  $01000000;
const mfReceiptCreated    =  $02000000;
const mfSmtpDelivered     =  $04000000;
const mfNNTPPost          =  $08000000;
const mfMimeSaved         =  $00000001;
type TMsgHeader = record
  Status: Longint;
  Conference: Longint;
  Id: Longint;
  Number: Longint;
  From: TUserInfo;
  Whoto: TUserInfo;
  Subject: array [0..SIZE_MESSAGE_SUBJECT-1] of char;
  PostedTimeGMT: TFileTime;
  MsgTime: TFileTime;
  ReadTime: TFileTime;
  Private: WordBool;
  Received: WordBool;
  ReceiptRequested: WordBool;
  Deleted: WordBool;
  Tagged: WordBool;
  Reference: Longint;
  ReplyCount: Longint;
  FidoFrom: TFidoAddress;
  FidoTo: TFidoAddress;
  FidoFlags: Longint;
  MsgSize: Longint;
  PrevUnread: Longint;
  NextUnread: Longint;
  Network: array [0..SIZE_MESSAGE_NETWORK-1] of char;
  Attachment: array [0..SIZE_SHORT_FILE_NAME-1] of char;
  AllowDisplayMacros: WordBool;
  AddedByUserId: Longint;
  Exported: WordBool;
  MailFlags: Longint;
  NextAttachment: Longint;
  ReadCount: Longint;
  Reserved: array [0..112-1] of Byte;
end;

const SIZE_FILE_DESCRIPTION = 76;
const MAX_FILE_LONGDESC_LINES = 15;
const SIZE_FILE_LONGDESC = 80;
const ffAbortedUpload     =  $00000001;
type TFileRecord = record
  Status: Longint;
  Area: Longint;
  SFName: array [0..SIZE_SHORT_FILE_NAME-1] of char;
  Description: array [0..SIZE_FILE_DESCRIPTION-1] of char;
  Password: array [0..SIZE_PASSWORD-1] of char;
  FileFlags: Longint;
  Size: Longint;
  FileTime: TFileTime;
  LastAccessed: TFileTime;
  NeverOverwrite: WordBool;
  NeverDelete: WordBool;
  FreeFile: WordBool;
  CopyBeforeDownload: WordBool;
  Offline: WordBool;
  FailedScan: WordBool;
  FreeTime: WordBool;
  Downloads: Longint;
  Cost: Longint;
  Uploader: TUserInfo;
  UserInfo: Longint;
  HasLongDescription: WordBool;
  PostTime: TFileTime;
  PrivateUserId: Longint;
  Reserved: array [0..32-1] of Byte;
  Name: array [0..SIZE_LONG_FILE_NAME-1] of char;
  Reserved2: array [0..100-1] of Byte;
end;

type TFullFileRecord = record
  Info: TFileRecord;
  StoredPath: array [0..MAX_PATH-1] of char;
  LongDescription: array [0..MAX_FILE_LONGDESC_LINES-1, 0..SIZE_FILE_LONGDESC-1] of Char;
end;

type TSpellSuggestList = record
  Words: array [0..10-1, 0..32-1] of Char;
end;

const SC_WATCH_REQUEST      = 0;
const SC_DISPLAY_UPDATE     = 1;
const SC_PUSH_KEY           = 2;
const SC_SECURITY_CHANGE    = 3;
const SC_DISCONNECT         = 4;
const SC_TIME_CHANGE        = 5;
const SC_USER_RECORD_CHANGE = 6;
const SE_FILE_UPLOAD          = 10;
const SE_FILE_DOWNLOAD        = 11;
const SE_FILE_DELETE          = 12;
const SE_FILE_UPDATE          = 13;
const SE_SHUTDOWN_REQUEST     = 20;
const SE_RESTART              = 21;
const SE_CONFIG_CHANGE        = 22;
const SE_SERVER_STATE_CHANGE  = 30;
const SE_NODE_STATE_CHANGE    = 31;
type TSystemEventFileInfo = record
  FileArea: Longint;
  ConnectionId: Longint;
  TimeStamp: TFileTime;
   szFileName: array [0..SIZE_LONG_FILE_NAME-1] of char;
end;

type TSystemControlViewMsg = record
  Line: Word;
  Count: Word;
  Text: array [0..3-1, 0..80-1] of Word;
  CursorX: Word;
  CursorY: Word;
  MinutesLeft: Word;
end;

const SP_USER_PAGE       = 0;
const SP_SYSOP_CHAT      = 1;
const SP_NEW_MESSAGE     = 2;
const SP_ALT_NUMBER_FILE = 3;
type TSystemPageNewMessage = record
  Conference: Longint;
  ConferenceName: array [0..SIZE_CONFERENCE_NAME-1] of char;
  Id: Longint;
  From: TUserInfo;
  Subject: array [0..SIZE_MESSAGE_SUBJECT-1] of char;
end;

const SIZE_SYSTEMPAGE_LINES           = 3;
const SIZE_SYSTEMPAGE_TEXT            = 80;
type TSystemPageInstantMessage = record
  From: array [0..MAX_USER_NAME-1] of char;
  Text: array [0..SIZE_SYSTEMPAGE_LINES-1, 0..SIZE_SYSTEMPAGE_TEXT-1] of Char;
  InviteToChat: WordBool;
end;

type TWildcatService = record
  Name: array [0..SIZE_SERVICE_NAME-1] of char;
  Vendor: array [0..SIZE_SERVICE_NAME-1] of char;
  Version: Longint;
  Address: Longint;
  Port: Longint;
end;

type TConnectionInfo = record
  ConnectionId: Longint;
  Node: Longint;
  Time: Longint;
  IdleTime: Longint;
  Calls: Longint;
  WindowsUserName: array [0..80-1] of char;
  Computer: array [0..SIZE_COMPUTER_NAME-1] of char;
  IpAddress: Longint;
  ProgramName: array [0..MAX_PATH-1] of char;
  RefCount: Longint;
  User: TUserInfo;
  HandlesOpen: Longint;
  ChannelsOpen: Longint;
  CurrentTid: Longint;
  Reserved: array [0..100-1] of Byte;
end;

type TWildcatServerInfo = record
  TotalCalls: Longint;
  TotalUsers: Longint;
  TotalMessages: Longint;
  TotalFiles: Longint;
  MemoryUsage: Longint;
  MemoryLoad: Longint;
  LastMessageId: Longint;
  LastUserId: Longint;
  Reserved: array [0..92-1] of Byte;
end;

type PSecurityName = ^TSecurityName;
     TSecurityName = array [0..SIZE_SECURITY_NAME-1] of Char;


implementation


end.
