// File: Protocol.java
// (c) copyright 2002 Santronics Software Inc.
//
//****************************************************
// DO NOT EDIT THIS FILE!!!
// CPP2JAVA GENERATED FROM SOURCE FILE: wctype.h
//****************************************************
//

package COM.winserver.wildcat;

import java.io.IOException;

public class Protocol {
  public static final int pNone = 0;
  public static final int pAscii = 1;
  public static final int pXmodem = 2;
  public static final int pXmodemCRC = 3;
  public static final int pXmodem1K = 4;
  public static final int pXmodem1KG = 5;
  public static final int pYmodem = 6;
  public static final int pYmodemG = 7;
  public static final int pKermit = 8;
  public static final int pZmodem = 9;
  public static final int NumProtocols = 10;
}
