// File: TAddMessage_Response.java
// (c) copyright 2002 Santronics Software Inc.
//
//****************************************************
// DO NOT EDIT THIS FILE!!!
// CPP2JAVA GENERATED FROM SOURCE FILE: wcgui.h
//****************************************************
//

package COM.winserver.wildcat;

import java.io.IOException;

public class TAddMessage_Response extends TWildcatRequest {
  public int error;
  public int msgid;

  // Total size
  public static final int SIZE = TWildcatRequest.SIZE+4+4;

  // Constructors
  public TAddMessage_Response()
  {
  }

  public TAddMessage_Response(byte[] x)
  {
    fromByteArray(x);
  }

  // Methods
  protected void writeTo(WcOutputStream out) throws IOException
  {
    super.writeTo(out);
    out.writeInt(error);
    out.writeInt(msgid);
  }

  protected void readFrom(WcInputStream in) throws IOException
  {
    super.readFrom(in);
    error = in.readInt();
    msgid = in.readInt();
  }
}
