// File: TAddMessage_MessageText.java
// (c) copyright 2002 Santronics Software Inc.
//
//****************************************************
// DO NOT EDIT THIS FILE!!!
// CPP2JAVA GENERATED FROM SOURCE FILE: wcgui.h
//****************************************************
//

package COM.winserver.wildcat;

import java.io.IOException;

public class TAddMessage_MessageText extends TWildcatRequest {
  public int size;
  public String text;

  // Total size
  public static final int SIZE = TWildcatRequest.SIZE+2+1024;

  // Constructors
  public TAddMessage_MessageText()
  {
  }

  public TAddMessage_MessageText(byte[] x)
  {
    fromByteArray(x);
  }

  // Methods
  protected void writeTo(WcOutputStream out) throws IOException
  {
    super.writeTo(out);
    out.writeShort(size);
    out.writeString(text, 1024);
  }

  protected void readFrom(WcInputStream in) throws IOException
  {
    super.readFrom(in);
    size = in.readUnsignedShort();
    text = in.readString(1024);
  }
}
