// File: TChatMessage.java
// (c) copyright 2002 Santronics Software Inc.
//
//****************************************************
// DO NOT EDIT THIS FILE!!!
// CPP2JAVA GENERATED FROM SOURCE FILE: wctype.h
//****************************************************
//

package COM.winserver.wildcat;

import java.io.IOException;

public class TChatMessage extends WcRecord {
  public String From;
  public String Text;
  public int Whisper;

  // Total size
  public static final int SIZE = 0+28+256+1;

  // Constructors
  public TChatMessage()
  {
  }

  public TChatMessage(byte[] x)
  {
    fromByteArray(x);
  }

  // Methods
  protected void writeTo(WcOutputStream out) throws IOException
  {
    super.writeTo(out);
    out.writeString(From, 28);
    out.writeString(Text, 256);
    out.writeByte(Whisper);
  }

  protected void readFrom(WcInputStream in) throws IOException
  {
    super.readFrom(in);
    From = in.readString(28);
    Text = in.readString(256);
    Whisper = in.readUnsignedByte();
  }
}
