// File: TConferenceGroup.java
// (c) copyright 2002 Santronics Software Inc.
//
//****************************************************
// DO NOT EDIT THIS FILE!!!
// CPP2JAVA GENERATED FROM SOURCE FILE: wctype.h
//****************************************************
//

package COM.winserver.wildcat;

import java.io.IOException;

public class TConferenceGroup extends WcRecord {
  public int ObjectId;
  public int Number;
  public String Name;

  // Total size
  public static final int SIZE = 0+4+4+32+24*1;

  // Constructors
  public TConferenceGroup()
  {
  }

  public TConferenceGroup(byte[] x)
  {
    fromByteArray(x);
  }

  // Methods
  protected void writeTo(WcOutputStream out) throws IOException
  {
    super.writeTo(out);
    out.writeInt(ObjectId);
    out.writeInt(Number);
    out.writeString(Name, 32);
    out.write(new byte[24*1]);
  }

  protected void readFrom(WcInputStream in) throws IOException
  {
    super.readFrom(in);
    ObjectId = in.readInt();
    Number = in.readInt();
    Name = in.readString(32);
    in.skip(24*1);
  }
}
