// File: TConnectionInfo.java
// (c) copyright 2002 Santronics Software Inc.
//
//****************************************************
// DO NOT EDIT THIS FILE!!!
// CPP2JAVA GENERATED FROM SOURCE FILE: wctype.h
//****************************************************
//

package COM.winserver.wildcat;

import java.io.IOException;

public class TConnectionInfo extends WcRecord {
  public int ConnectionId;
  public int Node;
  public int Time;
  public int IdleTime;
  public int Calls;
  public String WindowsUserName;
  public String Computer;
  public int IpAddress;
  public String ProgramName;
  public int RefCount;
  public TUserInfo User;
  public int HandlesOpen;
  public int ChannelsOpen;
  public int CurrentTid;

  // Total size
  public static final int SIZE = 0+4+4+4+4+4+80+16+4+260+4+TUserInfo.SIZE+4+4+4+100*1;

  // Constructors
  public TConnectionInfo()
  {
  }

  public TConnectionInfo(byte[] x)
  {
    fromByteArray(x);
  }

  // Methods
  protected void writeTo(WcOutputStream out) throws IOException
  {
    super.writeTo(out);
    out.writeInt(ConnectionId);
    out.writeInt(Node);
    out.writeInt(Time);
    out.writeInt(IdleTime);
    out.writeInt(Calls);
    out.writeString(WindowsUserName, 80);
    out.writeString(Computer, 16);
    out.writeInt(IpAddress);
    out.writeString(ProgramName, 260);
    out.writeInt(RefCount);
    User.writeTo(out);
    out.writeInt(HandlesOpen);
    out.writeInt(ChannelsOpen);
    out.writeInt(CurrentTid);
    out.write(new byte[100*1]);
  }

  protected void readFrom(WcInputStream in) throws IOException
  {
    super.readFrom(in);
    ConnectionId = in.readInt();
    Node = in.readInt();
    Time = in.readInt();
    IdleTime = in.readInt();
    Calls = in.readInt();
    WindowsUserName = in.readString(80);
    Computer = in.readString(16);
    IpAddress = in.readInt();
    ProgramName = in.readString(260);
    RefCount = in.readInt();
    User = new TUserInfo(); User.readFrom(in);
    HandlesOpen = in.readInt();
    ChannelsOpen = in.readInt();
    CurrentTid = in.readInt();
    in.skip(100*1);
  }
}
