// File: TCopyBeforeDownload_Submit_Request.java
// (c) copyright 2002 Santronics Software Inc.
//
//****************************************************
// DO NOT EDIT THIS FILE!!!
// CPP2JAVA GENERATED FROM SOURCE FILE: wcgui.h
//****************************************************
//

package COM.winserver.wildcat;

import java.io.IOException;

public class TCopyBeforeDownload_Submit_Request extends TWildcatRequest {
  public int id;
  public int area;
  public String fn;

  // Total size
  public static final int SIZE = TWildcatRequest.SIZE+4+4+16;

  // Constructors
  public TCopyBeforeDownload_Submit_Request()
  {
    type = WildcatRequest.wrCopyBeforeDownload;
  }

  public TCopyBeforeDownload_Submit_Request(byte[] x)
  {
    fromByteArray(x);
  }

  // Methods
  protected void writeTo(WcOutputStream out) throws IOException
  {
    super.writeTo(out);
    out.writeInt(id);
    out.writeInt(area);
    out.writeString(fn, 16);
  }

  protected void readFrom(WcInputStream in) throws IOException
  {
    super.readFrom(in);
    id = in.readInt();
    area = in.readInt();
    fn = in.readString(16);
  }
}
