// File: TCopyBeforeDownload_Status_Response.java
// (c) copyright 2002 Santronics Software Inc.
//
//****************************************************
// DO NOT EDIT THIS FILE!!!
// CPP2JAVA GENERATED FROM SOURCE FILE: wcgui.h
//****************************************************
//

package COM.winserver.wildcat;

import java.io.IOException;

public class TCopyBeforeDownload_Status_Response extends TWildcatRequest {
  public int id;
  public int result;
  public int cookie;

  // Total size
  public static final int SIZE = TWildcatRequest.SIZE+4+4+4;

  // Constructors
  public TCopyBeforeDownload_Status_Response()
  {
  }

  public TCopyBeforeDownload_Status_Response(byte[] x)
  {
    fromByteArray(x);
  }

  // Methods
  protected void writeTo(WcOutputStream out) throws IOException
  {
    super.writeTo(out);
    out.writeInt(id);
    out.writeInt(result);
    out.writeInt(cookie);
  }

  protected void readFrom(WcInputStream in) throws IOException
  {
    super.readFrom(in);
    id = in.readInt();
    result = in.readInt();
    cookie = in.readInt();
  }
}
