// File: TDeleteMessage_Request.java
// (c) copyright 2002 Santronics Software Inc.
//
//****************************************************
// DO NOT EDIT THIS FILE!!!
// CPP2JAVA GENERATED FROM SOURCE FILE: wcgui.h
//****************************************************
//

package COM.winserver.wildcat;

import java.io.IOException;

public class TDeleteMessage_Request extends TWildcatRequest {
  public int conference;
  public int msgid;

  // Total size
  public static final int SIZE = TWildcatRequest.SIZE+4+4;

  // Constructors
  public TDeleteMessage_Request()
  {
    type = WildcatRequest.wrDeleteMessage;
  }

  public TDeleteMessage_Request(byte[] x)
  {
    fromByteArray(x);
  }

  // Methods
  protected void writeTo(WcOutputStream out) throws IOException
  {
    super.writeTo(out);
    out.writeInt(conference);
    out.writeInt(msgid);
  }

  protected void readFrom(WcInputStream in) throws IOException
  {
    super.readFrom(in);
    conference = in.readInt();
    msgid = in.readInt();
  }
}
