// File: TDeleteFile_Response.java
// (c) copyright 2002 Santronics Software Inc.
//
//****************************************************
// DO NOT EDIT THIS FILE!!!
// CPP2JAVA GENERATED FROM SOURCE FILE: wcgui.h
//****************************************************
//

package COM.winserver.wildcat;

import java.io.IOException;

public class TDeleteFile_Response extends TWildcatRequest {
  public int error;

  // Total size
  public static final int SIZE = TWildcatRequest.SIZE+4;

  // Constructors
  public TDeleteFile_Response()
  {
  }

  public TDeleteFile_Response(byte[] x)
  {
    fromByteArray(x);
  }

  // Methods
  protected void writeTo(WcOutputStream out) throws IOException
  {
    super.writeTo(out);
    out.writeInt(error);
  }

  protected void readFrom(WcInputStream in) throws IOException
  {
    super.readFrom(in);
    error = in.readInt();
  }
}
