// File: TDeleteFile_Request.java
// (c) copyright 2002 Santronics Software Inc.
//
//****************************************************
// DO NOT EDIT THIS FILE!!!
// CPP2JAVA GENERATED FROM SOURCE FILE: wcgui.h
//****************************************************
//

package COM.winserver.wildcat;

import java.io.IOException;

public class TDeleteFile_Request extends TWildcatRequest {
  public String filename;
  public int area;
  public int disktoo;

  // Total size
  public static final int SIZE = TWildcatRequest.SIZE+16+4+4;

  // Constructors
  public TDeleteFile_Request()
  {
    type = WildcatRequest.wrDeleteFile;
  }

  public TDeleteFile_Request(byte[] x)
  {
    fromByteArray(x);
  }

  // Methods
  protected void writeTo(WcOutputStream out) throws IOException
  {
    super.writeTo(out);
    out.writeString(filename, 16);
    out.writeInt(area);
    out.writeInt(disktoo);
  }

  protected void readFrom(WcInputStream in) throws IOException
  {
    super.readFrom(in);
    filename = in.readString(16);
    area = in.readInt();
    disktoo = in.readInt();
  }
}
