// File: TDoorInfo.java
// (c) copyright 2002 Santronics Software Inc.
//
//****************************************************
// DO NOT EDIT THIS FILE!!!
// CPP2JAVA GENERATED FROM SOURCE FILE: wctype.h
//****************************************************
//

package COM.winserver.wildcat;

import java.io.IOException;

public class TDoorInfo extends WcRecord {
  public int ObjectId;
  public String Name;
  public String Batch;
  public String Display;
  public int DoorMenuIndex;
  public boolean MultiUser;
  public boolean SmallDoorSys;
  public int DoorType;

  // Total size
  public static final int SIZE = 0+4+40+16+16+4+4+4+4+36*1;

  // Constructors
  public TDoorInfo()
  {
  }

  public TDoorInfo(byte[] x)
  {
    fromByteArray(x);
  }

  // Methods
  protected void writeTo(WcOutputStream out) throws IOException
  {
    super.writeTo(out);
    out.writeInt(ObjectId);
    out.writeString(Name, 40);
    out.writeString(Batch, 16);
    out.writeString(Display, 16);
    out.writeInt(DoorMenuIndex);
    out.writeBoolean(MultiUser);
    out.writeBoolean(SmallDoorSys);
    out.writeInt(DoorType);
    out.write(new byte[36*1]);
  }

  protected void readFrom(WcInputStream in) throws IOException
  {
    super.readFrom(in);
    ObjectId = in.readInt();
    Name = in.readString(40);
    Batch = in.readString(16);
    Display = in.readString(16);
    DoorMenuIndex = in.readInt();
    MultiUser = in.readBoolean();
    SmallDoorSys = in.readBoolean();
    DoorType = in.readInt();
    in.skip(36*1);
  }
}
