// File: TDownloadFile_Request.java
// (c) copyright 2002 Santronics Software Inc.
//
//****************************************************
// DO NOT EDIT THIS FILE!!!
// CPP2JAVA GENERATED FROM SOURCE FILE: wcgui.h
//****************************************************
//

package COM.winserver.wildcat;

import java.io.IOException;

public class TDownloadFile_Request extends TWildcatRequest {
  public String filename;
  public int have;
  public int crc;

  // Total size
  public static final int SIZE = TWildcatRequest.SIZE+260+4+4;

  // Constructors
  public TDownloadFile_Request()
  {
    type = WildcatRequest.wrDownloadFile;
  }

  public TDownloadFile_Request(byte[] x)
  {
    fromByteArray(x);
  }

  // Methods
  protected void writeTo(WcOutputStream out) throws IOException
  {
    super.writeTo(out);
    out.writeString(filename, 260);
    out.writeInt(have);
    out.writeInt(crc);
  }

  protected void readFrom(WcInputStream in) throws IOException
  {
    super.readFrom(in);
    filename = in.readString(260);
    have = in.readInt();
    crc = in.readInt();
  }
}
