// File: TFidoAddress.java
// (c) copyright 2002 Santronics Software Inc.
//
//****************************************************
// DO NOT EDIT THIS FILE!!!
// CPP2JAVA GENERATED FROM SOURCE FILE: wctype.h
//****************************************************
//

package COM.winserver.wildcat;

import java.io.IOException;

public class TFidoAddress extends WcRecord {
  public int Zone;
  public int Net;
  public int Node;
  public int Point;

  // Total size
  public static final int SIZE = 0+2+2+2+2;

  // Constructors
  public TFidoAddress()
  {
  }

  public TFidoAddress(byte[] x)
  {
    fromByteArray(x);
  }

  // Methods
  protected void writeTo(WcOutputStream out) throws IOException
  {
    super.writeTo(out);
    out.writeShort(Zone);
    out.writeShort(Net);
    out.writeShort(Node);
    out.writeShort(Point);
  }

  protected void readFrom(WcInputStream in) throws IOException
  {
    super.readFrom(in);
    Zone = in.readUnsignedShort();
    Net = in.readUnsignedShort();
    Node = in.readUnsignedShort();
    Point = in.readUnsignedShort();
  }
}
