// File: TFileArea.java
// (c) copyright 2002 Santronics Software Inc.
//
//****************************************************
// DO NOT EDIT THIS FILE!!!
// CPP2JAVA GENERATED FROM SOURCE FILE: wctype.h
//****************************************************
//

package COM.winserver.wildcat;

import java.io.IOException;

public class TFileArea extends WcRecord {
  public int ObjectId;
  public int Number;
  public String Name;
  public boolean ExcludeFromNewFiles;
  public boolean PromptForPasswordProtect;
  public String FtpDirectoryName;
  public int Options;

  // Total size
  public static final int SIZE = 0+4+4+32+4+4+32+4;

  // Constructors
  public TFileArea()
  {
  }

  public TFileArea(byte[] x)
  {
    fromByteArray(x);
  }

  // Methods
  protected void writeTo(WcOutputStream out) throws IOException
  {
    super.writeTo(out);
    out.writeInt(ObjectId);
    out.writeInt(Number);
    out.writeString(Name, 32);
    out.writeBoolean(ExcludeFromNewFiles);
    out.writeBoolean(PromptForPasswordProtect);
    out.writeString(FtpDirectoryName, 32);
    out.writeInt(Options);
  }

  protected void readFrom(WcInputStream in) throws IOException
  {
    super.readFrom(in);
    ObjectId = in.readInt();
    Number = in.readInt();
    Name = in.readString(32);
    ExcludeFromNewFiles = in.readBoolean();
    PromptForPasswordProtect = in.readBoolean();
    FtpDirectoryName = in.readString(32);
    Options = in.readInt();
  }
}
