// File: TFileRequest.java
// (c) copyright 2002 Santronics Software Inc.
//
//****************************************************
// DO NOT EDIT THIS FILE!!!
// CPP2JAVA GENERATED FROM SOURCE FILE: wcgui.h
//****************************************************
//

package COM.winserver.wildcat;

import java.io.IOException;

public class TFileRequest extends WcRecord {
  public TUserInfo User;
  public long RequestTime;
  public String FileName;
  public int FileArea;

  // Total size
  public static final int SIZE = 0+TUserInfo.SIZE+8+16+4+100;

  // Constructors
  public TFileRequest()
  {
  }

  public TFileRequest(byte[] x)
  {
    fromByteArray(x);
  }

  // Methods
  protected void writeTo(WcOutputStream out) throws IOException
  {
    super.writeTo(out);
    User.writeTo(out);
    out.writeLong(RequestTime);
    out.writeString(FileName, 16);
    out.writeInt(FileArea);
    out.write(new byte[100]);
  }

  protected void readFrom(WcInputStream in) throws IOException
  {
    super.readFrom(in);
    User = new TUserInfo(); User.readFrom(in);
    RequestTime = in.readLong();
    FileName = in.readString(16);
    FileArea = in.readInt();
    in.skip(100);
  }
}
