// File: TGetDownloadStats_Response.java
// (c) copyright 2002 Santronics Software Inc.
//
//****************************************************
// DO NOT EDIT THIS FILE!!!
// CPP2JAVA GENERATED FROM SOURCE FILE: wcgui.h
//****************************************************
//

package COM.winserver.wildcat;

import java.io.IOException;

public class TGetDownloadStats_Response extends TWildcatRequest {
  public int Uploads;
  public int TotalUploadKbytes;
  public int Downloads;
  public int TotalDownloadKbytes;
  public int DownloadCountToday;
  public int DownloadKbytesToday;

  // Total size
  public static final int SIZE = TWildcatRequest.SIZE+4+4+4+4+4+4;

  // Constructors
  public TGetDownloadStats_Response()
  {
  }

  public TGetDownloadStats_Response(byte[] x)
  {
    fromByteArray(x);
  }

  // Methods
  protected void writeTo(WcOutputStream out) throws IOException
  {
    super.writeTo(out);
    out.writeInt(Uploads);
    out.writeInt(TotalUploadKbytes);
    out.writeInt(Downloads);
    out.writeInt(TotalDownloadKbytes);
    out.writeInt(DownloadCountToday);
    out.writeInt(DownloadKbytesToday);
  }

  protected void readFrom(WcInputStream in) throws IOException
  {
    super.readFrom(in);
    Uploads = in.readInt();
    TotalUploadKbytes = in.readInt();
    Downloads = in.readInt();
    TotalDownloadKbytes = in.readInt();
    DownloadCountToday = in.readInt();
    DownloadKbytesToday = in.readInt();
  }
}
