// File: TGetFileGroupAreas_Response.java
// (c) copyright 2002 Santronics Software Inc.
//
//****************************************************
// DO NOT EDIT THIS FILE!!!
// CPP2JAVA GENERATED FROM SOURCE FILE: wcgui.h
//****************************************************
//

package COM.winserver.wildcat;

import java.io.IOException;

public class TGetFileGroupAreas_Response extends TWildcatRequest {
  public int start;
  public int runlength;

  // Total size
  public static final int SIZE = TWildcatRequest.SIZE+2+2;

  // Constructors
  public TGetFileGroupAreas_Response()
  {
  }

  public TGetFileGroupAreas_Response(byte[] x)
  {
    fromByteArray(x);
  }

  // Methods
  protected void writeTo(WcOutputStream out) throws IOException
  {
    super.writeTo(out);
    out.writeShort(start);
    out.writeShort(runlength);
  }

  protected void readFrom(WcInputStream in) throws IOException
  {
    super.readFrom(in);
    start = in.readUnsignedShort();
    runlength = in.readUnsignedShort();
  }
}
