// File: TGetFileAreas_Response.java
// (c) copyright 2002 Santronics Software Inc.
//
//****************************************************
// DO NOT EDIT THIS FILE!!!
// CPP2JAVA GENERATED FROM SOURCE FILE: wcgui.h
//****************************************************
//

package COM.winserver.wildcat;

import java.io.IOException;

public class TGetFileAreas_Response extends TWildcatRequest {
  public TFileArea fa;
  public int Access;

  // Total size
  public static final int SIZE = TWildcatRequest.SIZE+TFileArea.SIZE+4;

  // Constructors
  public TGetFileAreas_Response()
  {
  }

  public TGetFileAreas_Response(byte[] x)
  {
    fromByteArray(x);
  }

  // Methods
  protected void writeTo(WcOutputStream out) throws IOException
  {
    super.writeTo(out);
    fa.writeTo(out);
    out.writeInt(Access);
  }

  protected void readFrom(WcInputStream in) throws IOException
  {
    super.readFrom(in);
    fa = new TFileArea(); fa.readFrom(in);
    Access = in.readInt();
  }
}
