// File: TGetPackageVersion_Response.java
// (c) copyright 2002 Santronics Software Inc.
//
//****************************************************
// DO NOT EDIT THIS FILE!!!
// CPP2JAVA GENERATED FROM SOURCE FILE: wcgui.h
//****************************************************
//

package COM.winserver.wildcat;

import java.io.IOException;

public class TGetPackageVersion_Response extends TWildcatRequest {
  public int error;
  public String PackageName;
  public String ShortPackageName;
  public String PackageVersion;
  public String PackageInfoFilename;
  public int UpgradeVersion;
  public int PatchAvailable;
  public String UpgradeFilename;

  // Total size
  public static final int SIZE = TWildcatRequest.SIZE+4+64+16+10+260+4+4+260;

  // Constructors
  public TGetPackageVersion_Response()
  {
  }

  public TGetPackageVersion_Response(byte[] x)
  {
    fromByteArray(x);
  }

  // Methods
  protected void writeTo(WcOutputStream out) throws IOException
  {
    super.writeTo(out);
    out.writeInt(error);
    out.writeString(PackageName, 64);
    out.writeString(ShortPackageName, 16);
    out.writeString(PackageVersion, 10);
    out.writeString(PackageInfoFilename, 260);
    out.writeInt(UpgradeVersion);
    out.writeInt(PatchAvailable);
    out.writeString(UpgradeFilename, 260);
  }

  protected void readFrom(WcInputStream in) throws IOException
  {
    super.readFrom(in);
    error = in.readInt();
    PackageName = in.readString(64);
    ShortPackageName = in.readString(16);
    PackageVersion = in.readString(10);
    PackageInfoFilename = in.readString(260);
    UpgradeVersion = in.readInt();
    PatchAvailable = in.readInt();
    UpgradeFilename = in.readString(260);
  }
}
