// File: TGetFileDescription_Response.java
// (c) copyright 2002 Santronics Software Inc.
//
//****************************************************
// DO NOT EDIT THIS FILE!!!
// CPP2JAVA GENERATED FROM SOURCE FILE: wcgui.h
//****************************************************
//

package COM.winserver.wildcat;

import java.io.IOException;

public class TGetFileDescription_Response extends TWildcatRequest {
  public int len;
  public String text;

  // Total size
  public static final int SIZE = TWildcatRequest.SIZE+2+MAX_FILE_LONGDESC_LINES*SIZE_FILE_LONGDESC;

  // Constructors
  public TGetFileDescription_Response()
  {
  }

  public TGetFileDescription_Response(byte[] x)
  {
    fromByteArray(x);
  }

  // Methods
  protected void writeTo(WcOutputStream out) throws IOException
  {
    super.writeTo(out);
    out.writeShort(len);
    out.writeString(text, MAX_FILE_LONGDESC_LINES*SIZE_FILE_LONGDESC);
  }

  protected void readFrom(WcInputStream in) throws IOException
  {
    super.readFrom(in);
    len = in.readUnsignedShort();
    text = in.readString(MAX_FILE_LONGDESC_LINES*SIZE_FILE_LONGDESC);
  }
}
