// File: TGetServiceByName_Response.java
// (c) copyright 2002 Santronics Software Inc.
//
//****************************************************
// DO NOT EDIT THIS FILE!!!
// CPP2JAVA GENERATED FROM SOURCE FILE: wcgui.h
//****************************************************
//

package COM.winserver.wildcat;

import java.io.IOException;

public class TGetServiceByName_Response extends TWildcatRequest {
  public TWildcatService info;

  // Total size
  public static final int SIZE = TWildcatRequest.SIZE+TWildcatService.SIZE;

  // Constructors
  public TGetServiceByName_Response()
  {
  }

  public TGetServiceByName_Response(byte[] x)
  {
    fromByteArray(x);
  }

  // Methods
  protected void writeTo(WcOutputStream out) throws IOException
  {
    super.writeTo(out);
    info.writeTo(out);
  }

  protected void readFrom(WcInputStream in) throws IOException
  {
    super.readFrom(in);
    info = new TWildcatService(); info.readFrom(in);
  }
}
