// File: TGetConferenceGroups_Response.java
// (c) copyright 2002 Santronics Software Inc.
//
//****************************************************
// DO NOT EDIT THIS FILE!!!
// CPP2JAVA GENERATED FROM SOURCE FILE: wcgui.h
//****************************************************
//

package COM.winserver.wildcat;

import java.io.IOException;

public class TGetConferenceGroups_Response extends TWildcatRequest {
  public TConferenceGroup cg;

  // Total size
  public static final int SIZE = TWildcatRequest.SIZE+TConferenceGroup.SIZE;

  // Constructors
  public TGetConferenceGroups_Response()
  {
  }

  public TGetConferenceGroups_Response(byte[] x)
  {
    fromByteArray(x);
  }

  // Methods
  protected void writeTo(WcOutputStream out) throws IOException
  {
    super.writeTo(out);
    cg.writeTo(out);
  }

  protected void readFrom(WcInputStream in) throws IOException
  {
    super.readFrom(in);
    cg = new TConferenceGroup(); cg.readFrom(in);
  }
}
