// File: TGetVolatileConfInfo_SetConfs.java
// (c) copyright 2002 Santronics Software Inc.
//
//****************************************************
// DO NOT EDIT THIS FILE!!!
// CPP2JAVA GENERATED FROM SOURCE FILE: wcgui.h
//****************************************************
//

package COM.winserver.wildcat;

import java.io.IOException;

public class TGetVolatileConfInfo_SetConfs extends TWildcatRequest {
  public int start;
  public int count;

  // Total size
  public static final int SIZE = TWildcatRequest.SIZE+4+4;

  // Constructors
  public TGetVolatileConfInfo_SetConfs()
  {
  }

  public TGetVolatileConfInfo_SetConfs(byte[] x)
  {
    fromByteArray(x);
  }

  // Methods
  protected void writeTo(WcOutputStream out) throws IOException
  {
    super.writeTo(out);
    out.writeInt(start);
    out.writeInt(count);
  }

  protected void readFrom(WcInputStream in) throws IOException
  {
    super.readFrom(in);
    start = in.readInt();
    count = in.readInt();
  }
}
