// File: TGetFileDescription_Request.java
// (c) copyright 2002 Santronics Software Inc.
//
//****************************************************
// DO NOT EDIT THIS FILE!!!
// CPP2JAVA GENERATED FROM SOURCE FILE: wcgui.h
//****************************************************
//

package COM.winserver.wildcat;

import java.io.IOException;

public class TGetFileDescription_Request extends TWildcatRequest {
  public int area;
  public String name;

  // Total size
  public static final int SIZE = TWildcatRequest.SIZE+2+16;

  // Constructors
  public TGetFileDescription_Request()
  {
    type = WildcatRequest.wrGetFileDescription;
  }

  public TGetFileDescription_Request(byte[] x)
  {
    fromByteArray(x);
  }

  // Methods
  protected void writeTo(WcOutputStream out) throws IOException
  {
    super.writeTo(out);
    out.writeShort(area);
    out.writeString(name, 16);
  }

  protected void readFrom(WcInputStream in) throws IOException
  {
    super.readFrom(in);
    area = in.readUnsignedShort();
    name = in.readString(16);
  }
}
