// File: TGetObjectInfo_Request.java
// (c) copyright 2002 Santronics Software Inc.
//
//****************************************************
// DO NOT EDIT THIS FILE!!!
// CPP2JAVA GENERATED FROM SOURCE FILE: wcgui.h
//****************************************************
//

package COM.winserver.wildcat;

import java.io.IOException;

public class TGetObjectInfo_Request extends TWildcatRequest {
  public int ObjectId;
  public int ObjectClass;
  public String ObjectName;

  // Total size
  public static final int SIZE = TWildcatRequest.SIZE+4+4+260;

  // Constructors
  public TGetObjectInfo_Request()
  {
    type = WildcatRequest.wrGetObjectInfo;
  }

  public TGetObjectInfo_Request(byte[] x)
  {
    fromByteArray(x);
  }

  // Methods
  protected void writeTo(WcOutputStream out) throws IOException
  {
    super.writeTo(out);
    out.writeInt(ObjectId);
    out.writeInt(ObjectClass);
    out.writeString(ObjectName, 260);
  }

  protected void readFrom(WcInputStream in) throws IOException
  {
    super.readFrom(in);
    ObjectId = in.readInt();
    ObjectClass = in.readInt();
    ObjectName = in.readString(260);
  }
}
