// File: TGetObjectFlagsByName_Request.java
// (c) copyright 2002 Santronics Software Inc.
//
//****************************************************
// DO NOT EDIT THIS FILE!!!
// CPP2JAVA GENERATED FROM SOURCE FILE: wcgui.h
//****************************************************
//

package COM.winserver.wildcat;

import java.io.IOException;

public class TGetObjectFlagsByName_Request extends TWildcatRequest {
  public String ObjectName;

  // Total size
  public static final int SIZE = TWildcatRequest.SIZE+260;

  // Constructors
  public TGetObjectFlagsByName_Request()
  {
    type = WildcatRequest.wrGetObjectFlagsByName;
  }

  public TGetObjectFlagsByName_Request(byte[] x)
  {
    fromByteArray(x);
  }

  // Methods
  protected void writeTo(WcOutputStream out) throws IOException
  {
    super.writeTo(out);
    out.writeString(ObjectName, 260);
  }

  protected void readFrom(WcInputStream in) throws IOException
  {
    super.readFrom(in);
    ObjectName = in.readString(260);
  }
}
