// File: TGetUserInfo_Request.java
// (c) copyright 2002 Santronics Software Inc.
//
//****************************************************
// DO NOT EDIT THIS FILE!!!
// CPP2JAVA GENERATED FROM SOURCE FILE: wcgui.h
//****************************************************
//

package COM.winserver.wildcat;

import java.io.IOException;

public class TGetUserInfo_Request extends TWildcatRequest {
  public String UserName;
  public int UserId;

  // Total size
  public static final int SIZE = TWildcatRequest.SIZE+72+4;

  // Constructors
  public TGetUserInfo_Request()
  {
    type = WildcatRequest.wrGetUserInfo;
  }

  public TGetUserInfo_Request(byte[] x)
  {
    fromByteArray(x);
  }

  // Methods
  protected void writeTo(WcOutputStream out) throws IOException
  {
    super.writeTo(out);
    out.writeString(UserName, 72);
    out.writeInt(UserId);
  }

  protected void readFrom(WcInputStream in) throws IOException
  {
    super.readFrom(in);
    UserName = in.readString(72);
    UserId = in.readInt();
  }
}
