// File: TGetPackageVersion_Request.java
// (c) copyright 2002 Santronics Software Inc.
//
//****************************************************
// DO NOT EDIT THIS FILE!!!
// CPP2JAVA GENERATED FROM SOURCE FILE: wcgui.h
//****************************************************
//

package COM.winserver.wildcat;

import java.io.IOException;

public class TGetPackageVersion_Request extends TWildcatRequest {
  public String PackageName;
  public String PackageVersion;

  // Total size
  public static final int SIZE = TWildcatRequest.SIZE+64+10;

  // Constructors
  public TGetPackageVersion_Request()
  {
    type = WildcatRequest.wrGetPackageVersion;
  }

  public TGetPackageVersion_Request(byte[] x)
  {
    fromByteArray(x);
  }

  // Methods
  protected void writeTo(WcOutputStream out) throws IOException
  {
    super.writeTo(out);
    out.writeString(PackageName, 64);
    out.writeString(PackageVersion, 10);
  }

  protected void readFrom(WcInputStream in) throws IOException
  {
    super.readFrom(in);
    PackageName = in.readString(64);
    PackageVersion = in.readString(10);
  }
}
