// File: TGuiChannelMessage.java
// (c) copyright 2002 Santronics Software Inc.
//
//****************************************************
// DO NOT EDIT THIS FILE!!!
// CPP2JAVA GENERATED FROM SOURCE FILE: wcgui.h
//****************************************************
//

package COM.winserver.wildcat;

import java.io.IOException;

public class TGuiChannelMessage extends WcRecord {
  public int DestId;
  public int UserData;
  public int DataSize;
  public byte[] Data;

  // Total size
  public static final int SIZE = 0+4+2+2+500;

  // Constructors
  public TGuiChannelMessage()
  {
  }

  public TGuiChannelMessage(byte[] x)
  {
    fromByteArray(x);
  }

  // Methods
  protected void writeTo(WcOutputStream out) throws IOException
  {
    super.writeTo(out);
    out.writeInt(DestId);
    out.writeShort(UserData);
    out.writeShort(DataSize);
    out.write(Data);
  }

  protected void readFrom(WcInputStream in) throws IOException
  {
    super.readFrom(in);
    DestId = in.readInt();
    UserData = in.readUnsignedShort();
    DataSize = in.readUnsignedShort();
    Data = new byte[500]; in.read(Data);
  }
}
