// File: TListFilesEx_Response.java
// (c) copyright 2002 Santronics Software Inc.
//
//****************************************************
// DO NOT EDIT THIS FILE!!!
// CPP2JAVA GENERATED FROM SOURCE FILE: wcgui.h
//****************************************************
//

package COM.winserver.wildcat;

import java.io.IOException;

public class TListFilesEx_Response extends TWildcatRequest {
  public int Area;
  public String Name;
  public String Description;
  public int UploaderId;
  public String UploaderName;
  public String Password;
  public int Size;
  public long FileTime;
  public long PostTime;
  public long LastAccessed;
  public int Flags;
  public int Downloads;
  public int Cost;
  public int LongDesc;

  // Total size
  public static final int SIZE = TWildcatRequest.SIZE+4+MAX_PATH+76+4+72+32+4+8+8+8+4+4+4+2;

  // Constructors
  public TListFilesEx_Response()
  {
  }

  public TListFilesEx_Response(byte[] x)
  {
    fromByteArray(x);
  }

  // Methods
  protected void writeTo(WcOutputStream out) throws IOException
  {
    super.writeTo(out);
    out.writeInt(Area);
    out.writeString(Name, MAX_PATH);
    out.writeString(Description, 76);
    out.writeInt(UploaderId);
    out.writeString(UploaderName, 72);
    out.writeString(Password, 32);
    out.writeInt(Size);
    out.writeLong(FileTime);
    out.writeLong(PostTime);
    out.writeLong(LastAccessed);
    out.writeInt(Flags);
    out.writeInt(Downloads);
    out.writeInt(Cost);
    out.writeShort(LongDesc);
  }

  protected void readFrom(WcInputStream in) throws IOException
  {
    super.readFrom(in);
    Area = in.readInt();
    Name = in.readString(MAX_PATH);
    Description = in.readString(76);
    UploaderId = in.readInt();
    UploaderName = in.readString(72);
    Password = in.readString(32);
    Size = in.readInt();
    FileTime = in.readLong();
    PostTime = in.readLong();
    LastAccessed = in.readLong();
    Flags = in.readInt();
    Downloads = in.readInt();
    Cost = in.readInt();
    LongDesc = in.readUnsignedShort();
  }
}
