// File: TListMessagesByAreaDate_Request.java
// (c) copyright 2002 Santronics Software Inc.
//
//****************************************************
// DO NOT EDIT THIS FILE!!!
// CPP2JAVA GENERATED FROM SOURCE FILE: wcgui.h
//****************************************************
//

package COM.winserver.wildcat;

import java.io.IOException;

public class TListMessagesByAreaDate_Request extends TWildcatRequest {
  public int conference;
  public long postedtime;
  public int count;
  public int flags;

  // Total size
  public static final int SIZE = TWildcatRequest.SIZE+4+8+4+2;

  // Constructors
  public TListMessagesByAreaDate_Request()
  {
    type = WildcatRequest.wrListMessagesByAreaDate;
  }

  public TListMessagesByAreaDate_Request(byte[] x)
  {
    fromByteArray(x);
  }

  // Methods
  protected void writeTo(WcOutputStream out) throws IOException
  {
    super.writeTo(out);
    out.writeInt(conference);
    out.writeLong(postedtime);
    out.writeInt(count);
    out.writeShort(flags);
  }

  protected void readFrom(WcInputStream in) throws IOException
  {
    super.readFrom(in);
    conference = in.readInt();
    postedtime = in.readLong();
    count = in.readInt();
    flags = in.readUnsignedShort();
  }
}
