// File: TListMessages_MsgText_Response.java
// (c) copyright 2002 Santronics Software Inc.
//
//****************************************************
// DO NOT EDIT THIS FILE!!!
// CPP2JAVA GENERATED FROM SOURCE FILE: wcgui.h
//****************************************************
//

package COM.winserver.wildcat;

import java.io.IOException;

public class TListMessages_MsgText_Response extends TWildcatRequest {
  public int len;
  public String text;

  // Total size
  public static final int SIZE = TWildcatRequest.SIZE+2+1024;

  // Constructors
  public TListMessages_MsgText_Response()
  {
  }

  public TListMessages_MsgText_Response(byte[] x)
  {
    fromByteArray(x);
  }

  // Methods
  protected void writeTo(WcOutputStream out) throws IOException
  {
    super.writeTo(out);
    out.writeShort(len);
    out.writeString(text, 1024);
  }

  protected void readFrom(WcInputStream in) throws IOException
  {
    super.readFrom(in);
    len = in.readUnsignedShort();
    text = in.readString(1024);
  }
}
