// File: TListMessages_GetMore.java
// (c) copyright 2002 Santronics Software Inc.
//
//****************************************************
// DO NOT EDIT THIS FILE!!!
// CPP2JAVA GENERATED FROM SOURCE FILE: wcgui.h
//****************************************************
//

package COM.winserver.wildcat;

import java.io.IOException;

public class TListMessages_GetMore extends TWildcatRequest {
  public int count;

  // Total size
  public static final int SIZE = TWildcatRequest.SIZE+4;

  // Constructors
  public TListMessages_GetMore()
  {
  }

  public TListMessages_GetMore(byte[] x)
  {
    fromByteArray(x);
  }

  // Methods
  protected void writeTo(WcOutputStream out) throws IOException
  {
    super.writeTo(out);
    out.writeInt(count);
  }

  protected void readFrom(WcInputStream in) throws IOException
  {
    super.readFrom(in);
    count = in.readInt();
  }
}
