// File: TListFilesByDate_Request.java
// (c) copyright 2002 Santronics Software Inc.
//
//****************************************************
// DO NOT EDIT THIS FILE!!!
// CPP2JAVA GENERATED FROM SOURCE FILE: wcgui.h
//****************************************************
//

package COM.winserver.wildcat;

import java.io.IOException;

public class TListFilesByDate_Request extends TListFiles_Request {
  public long startdate;

  // Total size
  public static final int SIZE = TListFiles_Request.SIZE+8;

  // Constructors
  public TListFilesByDate_Request()
  {
    type = WildcatRequest.wrListFilesByDate;
  }

  public TListFilesByDate_Request(byte[] x)
  {
    fromByteArray(x);
  }

  // Methods
  protected void writeTo(WcOutputStream out) throws IOException
  {
    super.writeTo(out);
    out.writeLong(startdate);
  }

  protected void readFrom(WcInputStream in) throws IOException
  {
    super.readFrom(in);
    startdate = in.readLong();
  }
}
