// File: TListMessages_MsgHeader_Response.java
// (c) copyright 2002 Santronics Software Inc.
//
//****************************************************
// DO NOT EDIT THIS FILE!!!
// CPP2JAVA GENERATED FROM SOURCE FILE: wcgui.h
//****************************************************
//

package COM.winserver.wildcat;

import java.io.IOException;

public class TListMessages_MsgHeader_Response extends TWildcatRequest {
  public TGuiMsgHeader mh;

  // Total size
  public static final int SIZE = TWildcatRequest.SIZE+TGuiMsgHeader.SIZE;

  // Constructors
  public TListMessages_MsgHeader_Response()
  {
  }

  public TListMessages_MsgHeader_Response(byte[] x)
  {
    fromByteArray(x);
  }

  // Methods
  protected void writeTo(WcOutputStream out) throws IOException
  {
    super.writeTo(out);
    mh.writeTo(out);
  }

  protected void readFrom(WcInputStream in) throws IOException
  {
    super.readFrom(in);
    mh = new TGuiMsgHeader(); mh.readFrom(in);
  }
}
