// File: TListFilesBySearch_Request.java
// (c) copyright 2002 Santronics Software Inc.
//
//****************************************************
// DO NOT EDIT THIS FILE!!!
// CPP2JAVA GENERATED FROM SOURCE FILE: wcgui.h
//****************************************************
//

package COM.winserver.wildcat;

import java.io.IOException;

public class TListFilesBySearch_Request extends TListFiles_Request {
  public String Target;

  // Total size
  public static final int SIZE = TListFiles_Request.SIZE+80;

  // Constructors
  public TListFilesBySearch_Request()
  {
    type = WildcatRequest.wrListFilesBySearch;
  }

  public TListFilesBySearch_Request(byte[] x)
  {
    fromByteArray(x);
  }

  // Methods
  protected void writeTo(WcOutputStream out) throws IOException
  {
    super.writeTo(out);
    out.writeString(Target, 80);
  }

  protected void readFrom(WcInputStream in) throws IOException
  {
    super.readFrom(in);
    Target = in.readString(80);
  }
}
