// File: TListConferencesByName_Request.java
// (c) copyright 2002 Santronics Software Inc.
//
//****************************************************
// DO NOT EDIT THIS FILE!!!
// CPP2JAVA GENERATED FROM SOURCE FILE: wcgui.h
//****************************************************
//

package COM.winserver.wildcat;

import java.io.IOException;

public class TListConferencesByName_Request extends TWildcatRequest {
  public String name;
  public int count;

  // Total size
  public static final int SIZE = TWildcatRequest.SIZE+60+4;

  // Constructors
  public TListConferencesByName_Request()
  {
    type = WildcatRequest.wrListConferencesByName;
  }

  public TListConferencesByName_Request(byte[] x)
  {
    fromByteArray(x);
  }

  // Methods
  protected void writeTo(WcOutputStream out) throws IOException
  {
    super.writeTo(out);
    out.writeString(name, 60);
    out.writeInt(count);
  }

  protected void readFrom(WcInputStream in) throws IOException
  {
    super.readFrom(in);
    name = in.readString(60);
    count = in.readInt();
  }
}
