// File: TListMessagesByUnread_Request.java
// (c) copyright 2002 Santronics Software Inc.
//
//****************************************************
// DO NOT EDIT THIS FILE!!!
// CPP2JAVA GENERATED FROM SOURCE FILE: wcgui.h
//****************************************************
//

package COM.winserver.wildcat;

import java.io.IOException;

public class TListMessagesByUnread_Request extends TWildcatRequest {
  public int flags;

  // Total size
  public static final int SIZE = TWildcatRequest.SIZE+2;

  // Constructors
  public TListMessagesByUnread_Request()
  {
    type = WildcatRequest.wrListMessagesByUnread;
  }

  public TListMessagesByUnread_Request(byte[] x)
  {
    fromByteArray(x);
  }

  // Methods
  protected void writeTo(WcOutputStream out) throws IOException
  {
    super.writeTo(out);
    out.writeShort(flags);
  }

  protected void readFrom(WcInputStream in) throws IOException
  {
    super.readFrom(in);
    flags = in.readUnsignedShort();
  }
}
