// File: TLoginUser_Response.java
// (c) copyright 2002 Santronics Software Inc.
//
//****************************************************
// DO NOT EDIT THIS FILE!!!
// CPP2JAVA GENERATED FROM SOURCE FILE: wcgui.h
//****************************************************
//

package COM.winserver.wildcat;

import java.io.IOException;

public class TLoginUser_Response extends TWildcatRequest {
  public int error;
  public int SystemAccess;
  public int MaxLoginAttempts;
  public String Info;
  public String WWWHostname;
  public int ServerRequestTypes;
  public int Flags;
  public int IdleTimeout;

  // Total size
  public static final int SIZE = TWildcatRequest.SIZE+4+4+4+420+80+2+4+2+4*1;

  // Constructors
  public TLoginUser_Response()
  {
  }

  public TLoginUser_Response(byte[] x)
  {
    fromByteArray(x);
  }

  // Methods
  protected void writeTo(WcOutputStream out) throws IOException
  {
    super.writeTo(out);
    out.writeInt(error);
    out.writeInt(SystemAccess);
    out.writeInt(MaxLoginAttempts);
    out.writeString(Info, 420);
    out.writeString(WWWHostname, 80);
    out.writeShort(ServerRequestTypes);
    out.writeInt(Flags);
    out.writeShort(IdleTimeout);
    out.write(new byte[4*1]);
  }

  protected void readFrom(WcInputStream in) throws IOException
  {
    super.readFrom(in);
    error = in.readInt();
    SystemAccess = in.readInt();
    MaxLoginAttempts = in.readInt();
    Info = in.readString(420);
    WWWHostname = in.readString(80);
    ServerRequestTypes = in.readUnsignedShort();
    Flags = in.readInt();
    IdleTimeout = in.readUnsignedShort();
    in.skip(4*1);
  }
}
