// File: TMenu.java
// (c) copyright 2002 Santronics Software Inc.
//
//****************************************************
// DO NOT EDIT THIS FILE!!!
// CPP2JAVA GENERATED FROM SOURCE FILE: wctype.h
//****************************************************
//

package COM.winserver.wildcat;

import java.io.IOException;

public class TMenu extends WcRecord {
  public int ObjectId;
  public String Description;
  public String DisplayName;
  public int Flags;
  public int Count;
  public TwcMenuItem[] Items;
  public int FastLoginChar;
  public String SecurityEntryName;

  // Total size
  public static final int SIZE = 0+4+40+16+4+4+40*TwcMenuItem.SIZE+4+24+128*1;

  // Constructors
  public TMenu()
  {
  }

  public TMenu(byte[] x)
  {
    fromByteArray(x);
  }

  // Methods
  protected void writeTo(WcOutputStream out) throws IOException
  {
    super.writeTo(out);
    out.writeInt(ObjectId);
    out.writeString(Description, 40);
    out.writeString(DisplayName, 16);
    out.writeInt(Flags);
    out.writeInt(Count);
    for (int i = 0; i < 40; i++) {
      if (i < Items.length) {
        Items[i].writeTo(out);
      } else {
        out.write(new byte[TwcMenuItem.SIZE]);
      }
    }
    out.writeInt(FastLoginChar);
    out.writeString(SecurityEntryName, 24);
    out.write(new byte[128*1]);
  }

  protected void readFrom(WcInputStream in) throws IOException
  {
    super.readFrom(in);
    ObjectId = in.readInt();
    Description = in.readString(40);
    DisplayName = in.readString(16);
    Flags = in.readInt();
    Count = in.readInt();
    Items = new TwcMenuItem[40];
    for (int i = 0; i < 40; i++) {
      Items[i] = new TwcMenuItem();
      Items[i].readFrom(in);
    }
    FastLoginChar = in.readInt();
    SecurityEntryName = in.readString(24);
    in.skip(128*1);
  }
}
