// File: TNavigatorRunClient.java
// (c) copyright 2002 Santronics Software Inc.
//
//****************************************************
// DO NOT EDIT THIS FILE!!!
// CPP2JAVA GENERATED FROM SOURCE FILE: wcgui.h
//****************************************************
//

package COM.winserver.wildcat;

import java.io.IOException;

public class TNavigatorRunClient extends WcRecord {
  public String CommandLine;

  // Total size
  public static final int SIZE = 0+260;

  // Constructors
  public TNavigatorRunClient()
  {
  }

  public TNavigatorRunClient(byte[] x)
  {
    fromByteArray(x);
  }

  // Methods
  protected void writeTo(WcOutputStream out) throws IOException
  {
    super.writeTo(out);
    out.writeString(CommandLine, 260);
  }

  protected void readFrom(WcInputStream in) throws IOException
  {
    super.readFrom(in);
    CommandLine = in.readString(260);
  }
}
