// File: TNavigatorUpload.java
// (c) copyright 2002 Santronics Software Inc.
//
//****************************************************
// DO NOT EDIT THIS FILE!!!
// CPP2JAVA GENERATED FROM SOURCE FILE: wcgui.h
//****************************************************
//

package COM.winserver.wildcat;

import java.io.IOException;

public class TNavigatorUpload extends WcRecord {
  public String FileName;

  // Total size
  public static final int SIZE = 0+16;

  // Constructors
  public TNavigatorUpload()
  {
  }

  public TNavigatorUpload(byte[] x)
  {
    fromByteArray(x);
  }

  // Methods
  protected void writeTo(WcOutputStream out) throws IOException
  {
    super.writeTo(out);
    out.writeString(FileName, 16);
  }

  protected void readFrom(WcInputStream in) throws IOException
  {
    super.readFrom(in);
    FileName = in.readString(16);
  }
}
