// File: TNodeConfig.java
// (c) copyright 2002 Santronics Software Inc.
//
//****************************************************
// DO NOT EDIT THIS FILE!!!
// CPP2JAVA GENERATED FROM SOURCE FILE: wctype.h
//****************************************************
//

package COM.winserver.wildcat;

import java.io.IOException;

public class TNodeConfig extends WcRecord {
  public int CallTypesAllowed;
  public String ModemName;
  public String Computer;
  public String Port;
  public int PermanentLineID;
  public String VirtualDoorPort;

  // Total size
  public static final int SIZE = 0+4+32+16+16+4+8+48*1;

  // Constructors
  public TNodeConfig()
  {
  }

  public TNodeConfig(byte[] x)
  {
    fromByteArray(x);
  }

  // Methods
  protected void writeTo(WcOutputStream out) throws IOException
  {
    super.writeTo(out);
    out.writeInt(CallTypesAllowed);
    out.writeString(ModemName, 32);
    out.writeString(Computer, 16);
    out.writeString(Port, 16);
    out.writeInt(PermanentLineID);
    out.writeString(VirtualDoorPort, 8);
    out.write(new byte[48*1]);
  }

  protected void readFrom(WcInputStream in) throws IOException
  {
    super.readFrom(in);
    CallTypesAllowed = in.readInt();
    ModemName = in.readString(32);
    Computer = in.readString(16);
    Port = in.readString(16);
    PermanentLineID = in.readInt();
    VirtualDoorPort = in.readString(8);
    in.skip(48*1);
  }
}
