// File: TObjectName.java
// (c) copyright 2002 Santronics Software Inc.
//
//****************************************************
// DO NOT EDIT THIS FILE!!!
// CPP2JAVA GENERATED FROM SOURCE FILE: wctype.h
//****************************************************
//

package COM.winserver.wildcat;

import java.io.IOException;

public class TObjectName extends WcRecord {
  public int Status;
  public int ObjectId;
  public int Number;
  public String Name;

  // Total size
  public static final int SIZE = 0+4+4+4+260;

  // Constructors
  public TObjectName()
  {
  }

  public TObjectName(byte[] x)
  {
    fromByteArray(x);
  }

  // Methods
  protected void writeTo(WcOutputStream out) throws IOException
  {
    super.writeTo(out);
    out.writeInt(Status);
    out.writeInt(ObjectId);
    out.writeInt(Number);
    out.writeString(Name, 260);
  }

  protected void readFrom(WcInputStream in) throws IOException
  {
    super.readFrom(in);
    Status = in.readInt();
    ObjectId = in.readInt();
    Number = in.readInt();
    Name = in.readString(260);
  }
}
