// File: TRequestOfflineFiles_Submit.java
// (c) copyright 2002 Santronics Software Inc.
//
//****************************************************
// DO NOT EDIT THIS FILE!!!
// CPP2JAVA GENERATED FROM SOURCE FILE: wcgui.h
//****************************************************
//

package COM.winserver.wildcat;

import java.io.IOException;

public class TRequestOfflineFiles_Submit extends TWildcatRequest {
  public String FileName;
  public int FileArea;

  // Total size
  public static final int SIZE = TWildcatRequest.SIZE+16+4;

  // Constructors
  public TRequestOfflineFiles_Submit()
  {
  }

  public TRequestOfflineFiles_Submit(byte[] x)
  {
    fromByteArray(x);
  }

  // Methods
  protected void writeTo(WcOutputStream out) throws IOException
  {
    super.writeTo(out);
    out.writeString(FileName, 16);
    out.writeInt(FileArea);
  }

  protected void readFrom(WcInputStream in) throws IOException
  {
    super.readFrom(in);
    FileName = in.readString(16);
    FileArea = in.readInt();
  }
}
