// File: TResolveFileName_Request.java
// (c) copyright 2002 Santronics Software Inc.
//
//****************************************************
// DO NOT EDIT THIS FILE!!!
// CPP2JAVA GENERATED FROM SOURCE FILE: wcgui.h
//****************************************************
//

package COM.winserver.wildcat;

import java.io.IOException;

public class TResolveFileName_Request extends TWildcatRequest {
  public String filename;

  // Total size
  public static final int SIZE = TWildcatRequest.SIZE+16;

  // Constructors
  public TResolveFileName_Request()
  {
    type = WildcatRequest.wrResolveFileName;
  }

  public TResolveFileName_Request(byte[] x)
  {
    fromByteArray(x);
  }

  // Methods
  protected void writeTo(WcOutputStream out) throws IOException
  {
    super.writeTo(out);
    out.writeString(filename, 16);
  }

  protected void readFrom(WcInputStream in) throws IOException
  {
    super.readFrom(in);
    filename = in.readString(16);
  }
}
