// File: TSearchUserNames_Request.java
// (c) copyright 2002 Santronics Software Inc.
//
//****************************************************
// DO NOT EDIT THIS FILE!!!
// CPP2JAVA GENERATED FROM SOURCE FILE: wcgui.h
//****************************************************
//

package COM.winserver.wildcat;

import java.io.IOException;

public class TSearchUserNames_Request extends TWildcatRequest {
  public String username;

  // Total size
  public static final int SIZE = TWildcatRequest.SIZE+72;

  // Constructors
  public TSearchUserNames_Request()
  {
    type = WildcatRequest.wrSearchUserNames;
  }

  public TSearchUserNames_Request(byte[] x)
  {
    fromByteArray(x);
  }

  // Methods
  protected void writeTo(WcOutputStream out) throws IOException
  {
    super.writeTo(out);
    out.writeString(username, 72);
  }

  protected void readFrom(WcInputStream in) throws IOException
  {
    super.readFrom(in);
    username = in.readString(72);
  }
}
