// File: TSecurityProfile.java
// (c) copyright 2002 Santronics Software Inc.
//
//****************************************************
// DO NOT EDIT THIS FILE!!!
// CPP2JAVA GENERATED FROM SOURCE FILE: wctype.h
//****************************************************
//

package COM.winserver.wildcat;

import java.io.IOException;

public class TSecurityProfile extends WcRecord {
  public String Name;
  public String ExpiredName;
  public String DisplayFileName;
  public String DoorSysProfileName;
  public String MenuDisplaySet;
  public int DailyTimeLimit;
  public int PerCallTimeLimit;
  public int VerifyPhoneInterval;
  public int VerifyBirthdateInterval;
  public int FailedInfoAction;
  public int MaxDownloadCountPerDay;
  public int DownloadRatioLimit;
  public int MaxDownloadKbytesPerDay;
  public int DownloadKbytesRatioLimit;
  public int UploadTimeCredit;
  public int ExpireDays;
  public int PasswordOptions;
  public int PasswordExpireDays;
  public int FtpSpaceKbytes;
  public String EmailDomainName;
  public int MaximumLogons;
  public boolean RestrictedHours;
  public TLogonHours LogonHours;

  // Total size
  public static final int SIZE = 0+24+24+16+24+16+4+4+4+4+4+4+4+4+4+4+4+2+2+4+64+4+4+TLogonHours.SIZE;

  // Constructors
  public TSecurityProfile()
  {
  }

  public TSecurityProfile(byte[] x)
  {
    fromByteArray(x);
  }

  // Methods
  protected void writeTo(WcOutputStream out) throws IOException
  {
    super.writeTo(out);
    out.writeString(Name, 24);
    out.writeString(ExpiredName, 24);
    out.writeString(DisplayFileName, 16);
    out.writeString(DoorSysProfileName, 24);
    out.writeString(MenuDisplaySet, 16);
    out.writeInt(DailyTimeLimit);
    out.writeInt(PerCallTimeLimit);
    out.writeInt(VerifyPhoneInterval);
    out.writeInt(VerifyBirthdateInterval);
    out.writeInt(FailedInfoAction);
    out.writeInt(MaxDownloadCountPerDay);
    out.writeInt(DownloadRatioLimit);
    out.writeInt(MaxDownloadKbytesPerDay);
    out.writeInt(DownloadKbytesRatioLimit);
    out.writeInt(UploadTimeCredit);
    out.writeInt(ExpireDays);
    out.writeShort(PasswordOptions);
    out.writeShort(PasswordExpireDays);
    out.writeInt(FtpSpaceKbytes);
    out.writeString(EmailDomainName, 64);
    out.writeInt(MaximumLogons);
    out.writeBoolean(RestrictedHours);
    LogonHours.writeTo(out);
  }

  protected void readFrom(WcInputStream in) throws IOException
  {
    super.readFrom(in);
    Name = in.readString(24);
    ExpiredName = in.readString(24);
    DisplayFileName = in.readString(16);
    DoorSysProfileName = in.readString(24);
    MenuDisplaySet = in.readString(16);
    DailyTimeLimit = in.readInt();
    PerCallTimeLimit = in.readInt();
    VerifyPhoneInterval = in.readInt();
    VerifyBirthdateInterval = in.readInt();
    FailedInfoAction = in.readInt();
    MaxDownloadCountPerDay = in.readInt();
    DownloadRatioLimit = in.readInt();
    MaxDownloadKbytesPerDay = in.readInt();
    DownloadKbytesRatioLimit = in.readInt();
    UploadTimeCredit = in.readInt();
    ExpireDays = in.readInt();
    PasswordOptions = in.readUnsignedShort();
    PasswordExpireDays = in.readUnsignedShort();
    FtpSpaceKbytes = in.readInt();
    EmailDomainName = in.readString(64);
    MaximumLogons = in.readInt();
    RestrictedHours = in.readBoolean();
    LogonHours = new TLogonHours(); LogonHours.readFrom(in);
  }
}
