// File: TServerState.java
// (c) copyright 2002 Santronics Software Inc.
//
//****************************************************
// DO NOT EDIT THIS FILE!!!
// CPP2JAVA GENERATED FROM SOURCE FILE: wctype.h
//****************************************************
//

package COM.winserver.wildcat;

import java.io.IOException;

public class TServerState extends WcRecord {
  public int OwnerId;
  public String Computer;
  public String Port;
  public int State;

  // Total size
  public static final int SIZE = 0+4+16+80+4;

  // Constructors
  public TServerState()
  {
  }

  public TServerState(byte[] x)
  {
    fromByteArray(x);
  }

  // Methods
  protected void writeTo(WcOutputStream out) throws IOException
  {
    super.writeTo(out);
    out.writeInt(OwnerId);
    out.writeString(Computer, 16);
    out.writeString(Port, 80);
    out.writeInt(State);
  }

  protected void readFrom(WcInputStream in) throws IOException
  {
    super.readFrom(in);
    OwnerId = in.readInt();
    Computer = in.readString(16);
    Port = in.readString(80);
    State = in.readInt();
  }
}
