// File: TSetLastRead_Request.java
// (c) copyright 2002 Santronics Software Inc.
//
//****************************************************
// DO NOT EDIT THIS FILE!!!
// CPP2JAVA GENERATED FROM SOURCE FILE: wcgui.h
//****************************************************
//

package COM.winserver.wildcat;

import java.io.IOException;

public class TSetLastRead_Request extends TWildcatRequest {
  public int conference;
  public int lastread;

  // Total size
  public static final int SIZE = TWildcatRequest.SIZE+4+4;

  // Constructors
  public TSetLastRead_Request()
  {
    type = WildcatRequest.wrSetLastRead;
  }

  public TSetLastRead_Request(byte[] x)
  {
    fromByteArray(x);
  }

  // Methods
  protected void writeTo(WcOutputStream out) throws IOException
  {
    super.writeTo(out);
    out.writeInt(conference);
    out.writeInt(lastread);
  }

  protected void readFrom(WcInputStream in) throws IOException
  {
    super.readFrom(in);
    conference = in.readInt();
    lastread = in.readInt();
  }
}
