// File: TSetMultipleConferenceFlags_SetData.java
// (c) copyright 2002 Santronics Software Inc.
//
//****************************************************
// DO NOT EDIT THIS FILE!!!
// CPP2JAVA GENERATED FROM SOURCE FILE: wcgui.h
//****************************************************
//

package COM.winserver.wildcat;

import java.io.IOException;

public class TSetMultipleConferenceFlags_SetData extends TWildcatRequest {
  public int start;
  public int runlength;
  public int flags;

  // Total size
  public static final int SIZE = TWildcatRequest.SIZE+4+4+4;

  // Constructors
  public TSetMultipleConferenceFlags_SetData()
  {
  }

  public TSetMultipleConferenceFlags_SetData(byte[] x)
  {
    fromByteArray(x);
  }

  // Methods
  protected void writeTo(WcOutputStream out) throws IOException
  {
    super.writeTo(out);
    out.writeInt(start);
    out.writeInt(runlength);
    out.writeInt(flags);
  }

  protected void readFrom(WcInputStream in) throws IOException
  {
    super.readFrom(in);
    start = in.readInt();
    runlength = in.readInt();
    flags = in.readInt();
  }
}
