// File: TShortModemProfile.java
// (c) copyright 2002 Santronics Software Inc.
//
//****************************************************
// DO NOT EDIT THIS FILE!!!
// CPP2JAVA GENERATED FROM SOURCE FILE: wctype.h
//****************************************************
//

package COM.winserver.wildcat;

import java.io.IOException;

public class TShortModemProfile extends WcRecord {
  public boolean UserDefined;
  public String Name;

  // Total size
  public static final int SIZE = 0+4+32;

  // Constructors
  public TShortModemProfile()
  {
  }

  public TShortModemProfile(byte[] x)
  {
    fromByteArray(x);
  }

  // Methods
  protected void writeTo(WcOutputStream out) throws IOException
  {
    super.writeTo(out);
    out.writeBoolean(UserDefined);
    out.writeString(Name, 32);
  }

  protected void readFrom(WcInputStream in) throws IOException
  {
    super.readFrom(in);
    UserDefined = in.readBoolean();
    Name = in.readString(32);
  }
}
