// File: TShortConfDesc.java
// (c) copyright 2002 Santronics Software Inc.
//
//****************************************************
// DO NOT EDIT THIS FILE!!!
// CPP2JAVA GENERATED FROM SOURCE FILE: wctype.h
//****************************************************
//

package COM.winserver.wildcat;

import java.io.IOException;

public class TShortConfDesc extends WcRecord {
  public int ObjectId;
  public String Name;
  public int MailType;

  // Total size
  public static final int SIZE = 0+4+60+4;

  // Constructors
  public TShortConfDesc()
  {
  }

  public TShortConfDesc(byte[] x)
  {
    fromByteArray(x);
  }

  // Methods
  protected void writeTo(WcOutputStream out) throws IOException
  {
    super.writeTo(out);
    out.writeInt(ObjectId);
    out.writeString(Name, 60);
    out.writeInt(MailType);
  }

  protected void readFrom(WcInputStream in) throws IOException
  {
    super.readFrom(in);
    ObjectId = in.readInt();
    Name = in.readString(60);
    MailType = in.readInt();
  }
}
