// File: TSocketAcceptRequest.java
// (c) copyright 2002 Santronics Software Inc.
//
//****************************************************
// DO NOT EDIT THIS FILE!!!
// CPP2JAVA GENERATED FROM SOURCE FILE: wcgui.h
//****************************************************
//

package COM.winserver.wildcat;

import java.io.IOException;

public class TSocketAcceptRequest extends WcRecord {
  public int MagicAcceptRequest;
  public int AcceptHandle;

  // Total size
  public static final int SIZE = 0+2+4;

  // Constructors
  public TSocketAcceptRequest()
  {
  }

  public TSocketAcceptRequest(byte[] x)
  {
    fromByteArray(x);
  }

  // Methods
  protected void writeTo(WcOutputStream out) throws IOException
  {
    super.writeTo(out);
    out.writeShort(MagicAcceptRequest);
    out.writeInt(AcceptHandle);
  }

  protected void readFrom(WcInputStream in) throws IOException
  {
    super.readFrom(in);
    MagicAcceptRequest = in.readUnsignedShort();
    AcceptHandle = in.readInt();
  }
}
