// File: TSocketListenRequest.java
// (c) copyright 2002 Santronics Software Inc.
//
//****************************************************
// DO NOT EDIT THIS FILE!!!
// CPP2JAVA GENERATED FROM SOURCE FILE: wcgui.h
//****************************************************
//

package COM.winserver.wildcat;

import java.io.IOException;

public class TSocketListenRequest extends WcRecord {
  public int MagicListenRequest;
  public int RequestedPort;

  // Total size
  public static final int SIZE = 0+2+2;

  // Constructors
  public TSocketListenRequest()
  {
  }

  public TSocketListenRequest(byte[] x)
  {
    fromByteArray(x);
  }

  // Methods
  protected void writeTo(WcOutputStream out) throws IOException
  {
    super.writeTo(out);
    out.writeShort(MagicListenRequest);
    out.writeShort(RequestedPort);
  }

  protected void readFrom(WcInputStream in) throws IOException
  {
    super.readFrom(in);
    MagicListenRequest = in.readUnsignedShort();
    RequestedPort = in.readUnsignedShort();
  }
}
