// File: TSortedList_Request.java
// (c) copyright 2002 Santronics Software Inc.
//
//****************************************************
// DO NOT EDIT THIS FILE!!!
// CPP2JAVA GENERATED FROM SOURCE FILE: wcgui.h
//****************************************************
//

package COM.winserver.wildcat;

import java.io.IOException;

public class TSortedList_Request extends TWildcatRequest {
  public int sorted;

  // Total size
  public static final int SIZE = TWildcatRequest.SIZE+4;

  // Constructors
  public TSortedList_Request()
  {
  }

  public TSortedList_Request(byte[] x)
  {
    fromByteArray(x);
  }

  // Methods
  protected void writeTo(WcOutputStream out) throws IOException
  {
    super.writeTo(out);
    out.writeInt(sorted);
  }

  protected void readFrom(WcInputStream in) throws IOException
  {
    super.readFrom(in);
    sorted = in.readInt();
  }
}
