// File: TSpellSuggestList.java
// (c) copyright 2002 Santronics Software Inc.
//
//****************************************************
// DO NOT EDIT THIS FILE!!!
// CPP2JAVA GENERATED FROM SOURCE FILE: wctype.h
//****************************************************
//

package COM.winserver.wildcat;

import java.io.IOException;

public class TSpellSuggestList extends WcRecord {
  public String[] Words;

  // Total size
  public static final int SIZE = 0+10*32;

  // Constructors
  public TSpellSuggestList()
  {
  }

  public TSpellSuggestList(byte[] x)
  {
    fromByteArray(x);
  }

  // Methods
  protected void writeTo(WcOutputStream out) throws IOException
  {
    super.writeTo(out);
    for (int i = 0; i < 10; i++) {
      if (i < Words.length) {
        out.writeString(Words[i], 32);
      } else {
        out.write(new byte[32]);
      }
    }
  }

  protected void readFrom(WcInputStream in) throws IOException
  {
    super.readFrom(in);
    Words = new String[10];
    for (int i = 0; i < 10; i++) {
      Words[i] = in.readString(32);
    }
  }
}
