// File: TSystemPageInstantMessage.java
// (c) copyright 2002 Santronics Software Inc.
//
//****************************************************
// DO NOT EDIT THIS FILE!!!
// CPP2JAVA GENERATED FROM SOURCE FILE: wctype.h
//****************************************************
//

package COM.winserver.wildcat;

import java.io.IOException;

public class TSystemPageInstantMessage extends WcRecord {
  public String From;
  public String[] Text;
  public boolean InviteToChat;

  // Total size
  public static final int SIZE = 0+28+3*80+4;

  // Constructors
  public TSystemPageInstantMessage()
  {
  }

  public TSystemPageInstantMessage(byte[] x)
  {
    fromByteArray(x);
  }

  // Methods
  protected void writeTo(WcOutputStream out) throws IOException
  {
    super.writeTo(out);
    out.writeString(From, 28);
    for (int i = 0; i < 3; i++) {
      if (i < Text.length) {
        out.writeString(Text[i], 80);
      } else {
        out.write(new byte[80]);
      }
    }
    out.writeBoolean(InviteToChat);
  }

  protected void readFrom(WcInputStream in) throws IOException
  {
    super.readFrom(in);
    From = in.readString(28);
    Text = new String[3];
    for (int i = 0; i < 3; i++) {
      Text[i] = in.readString(80);
    }
    InviteToChat = in.readBoolean();
  }
}
