// File: TSystemEventFileInfo.java
// (c) copyright 2002 Santronics Software Inc.
//
//****************************************************
// DO NOT EDIT THIS FILE!!!
// CPP2JAVA GENERATED FROM SOURCE FILE: wctype.h
//****************************************************
//

package COM.winserver.wildcat;

import java.io.IOException;

public class TSystemEventFileInfo extends WcRecord {
  public int FileArea;
  public int ConnectionId;
  public long TimeStamp;
  public String  szFileName;

  // Total size
  public static final int SIZE = 0+4+4+8+MAX_PATH;

  // Constructors
  public TSystemEventFileInfo()
  {
  }

  public TSystemEventFileInfo(byte[] x)
  {
    fromByteArray(x);
  }

  // Methods
  protected void writeTo(WcOutputStream out) throws IOException
  {
    super.writeTo(out);
    out.writeInt(FileArea);
    out.writeInt(ConnectionId);
    out.writeLong(TimeStamp);
    out.writeString( szFileName, MAX_PATH);
  }

  protected void readFrom(WcInputStream in) throws IOException
  {
    super.readFrom(in);
    FileArea = in.readInt();
    ConnectionId = in.readInt();
    TimeStamp = in.readLong();
     szFileName = in.readString(MAX_PATH);
  }
}
