// File: TSystemControlViewMsg.java
// (c) copyright 2002 Santronics Software Inc.
//
//****************************************************
// DO NOT EDIT THIS FILE!!!
// CPP2JAVA GENERATED FROM SOURCE FILE: wctype.h
//****************************************************
//

package COM.winserver.wildcat;

import java.io.IOException;

public class TSystemControlViewMsg extends WcRecord {
  public int Line;
  public int Count;
  //int[][] Text;
  public int CursorX;
  public int CursorY;
  public int MinutesLeft;

  // Total size
  public static final int SIZE = 0+2+2+3*80*2+2+2+2;

  // Constructors
  public TSystemControlViewMsg()
  {
  }

  public TSystemControlViewMsg(byte[] x)
  {
    fromByteArray(x);
  }

  // Methods
  protected void writeTo(WcOutputStream out) throws IOException
  {
    super.writeTo(out);
    out.writeShort(Line);
    out.writeShort(Count);
    out.writeShort(CursorX);
    out.writeShort(CursorY);
    out.writeShort(MinutesLeft);
  }

  protected void readFrom(WcInputStream in) throws IOException
  {
    super.readFrom(in);
    Line = in.readUnsignedShort();
    Count = in.readUnsignedShort();
    CursorX = in.readUnsignedShort();
    CursorY = in.readUnsignedShort();
    MinutesLeft = in.readUnsignedShort();
  }
}
