// File: TUpdateCurrentUser_Request.java
// (c) copyright 2002 Santronics Software Inc.
//
//****************************************************
// DO NOT EDIT THIS FILE!!!
// CPP2JAVA GENERATED FROM SOURCE FILE: wcgui.h
//****************************************************
//

package COM.winserver.wildcat;

import java.io.IOException;

public class TUpdateCurrentUser_Request extends TWildcatRequest {
  public TUser User;

  // Total size
  public static final int SIZE = TWildcatRequest.SIZE+TUser.SIZE;

  // Constructors
  public TUpdateCurrentUser_Request()
  {
    type = WildcatRequest.wrUpdateCurrentUser;
  }

  public TUpdateCurrentUser_Request(byte[] x)
  {
    fromByteArray(x);
  }

  // Methods
  protected void writeTo(WcOutputStream out) throws IOException
  {
    super.writeTo(out);
    User.writeTo(out);
  }

  protected void readFrom(WcInputStream in) throws IOException
  {
    super.readFrom(in);
    User = new TUser(); User.readFrom(in);
  }
}
