// File: TUploadAttachment_SetMessage_Request.java
// (c) copyright 2002 Santronics Software Inc.
//
//****************************************************
// DO NOT EDIT THIS FILE!!!
// CPP2JAVA GENERATED FROM SOURCE FILE: wcgui.h
//****************************************************
//

package COM.winserver.wildcat;

import java.io.IOException;

public class TUploadAttachment_SetMessage_Request extends TWildcatRequest {
  public int conference;
  public int msgid;

  // Total size
  public static final int SIZE = TWildcatRequest.SIZE+2+4;

  // Constructors
  public TUploadAttachment_SetMessage_Request()
  {
    type = WildcatRequest.wrUploadAttachment;
  }

  public TUploadAttachment_SetMessage_Request(byte[] x)
  {
    fromByteArray(x);
  }

  // Methods
  protected void writeTo(WcOutputStream out) throws IOException
  {
    super.writeTo(out);
    out.writeShort(conference);
    out.writeInt(msgid);
  }

  protected void readFrom(WcInputStream in) throws IOException
  {
    super.readFrom(in);
    conference = in.readUnsignedShort();
    msgid = in.readInt();
  }
}
