// File: TUploadFileEx_Request.java
// (c) copyright 2002 Santronics Software Inc.
//
//****************************************************
// DO NOT EDIT THIS FILE!!!
// CPP2JAVA GENERATED FROM SOURCE FILE: wcgui.h
//****************************************************
//

package COM.winserver.wildcat;

import java.io.IOException;

public class TUploadFileEx_Request extends TWildcatRequest {
  public TFullFileRecord5 file;
  public int flags;

  // Total size
  public static final int SIZE = TWildcatRequest.SIZE+TFullFileRecord5.SIZE+2;

  // Constructors
  public TUploadFileEx_Request()
  {
    type = WildcatRequest.wrUploadFileEx;
  }

  public TUploadFileEx_Request(byte[] x)
  {
    fromByteArray(x);
  }

  // Methods
  protected void writeTo(WcOutputStream out) throws IOException
  {
    super.writeTo(out);
    file.writeTo(out);
    out.writeShort(flags);
  }

  protected void readFrom(WcInputStream in) throws IOException
  {
    super.readFrom(in);
    file = new TFullFileRecord5(); file.readFrom(in);
    flags = in.readUnsignedShort();
  }
}
