// File: TUserInfo.java
// (c) copyright 2002 Santronics Software Inc.
//
//****************************************************
// DO NOT EDIT THIS FILE!!!
// CPP2JAVA GENERATED FROM SOURCE FILE: wctype.h
//****************************************************
//

package COM.winserver.wildcat;

import java.io.IOException;

public class TUserInfo extends WcRecord {
  public int Id;
  public String Name;
  public String Title;

  // Total size
  public static final int SIZE = 0+4+72+12;

  // Constructors
  public TUserInfo()
  {
  }

  public TUserInfo(byte[] x)
  {
    fromByteArray(x);
  }

  // Methods
  protected void writeTo(WcOutputStream out) throws IOException
  {
    super.writeTo(out);
    out.writeInt(Id);
    out.writeString(Name, 72);
    out.writeString(Title, 12);
  }

  protected void readFrom(WcInputStream in) throws IOException
  {
    super.readFrom(in);
    Id = in.readInt();
    Name = in.readString(72);
    Title = in.readString(12);
  }
}
