// File: TViewArchive_Request.java
// (c) copyright 2002 Santronics Software Inc.
//
//****************************************************
// DO NOT EDIT THIS FILE!!!
// CPP2JAVA GENERATED FROM SOURCE FILE: wcgui.h
//****************************************************
//

package COM.winserver.wildcat;

import java.io.IOException;

public class TViewArchive_Request extends TWildcatRequest {
  public int area;
  public String filename;

  // Total size
  public static final int SIZE = TWildcatRequest.SIZE+4+16;

  // Constructors
  public TViewArchive_Request()
  {
    type = WildcatRequest.wrViewArchive;
  }

  public TViewArchive_Request(byte[] x)
  {
    fromByteArray(x);
  }

  // Methods
  protected void writeTo(WcOutputStream out) throws IOException
  {
    super.writeTo(out);
    out.writeInt(area);
    out.writeString(filename, 16);
  }

  protected void readFrom(WcInputStream in) throws IOException
  {
    super.readFrom(in);
    area = in.readInt();
    filename = in.readString(16);
  }
}
