// File: TwcMenuItem.java
// (c) copyright 2002 Santronics Software Inc.
//
//****************************************************
// DO NOT EDIT THIS FILE!!!
// CPP2JAVA GENERATED FROM SOURCE FILE: wctype.h
//****************************************************
//

package COM.winserver.wildcat;

import java.io.IOException;

public class TwcMenuItem extends WcRecord {
  public String Selection;
  public String Description;
  public String Command;
  public String Parameters;

  // Total size
  public static final int SIZE = 0+16+32+48+48+4*1;

  // Constructors
  public TwcMenuItem()
  {
  }

  public TwcMenuItem(byte[] x)
  {
    fromByteArray(x);
  }

  // Methods
  protected void writeTo(WcOutputStream out) throws IOException
  {
    super.writeTo(out);
    out.writeString(Selection, 16);
    out.writeString(Description, 32);
    out.writeString(Command, 48);
    out.writeString(Parameters, 48);
    out.write(new byte[4*1]);
  }

  protected void readFrom(WcInputStream in) throws IOException
  {
    super.readFrom(in);
    Selection = in.readString(16);
    Description = in.readString(32);
    Command = in.readString(48);
    Parameters = in.readString(48);
    in.skip(4*1);
  }
}
