// File: TWildcatProcessTimes.java
// (c) copyright 2002 Santronics Software Inc.
//
//****************************************************
// DO NOT EDIT THIS FILE!!!
// CPP2JAVA GENERATED FROM SOURCE FILE: wctype.h
//****************************************************
//

package COM.winserver.wildcat;

import java.io.IOException;

public class TWildcatProcessTimes extends WcRecord {
  public long ftSystem;
  public long ftStart;
  public long ftExit;
  public long ftKernel;
  public long ftUser;

  // Total size
  public static final int SIZE = 0+8+8+8+8+8+24*1;

  // Constructors
  public TWildcatProcessTimes()
  {
  }

  public TWildcatProcessTimes(byte[] x)
  {
    fromByteArray(x);
  }

  // Methods
  protected void writeTo(WcOutputStream out) throws IOException
  {
    super.writeTo(out);
    out.writeLong(ftSystem);
    out.writeLong(ftStart);
    out.writeLong(ftExit);
    out.writeLong(ftKernel);
    out.writeLong(ftUser);
    out.write(new byte[24*1]);
  }

  protected void readFrom(WcInputStream in) throws IOException
  {
    super.readFrom(in);
    ftSystem = in.readLong();
    ftStart = in.readLong();
    ftExit = in.readLong();
    ftKernel = in.readLong();
    ftUser = in.readLong();
    in.skip(24*1);
  }
}
