// File: TWildcatServerInfo.java
// (c) copyright 2002 Santronics Software Inc.
//
//****************************************************
// DO NOT EDIT THIS FILE!!!
// CPP2JAVA GENERATED FROM SOURCE FILE: wctype.h
//****************************************************
//

package COM.winserver.wildcat;

import java.io.IOException;

public class TWildcatServerInfo extends WcRecord {
  public int TotalCalls;
  public int TotalUsers;
  public int TotalMessages;
  public int TotalFiles;
  public int MemoryUsage;
  public int MemoryLoad;
  public int LastMessageId;
  public int LastUserId;

  // Total size
  public static final int SIZE = 0+4+4+4+4+4+4+4+4+92*1;

  // Constructors
  public TWildcatServerInfo()
  {
  }

  public TWildcatServerInfo(byte[] x)
  {
    fromByteArray(x);
  }

  // Methods
  protected void writeTo(WcOutputStream out) throws IOException
  {
    super.writeTo(out);
    out.writeInt(TotalCalls);
    out.writeInt(TotalUsers);
    out.writeInt(TotalMessages);
    out.writeInt(TotalFiles);
    out.writeInt(MemoryUsage);
    out.writeInt(MemoryLoad);
    out.writeInt(LastMessageId);
    out.writeInt(LastUserId);
    out.write(new byte[92*1]);
  }

  protected void readFrom(WcInputStream in) throws IOException
  {
    super.readFrom(in);
    TotalCalls = in.readInt();
    TotalUsers = in.readInt();
    TotalMessages = in.readInt();
    TotalFiles = in.readInt();
    MemoryUsage = in.readInt();
    MemoryLoad = in.readInt();
    LastMessageId = in.readInt();
    LastUserId = in.readInt();
    in.skip(92*1);
  }
}
