// File: TWildcatService.java
// (c) copyright 2002 Santronics Software Inc.
//
//****************************************************
// DO NOT EDIT THIS FILE!!!
// CPP2JAVA GENERATED FROM SOURCE FILE: wctype.h
//****************************************************
//

package COM.winserver.wildcat;

import java.io.IOException;

public class TWildcatService extends WcRecord {
  public String Name;
  public String Vendor;
  public int Version;
  public int Address;
  public int Port;

  // Total size
  public static final int SIZE = 0+64+64+4+4+4;

  // Constructors
  public TWildcatService()
  {
  }

  public TWildcatService(byte[] x)
  {
    fromByteArray(x);
  }

  // Methods
  protected void writeTo(WcOutputStream out) throws IOException
  {
    super.writeTo(out);
    out.writeString(Name, 64);
    out.writeString(Vendor, 64);
    out.writeInt(Version);
    out.writeInt(Address);
    out.writeInt(Port);
  }

  protected void readFrom(WcInputStream in) throws IOException
  {
    super.readFrom(in);
    Name = in.readString(64);
    Vendor = in.readString(64);
    Version = in.readInt();
    Address = in.readInt();
    Port = in.readInt();
  }
}
