// File: TWildcatPOP3.java
// (c) copyright 2002 Santronics Software Inc.
//
//****************************************************
// DO NOT EDIT THIS FILE!!!
// CPP2JAVA GENERATED FROM SOURCE FILE: wctype.h
//****************************************************
//

package COM.winserver.wildcat;

import java.io.IOException;

public class TWildcatPOP3 extends WcRecord {
  public int  dwVersion;
  public int  dwRevision;
  public boolean  EnablePopBeforeSmtp;
  public int dwPopBeforeSmtpTimeout;
  public int MarkDownloadAsReceived;
  public TWildcatLogOptions LogOptions;

  // Total size
  public static final int SIZE = 0+2+2+4+4+4+TWildcatLogOptions.SIZE+80;

  // Constructors
  public TWildcatPOP3()
  {
  }

  public TWildcatPOP3(byte[] x)
  {
    fromByteArray(x);
  }

  // Methods
  protected void writeTo(WcOutputStream out) throws IOException
  {
    super.writeTo(out);
    out.writeShort( dwVersion);
    out.writeShort( dwRevision);
    out.writeBoolean( EnablePopBeforeSmtp);
    out.writeInt(dwPopBeforeSmtpTimeout);
    out.writeInt(MarkDownloadAsReceived);
    LogOptions.writeTo(out);
    out.write(new byte[80]);
  }

  protected void readFrom(WcInputStream in) throws IOException
  {
    super.readFrom(in);
     dwVersion = in.readUnsignedShort();
     dwRevision = in.readUnsignedShort();
     EnablePopBeforeSmtp = in.readBoolean();
    dwPopBeforeSmtpTimeout = in.readInt();
    MarkDownloadAsReceived = in.readInt();
    LogOptions = new TWildcatLogOptions(); LogOptions.readFrom(in);
    in.skip(80);
  }
}
