// File: TWildcatSASLContext.java
// (c) copyright 2002 Santronics Software Inc.
//
//****************************************************
// DO NOT EDIT THIS FILE!!!
// CPP2JAVA GENERATED FROM SOURCE FILE: wctype.h
//****************************************************
//

package COM.winserver.wildcat;

import java.io.IOException;

public class TWildcatSASLContext extends WcRecord {
  public String szSaslMethod;
  public String szChallenge;
  public int dwState;
  public int dwUserid;
  public byte[] Data;

  public String szUsername;
  public String szRealm;
  public String szDomain;
  public String szNonce;
  public String szCNonce;
  public int dwCNonceCount;
  public String szURI;
  public String szMethod;
  public String szAlg;
  public String szQop;

  // Total size
  public static final int SIZE = 0+32+260+4+4+4096+72+260+260+260+260+4+260+20+64+64;

  // Constructors
  public TWildcatSASLContext()
  {
  }

  public TWildcatSASLContext(byte[] x)
  {
    fromByteArray(x);
  }

  // Methods
  protected void writeTo(WcOutputStream out) throws IOException
  {
    super.writeTo(out);
    out.writeString(szSaslMethod, 32);
    out.writeString(szChallenge, 260);
    out.writeInt(dwState);
    out.writeInt(dwUserid);
    out.write(Data);
    out.writeString(szUsername, 72);
    out.writeString(szRealm, 260);
    out.writeString(szDomain, 260);
    out.writeString(szNonce, 260);
    out.writeString(szCNonce, 260);
    out.writeInt(dwCNonceCount);
    out.writeString(szURI, 260);
    out.writeString(szMethod, 20);
    out.writeString(szAlg, 64);
    out.writeString(szQop, 64);
  }

  protected void readFrom(WcInputStream in) throws IOException
  {
    super.readFrom(in);
    szSaslMethod = in.readString(32);
    szChallenge = in.readString(260);
    dwState = in.readInt();
    dwUserid = in.readInt();
    Data = new byte[4096]; in.read(Data);
    szUsername = in.readString(72);
    szRealm = in.readString(260);
    szDomain = in.readString(260);
    szNonce = in.readString(260);
    szCNonce = in.readString(260);
    dwCNonceCount = in.readInt();
    szURI = in.readString(260);
    szMethod = in.readString(20);
    szAlg = in.readString(64);
    szQop = in.readString(64);
  }
}
