// File: TWildcatTimeouts.java
// (c) copyright 2002 Santronics Software Inc.
//
//****************************************************
// DO NOT EDIT THIS FILE!!!
// CPP2JAVA GENERATED FROM SOURCE FILE: wctype.h
//****************************************************
//

package COM.winserver.wildcat;

import java.io.IOException;

public class TWildcatTimeouts extends WcRecord {
  public int dwVersion;
  public int dwRevision;
  public int Web;
  public int WebQues;
  public int Telnet;
  public int TelnetLogin;
  public int Ftp;
  public int wcPPP;
  public int wcNAV;

  // Total size
  public static final int SIZE = 0+2+2+4+4+4+4+4+4+4+92;

  // Constructors
  public TWildcatTimeouts()
  {
  }

  public TWildcatTimeouts(byte[] x)
  {
    fromByteArray(x);
  }

  // Methods
  protected void writeTo(WcOutputStream out) throws IOException
  {
    super.writeTo(out);
    out.writeShort(dwVersion);
    out.writeShort(dwRevision);
    out.writeInt(Web);
    out.writeInt(WebQues);
    out.writeInt(Telnet);
    out.writeInt(TelnetLogin);
    out.writeInt(Ftp);
    out.writeInt(wcPPP);
    out.writeInt(wcNAV);
    out.write(new byte[92]);
  }

  protected void readFrom(WcInputStream in) throws IOException
  {
    super.readFrom(in);
    dwVersion = in.readUnsignedShort();
    dwRevision = in.readUnsignedShort();
    Web = in.readInt();
    WebQues = in.readInt();
    Telnet = in.readInt();
    TelnetLogin = in.readInt();
    Ftp = in.readInt();
    wcPPP = in.readInt();
    wcNAV = in.readInt();
    in.skip(92);
  }
}
