// File: TWildcatHttpd.java
// (c) copyright 2002 Santronics Software Inc.
//
//****************************************************
// DO NOT EDIT THIS FILE!!!
// CPP2JAVA GENERATED FROM SOURCE FILE: wctype.h
//****************************************************
//

package COM.winserver.wildcat;

import java.io.IOException;

public class TWildcatHttpd extends WcRecord {
  public int  dwVersion;
  public int  dwRevision;
  public boolean CommonLogFile;
  public boolean DeutschIVW;
  public TWildcatLogOptions LogOptions;

  // Total size
  public static final int SIZE = 0+2+2+4+4+TWildcatLogOptions.SIZE+68*1;

  // Constructors
  public TWildcatHttpd()
  {
  }

  public TWildcatHttpd(byte[] x)
  {
    fromByteArray(x);
  }

  // Methods
  protected void writeTo(WcOutputStream out) throws IOException
  {
    super.writeTo(out);
    out.writeShort( dwVersion);
    out.writeShort( dwRevision);
    out.writeBoolean(CommonLogFile);
    out.writeBoolean(DeutschIVW);
    LogOptions.writeTo(out);
    out.write(new byte[68*1]);
  }

  protected void readFrom(WcInputStream in) throws IOException
  {
    super.readFrom(in);
     dwVersion = in.readUnsignedShort();
     dwRevision = in.readUnsignedShort();
    CommonLogFile = in.readBoolean();
    DeutschIVW = in.readBoolean();
    LogOptions = new TWildcatLogOptions(); LogOptions.readFrom(in);
    in.skip(68*1);
  }
}
