// File: TWildcatLogOptions.java
// (c) copyright 2002 Santronics Software Inc.
//
//****************************************************
// DO NOT EDIT THIS FILE!!!
// CPP2JAVA GENERATED FROM SOURCE FILE: wctype.h
//****************************************************
//

package COM.winserver.wildcat;

import java.io.IOException;

public class TWildcatLogOptions extends WcRecord {
  public boolean EnableSessionTrace;
  public TWildcatLogPeriod LogPeriod;
  public int dwMaxSize;
  public int dwVerbosity;

  // Total size
  public static final int SIZE = 0+4+TWildcatLogPeriod.SIZE+4+4+16*1;

  // Constructors
  public TWildcatLogOptions()
  {
  }

  public TWildcatLogOptions(byte[] x)
  {
    fromByteArray(x);
  }

  // Methods
  protected void writeTo(WcOutputStream out) throws IOException
  {
    super.writeTo(out);
    out.writeBoolean(EnableSessionTrace);
    LogPeriod.writeTo(out);
    out.writeInt(dwMaxSize);
    out.writeInt(dwVerbosity);
    out.write(new byte[16*1]);
  }

  protected void readFrom(WcInputStream in) throws IOException
  {
    super.readFrom(in);
    EnableSessionTrace = in.readBoolean();
    LogPeriod = new TWildcatLogPeriod(); LogPeriod.readFrom(in);
    dwMaxSize = in.readInt();
    dwVerbosity = in.readInt();
    in.skip(16*1);
  }
}
