// File: TWildcatFTP.java
// (c) copyright 2002 Santronics Software Inc.
//
//****************************************************
// DO NOT EDIT THIS FILE!!!
// CPP2JAVA GENERATED FROM SOURCE FILE: wctype.h
//****************************************************
//

package COM.winserver.wildcat;

import java.io.IOException;

public class TWildcatFTP extends WcRecord {
  public int  dwVersion;
  public int  dwRevision;
  public boolean  AllowAnonymous;
  public boolean  ShowFileGroups;
  public boolean  UseUnderScore;
  public boolean  UseSingleAreaChange;
  public int MaxAnonymousConnects;
  public TWildcatLogOptions LogOptions;

  // Total size
  public static final int SIZE = 0+2+2+4+4+4+4+4+TWildcatLogOptions.SIZE+72;

  // Constructors
  public TWildcatFTP()
  {
  }

  public TWildcatFTP(byte[] x)
  {
    fromByteArray(x);
  }

  // Methods
  protected void writeTo(WcOutputStream out) throws IOException
  {
    super.writeTo(out);
    out.writeShort( dwVersion);
    out.writeShort( dwRevision);
    out.writeBoolean( AllowAnonymous);
    out.writeBoolean( ShowFileGroups);
    out.writeBoolean( UseUnderScore);
    out.writeBoolean( UseSingleAreaChange);
    out.writeInt(MaxAnonymousConnects);
    LogOptions.writeTo(out);
    out.write(new byte[72]);
  }

  protected void readFrom(WcInputStream in) throws IOException
  {
    super.readFrom(in);
     dwVersion = in.readUnsignedShort();
     dwRevision = in.readUnsignedShort();
     AllowAnonymous = in.readBoolean();
     ShowFileGroups = in.readBoolean();
     UseUnderScore = in.readBoolean();
     UseSingleAreaChange = in.readBoolean();
    MaxAnonymousConnects = in.readInt();
    LogOptions = new TWildcatLogOptions(); LogOptions.readFrom(in);
    in.skip(72);
  }
}
