// File: TWildcatComputerIpPort.java
// (c) copyright 2002 Santronics Software Inc.
//
//****************************************************
// DO NOT EDIT THIS FILE!!!
// CPP2JAVA GENERATED FROM SOURCE FILE: wctype.h
//****************************************************
//

package COM.winserver.wildcat;

import java.io.IOException;

public class TWildcatComputerIpPort extends WcRecord {
  public int dwPort;
  public int dwIpAddress;

  // Total size
  public static final int SIZE = 0+4+4;

  // Constructors
  public TWildcatComputerIpPort()
  {
  }

  public TWildcatComputerIpPort(byte[] x)
  {
    fromByteArray(x);
  }

  // Methods
  protected void writeTo(WcOutputStream out) throws IOException
  {
    super.writeTo(out);
    out.writeInt(dwPort);
    out.writeInt(dwIpAddress);
  }

  protected void readFrom(WcInputStream in) throws IOException
  {
    super.readFrom(in);
    dwPort = in.readInt();
    dwIpAddress = in.readInt();
  }
}
