// File: TWriteActivityLogEntry_Request.java
// (c) copyright 2002 Santronics Software Inc.
//
//****************************************************
// DO NOT EDIT THIS FILE!!!
// CPP2JAVA GENERATED FROM SOURCE FILE: wcgui.h
//****************************************************
//

package COM.winserver.wildcat;

import java.io.IOException;

public class TWriteActivityLogEntry_Request extends TWildcatRequest {
  public int len;
  public String text;

  // Total size
  public static final int SIZE = TWildcatRequest.SIZE+4+256;

  // Constructors
  public TWriteActivityLogEntry_Request()
  {
    type = WildcatRequest.wrWriteActivityLogEntry;
  }

  public TWriteActivityLogEntry_Request(byte[] x)
  {
    fromByteArray(x);
  }

  // Methods
  protected void writeTo(WcOutputStream out) throws IOException
  {
    super.writeTo(out);
    out.writeInt(len);
    out.writeString(text, 256);
  }

  protected void readFrom(WcInputStream in) throws IOException
  {
    super.readFrom(in);
    len = in.readInt();
    text = in.readString(256);
  }
}
