// File: WildcatRequest2.java
// (c) copyright 2002 Santronics Software Inc.
//
//****************************************************
// DO NOT EDIT THIS FILE!!!
// CPP2JAVA GENERATED FROM SOURCE FILE: wcgui.h
//****************************************************
//

package COM.winserver.wildcat;

import java.io.IOException;

public class WildcatRequest2 {
  public static final int wrListFiles_SetFileArea = 256;
  public static final int wrListFiles_SetFileAreaDone = 257;
  public static final int wrFileTransfer_Data = 258;
  public static final int wrFileTransfer_Error = 259;
  public static final int wrAddMessage_Text = 260;
  public static final int wrViewArchive_Data = 261;
  public static final int wrSearchMessages_SetConfs = 262;
  public static final int wrSearchMessages_SetConfsDone = 263;
  public static final int wrUploadAttachment_SetMessage = 264;
  public static final int wrUploadAttachment_SetMessageDone = 265;
  public static final int wrListMessages_GetMore = 266;
  public static final int wrListMessages_GetAll = 267;
  public static final int wrSetMultipleConferenceFlags_SetAll = 268;
  public static final int wrSetMultipleConferenceFlags_SetData = 269;
  public static final int wrSetMultipleConferenceFlags_SetDone = 270;
  public static final int wrListFiles_GetMore = 271;
  public static final int wrListFiles_GetAll = 272;
  public static final int wrListFiles_Pause = 273;
  public static final int wrListMessages_MsgHeader = 274;
  public static final int wrListMessages_MsgText = 275;
  public static final int wrRequestOfflineFiles_Submit = 276;
  public static final int wrRequestOfflineFiles_Done = 277;
  public static final int wrGetVolatileConfInfo_SetConfs = 278;
  public static final int wrGetVolatileConfInfo_SetConfsDone = 279;
  public static final int wrCopyBeforeDownload_Submit = 280;
  public static final int wrCopyBeforeDownload_Status = 281;
  public static final int wrCopyBeforeDownload_Remove = 282;
}
