// File: WildcatRequest.java
// (c) copyright 2002 Santronics Software Inc.
//
//****************************************************
// DO NOT EDIT THIS FILE!!!
// CPP2JAVA GENERATED FROM SOURCE FILE: wcgui.h
//****************************************************
//

package COM.winserver.wildcat;

import java.io.IOException;

public class WildcatRequest {
  public static final int wrNone = 0;
  public static final int wrLoginUser = 1;
  public static final int wrGetConferenceCount = 2;
  public static final int wrGetEffectiveConferenceCount = 3;
  public static final int wrGetConfDescs = 4;
  public static final int wrGetConferenceGroupCount = 5;
  public static final int wrGetEffectiveConferenceGroupCount = 6;
  public static final int wrGetConferenceGroups = 7;
  public static final int wrGetConferenceGroupAreas = 8;
  public static final int wrAddMessage = 9;
  public static final int wrGetFileGroupCount = 10;
  public static final int wrGetEffectiveFileGroupCount = 11;
  public static final int wrGetFileGroups = 12;
  public static final int wrGetFileGroupAreas = 13;
  public static final int wrGetFileAreaCount = 14;
  public static final int wrGetEffectiveFileAreaCount = 15;
  public static final int wrGetFileAreas = 16;
  public static final int wrListFilesByName = 17;
  public static final int wrListFilesByDate = 18;
  public static final int wrListFilesBySearch = 19;
  public static final int wrGetFileDescription = 20;
  public static final int wrGetCurrentUser = 21;
  public static final int wrUpdateCurrentUser = 22;
  public static final int wrGetUserInfo = 23;
  public static final int wrGetWhosOnline = 24;
  public static final int wrDownloadFile = 25;
  public static final int wrUploadFile = 26;
  public static final int wrUploadAttachment = 27;
  public static final int wrGetSystemInfo = 28;
  public static final int wrGetObjectFlags = 29;
  public static final int wrResolveFileName = 30;
  public static final int wrGetUserList = 31;
  public static final int wrDeleteFile = 32;
  public static final int wrViewArchive = 33;
  public static final int wrGetNodeInfoByName = 34;
  public static final int wrSetLastRead = 35;
  public static final int wrDeleteMessage = 36;
  public static final int wrSetConferenceFlags = 37;
  public static final int wrGetPackageVersion = 38;
  public static final int wrSearchUserNames = 39;
  public static final int wrListMessagesByAreaNumber = 40;
  public static final int wrListMessagesByAreaMsgId = 41;
  public static final int wrListMessagesByAreaDate = 42;
  public static final int wrListMessagesBySearch = 43;
  public static final int wrListMessagesByUnread = 44;
  public static final int wrSetMultipleConferenceFlags = 45;
  public static final int wrUpdateFileInfo = 46;
  public static final int wrGetObjectFlagsByName = 47;
  public static final int wrRequestOfflineFiles = 48;
  public static final int wrGetSecurityProfile = 49;
  public static final int wrGetDownloadStats = 50;
  public static final int wrMarkMessageRead = 51;
  public static final int wrGetVolatileConfInfo = 52;
  public static final int wrListConferencesByNumber = 53;
  public static final int wrListConferencesByName = 54;
  public static final int wrListMessagesBackwardsByMsgId = 55;
  public static final int wrListMessagesBackwardsByNumber = 56;
  public static final int wrKeepAlive = 57;
  public static final int wrGetVolatileConfInfoEx = 58;
  public static final int wrGetTimeLeftOnline = 59;
  public static final int wrWriteActivityLogEntry = 60;
  public static final int wrUploadFileEx = 61;
  public static final int wrGetServiceByName = 62;
  public static final int wrGetServerContextHandle = 63;
  public static final int wrCopyBeforeDownload = 64;
  public static final int wrGetServerChallengeString = 65;
  public static final int wrGetPredefinedChatChannels = 66;
  public static final int wrGetObjectInfo = 67;
  public static final int wrMAX = 68;
}
